import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Стартовая миграция таблиц расширения «edubridge»: разделы, уровни, курсы, слушатели, подписки, очередь доступа, преподаватели и взносы.
 *
 * Идемпотентна: на пустой базе создаёт всё, на базе, которую раньше вёл
 * synchronize, добавляет только недостающее и ничего не удаляет.
 *
 * SQL выписан TypeORM из сущностей (`pnpm schema:generate`) и переведён в
 * идемпотентную форму (`toIdempotent`), как у стартовых миграций.
 */
const UP: readonly string[] = [
  "CREATE TABLE IF NOT EXISTS \"edubridge_sections\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"title\" character varying(120) NOT NULL, \"sort_order\" integer NOT NULL DEFAULT '0', \"archived\" boolean NOT NULL DEFAULT false, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_2d11ef58c0a20525a985ad986d5\" PRIMARY KEY (\"id\"))",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_sections_title\" ON \"edubridge_sections\" (\"coopname\", \"title\") ",
  "CREATE TABLE IF NOT EXISTS \"edubridge_levels\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"section_id\" uuid NOT NULL, \"title\" character varying(60) NOT NULL, \"sort_order\" integer NOT NULL DEFAULT '0', \"archived\" boolean NOT NULL DEFAULT false, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_74771beb031c244bf7ae5e3f533\" PRIMARY KEY (\"id\"))",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_levels_title\" ON \"edubridge_levels\" (\"section_id\", \"title\") ",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_courses_direction_enum\" AS ENUM('online_platform', 'closed_community', 'onsite'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_courses_carrier_enum\" AS ENUM('skillspace', 'getcourse', 'telegram', 'vk', 'onsite'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_courses_status_enum\" AS ENUM('draft', 'published', 'archived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"edubridge_courses\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"chain_ref\" BIGSERIAL NOT NULL, \"title\" character varying(255) NOT NULL, \"section_id\" uuid, \"level_id\" uuid, \"subject\" character varying(120) DEFAULT '', \"grade\" character varying(60) DEFAULT '', \"description\" text NOT NULL DEFAULT '', \"syllabus\" text NOT NULL DEFAULT '', \"schedule\" text NOT NULL DEFAULT '', \"image\" jsonb, \"teacher_usernames\" jsonb NOT NULL DEFAULT '[]', \"lessons_per_month\" integer NOT NULL DEFAULT '0', \"lessons_total\" integer NOT NULL DEFAULT '0', \"lesson_minutes\" integer NOT NULL DEFAULT '60', \"planned_hourly_rate\" character varying(64) NOT NULL DEFAULT '0.0000 RUB', \"starts_at\" date, \"guarantee_days\" integer NOT NULL DEFAULT '14', \"teacher_reserve_balance\" character varying(64), \"teacher_settled_total\" character varying(64), \"course_payment_enabled\" boolean NOT NULL DEFAULT false, \"course_discount_bp\" integer NOT NULL DEFAULT '0', \"fee_month\" character varying(64) NOT NULL, \"direction\" \"public\".\"edubridge_courses_direction_enum\" NOT NULL DEFAULT 'online_platform', \"carrier\" \"public\".\"edubridge_courses_carrier_enum\" NOT NULL, \"external_ref\" character varying(255) NOT NULL DEFAULT '', \"external_title_seen\" character varying(255), \"external_checked_at\" TIMESTAMP WITH TIME ZONE, \"status\" \"public\".\"edubridge_courses_status_enum\" NOT NULL DEFAULT 'draft', \"sort_order\" integer NOT NULL DEFAULT '0', \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"UQ_370ab19775813ef2bd13edcc474\" UNIQUE (\"chain_ref\"), CONSTRAINT \"PK_29573c09ff964c0fefb97f2a4c3\" PRIMARY KEY (\"id\"))",
  "CREATE INDEX IF NOT EXISTS \"IDX_edubridge_courses_coop_status\" ON \"edubridge_courses\" (\"coopname\", \"status\") ",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_learners_recipient_type_enum\" AS ENUM('email', 'telegram', 'onsite'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"edubridge_learners\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"chain_ref\" BIGSERIAL NOT NULL, \"member_username\" character varying(13) NOT NULL, \"display_name\" character varying(255) NOT NULL, \"recipient_type\" \"public\".\"edubridge_learners_recipient_type_enum\" NOT NULL DEFAULT 'email', \"recipient_value\" character varying(255) NOT NULL, \"is_self\" boolean NOT NULL DEFAULT false, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"UQ_eb3622f5336ac68da70ec15115d\" UNIQUE (\"chain_ref\"), CONSTRAINT \"PK_633c67b3851e90f4741cc274af3\" PRIMARY KEY (\"id\"))",
  "CREATE INDEX IF NOT EXISTS \"IDX_edubridge_learners_member\" ON \"edubridge_learners\" (\"coopname\", \"member_username\") ",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_enrollments_period_enum\" AS ENUM('month', 'course', 'year'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_enrollments_status_enum\" AS ENUM('pending', 'active', 'expired', 'revoked', 'cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_enrollments_access_state_enum\" AS ENUM('none', 'pending', 'granted', 'revoked', 'needs_attention'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"edubridge_enrollments\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"member_username\" character varying(13) NOT NULL, \"learner_id\" uuid NOT NULL, \"course_id\" uuid NOT NULL, \"sub_hash\" character varying(64) NOT NULL, \"period\" \"public\".\"edubridge_enrollments_period_enum\" NOT NULL, \"paid_until\" TIMESTAMP WITH TIME ZONE, \"status\" \"public\".\"edubridge_enrollments_status_enum\" NOT NULL DEFAULT 'pending', \"access_state\" \"public\".\"edubridge_enrollments_access_state_enum\" NOT NULL DEFAULT 'none', \"paid_amount\" character varying(64) NOT NULL DEFAULT '0.0000 RUB', \"paid_months\" integer, \"locked_amount\" character varying(64), \"joined_at\" TIMESTAMP WITH TIME ZONE, \"cancelled_at\" TIMESTAMP WITH TIME ZONE, \"refunded_amount\" character varying(64), \"refund_reason\" character varying(32), \"statement_hash\" character varying(64), \"expiry_notified_at\" TIMESTAMP WITH TIME ZONE, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_ff7bea693497dc6509a677769f8\" PRIMARY KEY (\"id\"))",
  "CREATE INDEX IF NOT EXISTS \"IDX_edubridge_enrollments_paid_until\" ON \"edubridge_enrollments\" (\"coopname\", \"status\", \"paid_until\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_enrollments_sub_hash\" ON \"edubridge_enrollments\" (\"sub_hash\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_enrollments_unique\" ON \"edubridge_enrollments\" (\"coopname\", \"learner_id\", \"course_id\") ",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_access_tasks_kind_enum\" AS ENUM('grant', 'revoke'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_access_tasks_carrier_enum\" AS ENUM('skillspace', 'getcourse', 'telegram', 'vk', 'onsite'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_access_tasks_status_enum\" AS ENUM('pending', 'running', 'done', 'failed', 'needs_attention'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"edubridge_access_tasks\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"enrollment_id\" uuid NOT NULL, \"kind\" \"public\".\"edubridge_access_tasks_kind_enum\" NOT NULL, \"carrier\" \"public\".\"edubridge_access_tasks_carrier_enum\" NOT NULL, \"trigger_trx\" character varying(80) NOT NULL, \"recipient_override\" jsonb, \"status\" \"public\".\"edubridge_access_tasks_status_enum\" NOT NULL DEFAULT 'pending', \"attempts\" integer NOT NULL DEFAULT '0', \"next_attempt_at\" TIMESTAMP WITH TIME ZONE NOT NULL, \"last_error\" text, \"last_result\" character varying(32), \"done_at\" TIMESTAMP WITH TIME ZONE, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_b0b07f4bb112f2adcd631391a3e\" PRIMARY KEY (\"id\"))",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_access_tasks_dedup\" ON \"edubridge_access_tasks\" (\"kind\", \"enrollment_id\", \"trigger_trx\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_edubridge_access_tasks_due\" ON \"edubridge_access_tasks\" (\"coopname\", \"status\", \"next_attempt_at\") ",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_connector_bindings_carrier_enum\" AS ENUM('skillspace', 'getcourse', 'telegram', 'vk', 'onsite'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_connector_bindings_health_enum\" AS ENUM('unknown', 'ok', 'failing', 'license_limit'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"edubridge_connector_bindings\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"carrier\" \"public\".\"edubridge_connector_bindings_carrier_enum\" NOT NULL, \"enabled\" boolean NOT NULL DEFAULT true, \"health\" \"public\".\"edubridge_connector_bindings_health_enum\" NOT NULL DEFAULT 'unknown', \"last_check_at\" TIMESTAMP WITH TIME ZONE, \"last_check_message\" text, \"credentials_encrypted\" text, \"credentials_updated_at\" TIMESTAMP WITH TIME ZONE, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_4d0d127ceca8ffeafe261c9c136\" PRIMARY KEY (\"id\"))",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_connector_bindings_unique\" ON \"edubridge_connector_bindings\" (\"coopname\", \"carrier\") ",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_teacher_assignments_status_enum\" AS ENUM('draft', 'pending_approval', 'active', 'declined', 'closed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"edubridge_teacher_assignments\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"teacher_username\" character varying(13) NOT NULL, \"course_id\" uuid NOT NULL, \"schedule\" text NOT NULL DEFAULT '', \"expected_result\" text NOT NULL DEFAULT '', \"period_from\" date NOT NULL, \"period_to\" date NOT NULL, \"annex_hash\" character varying(64), \"minutes_per_month\" integer NOT NULL DEFAULT '0', \"status\" \"public\".\"edubridge_teacher_assignments_status_enum\" NOT NULL DEFAULT 'draft', \"decline_reason\" text NOT NULL DEFAULT '', \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_60c15bf9bf59b9a9b274b720ca4\" PRIMARY KEY (\"id\"))",
  "CREATE INDEX IF NOT EXISTS \"IDX_edubridge_teacher_assignments_teacher\" ON \"edubridge_teacher_assignments\" (\"coopname\", \"teacher_username\") ",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_contributions_rid_type_enum\" AS ENUM('lesson_recording', 'methodical_material', 'course_program', 'assessment_material', 'other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_contributions_status_enum\" AS ENUM('draft', 'held', 'submitted', 'council_approved', 'act_signed', 'accepted', 'declined'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_contributions_council_outcome_enum\" AS ENUM('declined', 'expired'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"edubridge_contributions\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"teacher_username\" character varying(13) NOT NULL, \"assignment_id\" uuid NOT NULL, \"rid_hash\" character varying(64) NOT NULL, \"rid_type\" \"public\".\"edubridge_contributions_rid_type_enum\" NOT NULL, \"links\" jsonb NOT NULL DEFAULT '[]', \"description\" text NOT NULL DEFAULT '', \"amount\" character varying(64) NOT NULL, \"status\" \"public\".\"edubridge_contributions_status_enum\" NOT NULL DEFAULT 'draft', \"statement_hash\" character varying(64), \"storage_act_hash\" character varying(64), \"statement_document\" jsonb, \"hold_until\" TIMESTAMP WITH TIME ZONE, \"lesson_id\" uuid, \"decision_hash\" character varying(64), \"act_hash\" character varying(64), \"act_signed\" jsonb, \"decline_reason\" text, \"council_project_hash\" character varying(64), \"council_agenda_id\" character varying(64), \"council_outcome\" \"public\".\"edubridge_contributions_council_outcome_enum\", \"council_decision_id\" character varying(64), \"decided_at\" TIMESTAMP WITH TIME ZONE, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_7786615ba8dfbc24dd9c1fec2db\" PRIMARY KEY (\"id\"))",
  "CREATE INDEX IF NOT EXISTS \"IDX_edubridge_contributions_teacher\" ON \"edubridge_contributions\" (\"coopname\", \"teacher_username\", \"status\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_contributions_rid_hash\" ON \"edubridge_contributions\" (\"rid_hash\") ",
  "CREATE TABLE IF NOT EXISTS \"edubridge_lessons\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"teacher_username\" character varying(13) NOT NULL, \"course_id\" uuid NOT NULL, \"assignment_id\" uuid NOT NULL, \"lesson_number\" integer NOT NULL, \"held_at\" TIMESTAMP WITH TIME ZONE NOT NULL, \"duration_minutes\" integer NOT NULL, \"materials\" jsonb NOT NULL DEFAULT '[]', \"topic\" text NOT NULL DEFAULT '', \"contribution_id\" uuid, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_e902af3a18d37e6883396c695e5\" PRIMARY KEY (\"id\"))",
  "CREATE INDEX IF NOT EXISTS \"IDX_edubridge_lessons_teacher\" ON \"edubridge_lessons\" (\"coopname\", \"teacher_username\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_lessons_unique\" ON \"edubridge_lessons\" (\"coopname\", \"course_id\", \"lesson_number\") ",
  "CREATE TABLE IF NOT EXISTS \"edubridge_admins\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"username\" character varying(13) NOT NULL, \"appointed_by\" character varying(13) NOT NULL, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_a25394dbbf3d8b85ece638b05ea\" PRIMARY KEY (\"id\"))",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_admins_unique\" ON \"edubridge_admins\" (\"coopname\", \"username\") ",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_teacher_contracts_status_enum\" AS ENUM('pending_approval', 'active', 'declined', 'terminated'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"edubridge_teacher_contracts\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"teacher_username\" character varying(13) NOT NULL, \"contract_hash\" character varying(64) NOT NULL, \"contract_number\" character varying(32) NOT NULL, \"hourly_rate\" character varying(64) NOT NULL DEFAULT '0.0000 RUB', \"status\" \"public\".\"edubridge_teacher_contracts_status_enum\" NOT NULL DEFAULT 'pending_approval', \"decline_reason\" text NOT NULL DEFAULT '', \"approved_at\" TIMESTAMP WITH TIME ZONE, \"signed_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_575249729056fcc93e0001c2aa8\" PRIMARY KEY (\"id\"))",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_teacher_contracts_unique\" ON \"edubridge_teacher_contracts\" (\"coopname\", \"teacher_username\") ",
  "DO $$ BEGIN CREATE TYPE \"public\".\"edubridge_return_requests_status_enum\" AS ENUM('pending', 'approved', 'declined'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"edubridge_return_requests\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(13) NOT NULL, \"member_username\" character varying(13) NOT NULL, \"amount\" character varying(64) NOT NULL, \"statement_hash\" character varying(64) NOT NULL, \"statement_document\" jsonb NOT NULL, \"status\" \"public\".\"edubridge_return_requests_status_enum\" NOT NULL DEFAULT 'pending', \"decline_reason\" character varying(512) NOT NULL DEFAULT '', \"decided_by\" character varying(13), \"decided_at\" TIMESTAMP WITH TIME ZONE, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_a2b73b00b626acc09411f8881eb\" PRIMARY KEY (\"id\"))",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_edubridge_return_requests_statement\" ON \"edubridge_return_requests\" (\"statement_hash\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_edubridge_return_requests_member\" ON \"edubridge_return_requests\" (\"coopname\", \"member_username\", \"status\") ",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"edubridge_levels\"'::regclass AND conname = 'FK_10ce1295d4f7e13095bd12d6189') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'FK_10ce1295d4f7e13095bd12d6189' AND relkind = 'i') THEN ALTER TABLE \"edubridge_levels\" ADD CONSTRAINT \"FK_10ce1295d4f7e13095bd12d6189\" FOREIGN KEY (\"section_id\") REFERENCES \"edubridge_sections\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION; END IF; END $$",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"edubridge_courses\"'::regclass AND conname = 'FK_18901a522398decf1e446ef04a6') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'FK_18901a522398decf1e446ef04a6' AND relkind = 'i') THEN ALTER TABLE \"edubridge_courses\" ADD CONSTRAINT \"FK_18901a522398decf1e446ef04a6\" FOREIGN KEY (\"section_id\") REFERENCES \"edubridge_sections\"(\"id\") ON DELETE SET NULL ON UPDATE NO ACTION; END IF; END $$",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"edubridge_courses\"'::regclass AND conname = 'FK_763741dfcddbe06bd4d1e1bf7b3') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'FK_763741dfcddbe06bd4d1e1bf7b3' AND relkind = 'i') THEN ALTER TABLE \"edubridge_courses\" ADD CONSTRAINT \"FK_763741dfcddbe06bd4d1e1bf7b3\" FOREIGN KEY (\"level_id\") REFERENCES \"edubridge_levels\"(\"id\") ON DELETE SET NULL ON UPDATE NO ACTION; END IF; END $$",
];

export class EdubridgeBaseline1790236885856 implements MigrationInterface {
  name = 'EdubridgeBaseline1790236885856';

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {
    throw new Error('EdubridgeBaseline1790236885856 не откатывается: удаление таблиц стартовой миграции стёрло бы данные');
  }
}
