/** Таблицы расширения в базе кооператива: по ним собираются типы запросов (`pnpm schema:types`). */
export default [
  'available_categories',
  'categories',
  'marketplace_apl_reception',
  'marketplace_cart',
  'marketplace_cart_item',
  'marketplace_category',
  'marketplace_consolidated_request',
  'marketplace_container',
  'marketplace_container_type',
  'marketplace_inventory',
  'marketplace_issuance_saga',
  'marketplace_ku_details',
  'marketplace_moderation_log',
  'marketplace_offer',
  'marketplace_order',
  'marketplace_outgoing_payment_request',
  'marketplace_return_claim',
  'marketplace_shipment',
  'marketplace_stock_proposal',
  'marketplace_storage_cell',
  'marketplace_supplier',
  'marketplace_supplier_claim',
  'marketplace_supplier_settings',
  'marketplace_supply_validation_log',
  'marketplace_ttn_document',
  'marketplace_vitrine',
  'marketplace_writeoff_proposal',
  'types',
] as const;
