version: '3'

services:
  hasura:
    image: hasura/graphql-engine:latest
#    ports:
#      - "8082:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/voskhod
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: youradminsecretkey
      HASURA_GRAPHQL_SERVER_PORT: 8085

  notificator:
    container_name: notificator
    build:
      context: ./components/notificator
      dockerfile: Dockerfile
    image: notificator
    env_file:
      - components/notificator/.env
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - ./:/app
    command: pnpm -F coop-notificator run start
    # command: tail -f /dev/null
    
  coopback:
    container_name: coopback
    build:
      context: ./components/coopback
      dockerfile: Dockerfile
    image: coopback
    env_file:
      - components/coopback/.env
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - ./:/app
    command: pnpm -F coopback run start


  cooparser:
    container_name: cooparser
    build:
      context: ./components/cooparser
      dockerfile: Dockerfile
    image: cooparser
    env_file:
      - components/cooparser/.env
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - ./:/app
    command: pnpm -F cooparser-ts run start
