version: '3'

services:
  notificator:
    container_name: notificator
    build:
      context: ./components/notificator
      dockerfile: Dockerfile
    image: notificator
    env_file:
      - components/notificator/.env
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - ./:/app
    command: pnpm -F coop-notificator run start
    # command: tail -f /dev/null
    
  coopback:
    container_name: coopback
    build:
      context: ./components/coopback
      dockerfile: Dockerfile
    image: coopback
    env_file:
      - components/coopback/.env
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - ./:/app
    command: pnpm -F coopback run start


  cooparser:
    container_name: cooparser
    build:
      context: ./components/cooparser
      dockerfile: Dockerfile
    image: cooparser
    env_file:
      - components/cooparser/.env
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - ./:/app
    command: pnpm -F cooparser-ts run start
