import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Стартовая миграция таблиц ядра: 39 таблиц.
 *
 * Идемпотентна: на пустой базе создаёт всё, на базе, которую раньше вёл
 * synchronize, добавляет только недостающее и ничего не удаляет.
 *
 * Сгенерировано командой `pnpm schema:baseline` — SQL выписан TypeORM из сущностей.
 */
const UP: readonly string[] = [
  "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"",
  "CREATE TABLE IF NOT EXISTS \"entity_versions\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"entity_table\" character varying(100) NOT NULL, \"entity_id\" character varying(36) NOT NULL, \"previous_data\" jsonb NOT NULL, \"block_num\" integer, \"change_type\" character varying(50) NOT NULL, \"metadata\" jsonb, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_564bb2516cf0a2db81b3c21bdee\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"invalidated_entities\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"entity_table\" character varying(100) NOT NULL, \"entity_id\" character varying(64) NOT NULL, \"data\" jsonb NOT NULL, \"invalidated_by_block\" integer NOT NULL, \"fork_event_id\" character varying(128), \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_6a11f94cbe17340008972be73b0\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"invalidated_entity_versions\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"entity_table\" character varying(100) NOT NULL, \"entity_id\" character varying(64) NOT NULL, \"previous_data\" jsonb NOT NULL, \"original_block_num\" integer, \"invalidated_by_block\" integer NOT NULL, \"fork_event_id\" character varying(128), \"change_type\" character varying(50) NOT NULL, \"metadata\" jsonb, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_5a4d4083e5ce63e81f8db217095\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"tracking_rules\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"hash\" character varying(64) NOT NULL, \"event_type\" character varying(20) NOT NULL, \"vars_field\" character varying(50) NOT NULL, \"metadata\" jsonb, \"active\" boolean NOT NULL DEFAULT true, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_d50bb72d95ea76a5c5e26cc5984\" UNIQUE (\"hash\"), CONSTRAINT \"PK_54e36fc983caf6601fa32f31129\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"web_push_subscriptions\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"username\" character varying(255) NOT NULL, \"endpoint\" text NOT NULL, \"p256dhKey\" character varying(255) NOT NULL, \"authKey\" character varying(255) NOT NULL, \"userAgent\" text, \"isActive\" boolean NOT NULL DEFAULT true, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_8fdd353125d839be247dfdd8caa\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"vaults\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"username\" character varying(50) NOT NULL, \"permission\" character varying(20) NOT NULL DEFAULT 'active', \"wif\" text NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_487a5346fa3693a430b6d6db60c\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"users\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"username\" character varying(50) NOT NULL, \"status\" character varying(20) NOT NULL, \"message\" text NOT NULL DEFAULT '', \"is_registered\" boolean NOT NULL DEFAULT false, \"has_account\" boolean NOT NULL DEFAULT false, \"type\" character varying(20) NOT NULL, \"public_key\" text NOT NULL DEFAULT '', \"referer\" character varying(100) NOT NULL DEFAULT '', \"email\" character varying(255), \"role\" character varying(20) NOT NULL DEFAULT 'user', \"is_email_verified\" boolean NOT NULL DEFAULT false, \"subscriber_id\" character varying(100) NOT NULL DEFAULT '', \"subscriber_hash\" character varying(255) NOT NULL DEFAULT '', \"legacy_mongo_id\" character varying(50), \"joined_at\" TIMESTAMP WITH TIME ZONE, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_fe0bb3f6520ee0469504521e710\" UNIQUE (\"username\"), CONSTRAINT \"PK_a3ffb1c0c8416b9fc6f907b7433\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"user_wallets\" (\"_id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"block_num\" integer NOT NULL DEFAULT '0', \"present\" boolean NOT NULL DEFAULT false, \"status\" character varying NOT NULL DEFAULT 'UNDEFINED', \"_created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"_updated_at\" TIMESTAMP NOT NULL DEFAULT now(), \"id\" character varying(20) NOT NULL, \"coopname\" character varying(12) NOT NULL, \"wallet_name\" character varying(12) NOT NULL, \"username\" character varying(12) NOT NULL, \"available\" character varying(50) NOT NULL, \"blocked\" character varying(50) NOT NULL, CONSTRAINT \"UQ_f98089275dcfc65d59b1d347167\" UNIQUE (\"id\"), CONSTRAINT \"PK_11fb4403d711227492f384c24ae\" PRIMARY KEY (\"_id\"))",
  "CREATE TABLE IF NOT EXISTS \"user_agreements\" (\"_id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"block_num\" integer NOT NULL DEFAULT '0', \"present\" boolean NOT NULL DEFAULT false, \"status\" character varying NOT NULL DEFAULT 'UNDEFINED', \"_created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"_updated_at\" TIMESTAMP NOT NULL DEFAULT now(), \"coopname\" character varying(12) NOT NULL, \"username\" character varying(12) NOT NULL, \"programs\" jsonb NOT NULL DEFAULT '[]', CONSTRAINT \"PK_231e44044256f0f90ae45b028a1\" PRIMARY KEY (\"_id\"))",
  "CREATE TABLE IF NOT EXISTS \"tokens\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"token\" character varying(1024) NOT NULL, \"user_id\" character varying(50) NOT NULL, \"type\" character varying(20) NOT NULL, \"expires\" TIMESTAMP NOT NULL, \"blacklisted\" boolean NOT NULL DEFAULT false, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_6a8ca5961656d13c16c04079dd3\" UNIQUE (\"token\"), CONSTRAINT \"PK_3001e89ada36263dabf1fb6210a\" PRIMARY KEY (\"id\"))",
  "DO $$ BEGIN CREATE TYPE \"public\".\"system_status_status_enum\" AS ENUM('install', 'initialized', 'active', 'maintenance'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"system_status\" (\"coopname\" character varying(12) NOT NULL, \"status\" \"public\".\"system_status_status_enum\" NOT NULL DEFAULT 'install', \"install_code\" character varying(255), \"install_code_expires_at\" TIMESTAMP, \"init_by_server\" boolean NOT NULL DEFAULT false, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_6d41625a93b9f58f3ddfb00a42b\" PRIMARY KEY (\"coopname\"))",
  "CREATE TABLE IF NOT EXISTS \"signed_documents\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(50) NOT NULL, \"package\" character varying(64) NOT NULL, \"doc_hash\" character varying(64) NOT NULL DEFAULT '', \"hash\" character varying(64) NOT NULL, \"username\" character varying(50) NOT NULL DEFAULT '', \"status\" character varying(20) NOT NULL DEFAULT 'submitted', \"action\" character varying(20) NOT NULL DEFAULT '', \"registry_id\" integer NOT NULL DEFAULT '0', \"full_title\" text NOT NULL DEFAULT '', \"content_text\" text NOT NULL DEFAULT '', \"signers_text\" text NOT NULL DEFAULT '', \"block_num\" bigint, \"document_created_at\" TIMESTAMP WITH TIME ZONE, \"document_aggregate\" jsonb, \"source_action_data\" jsonb, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_2b206e85f339fdac189d730955a\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"blockchain_sync_state\" (\"key\" character varying(50) NOT NULL, \"block_num\" bigint NOT NULL, \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_5bf17cbf61f49a7a31959b2baf0\" PRIMARY KEY (\"key\"))",
  "CREATE TABLE IF NOT EXISTS \"settings\" (\"coopname\" character varying(12) NOT NULL, \"provider_name\" character varying(50) NOT NULL DEFAULT 'qrpay', \"authorized_default_workspace\" character varying(50) NOT NULL, \"authorized_default_route\" character varying(50) NOT NULL, \"non_authorized_default_workspace\" character varying(50) NOT NULL, \"non_authorized_default_route\" character varying(50) NOT NULL, \"extra_settings\" jsonb NOT NULL DEFAULT '{}', \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_eb46f075ecbcd892188ed8234a2\" PRIMARY KEY (\"coopname\"))",
  "CREATE TABLE IF NOT EXISTS \"program_wallets\" (\"_id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"block_num\" integer NOT NULL DEFAULT '0', \"present\" boolean NOT NULL DEFAULT false, \"status\" character varying NOT NULL DEFAULT 'UNDEFINED', \"_created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"_updated_at\" TIMESTAMP NOT NULL DEFAULT now(), \"id\" character varying(20) NOT NULL, \"coopname\" character varying(12) NOT NULL, \"program_id\" character varying(20) NOT NULL, \"agreement_id\" character varying(20) NOT NULL, \"username\" character varying(12) NOT NULL, \"available\" character varying(50) NOT NULL, \"blocked\" character varying(50) NOT NULL, \"membership_contribution\" character varying(50) NOT NULL, CONSTRAINT \"UQ_71875fb46556328da4588eb3fb3\" UNIQUE (\"id\"), CONSTRAINT \"PK_53c9c359c1b2f33f4b2d048fbd6\" PRIMARY KEY (\"_id\"))",
  "DO $$ BEGIN CREATE TYPE \"public\".\"payments_type_enum\" AS ENUM('registration', 'deposit', 'withdrawal', 'payment', 'registration_refund', 'membership_exit', 'expense', 'expense_return', 'expense_overspend', 'aid', 'tax'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"payments_direction_enum\" AS ENUM('incoming', 'outgoing'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "DO $$ BEGIN CREATE TYPE \"public\".\"payments_status_enum\" AS ENUM('awaiting_authorization', 'pending', 'processing', 'paid', 'completed', 'failed', 'expired', 'cancelled', 'refunded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"payments\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"hash\" character varying NOT NULL, \"coopname\" character varying NOT NULL, \"username\" character varying NOT NULL, \"quantity\" integer NOT NULL, \"symbol\" character varying NOT NULL, \"type\" \"public\".\"payments_type_enum\" NOT NULL, \"direction\" \"public\".\"payments_direction_enum\" NOT NULL, \"status\" \"public\".\"payments_status_enum\" NOT NULL DEFAULT 'pending', \"provider\" character varying, \"payment_method_id\" character varying, \"secret\" character varying, \"message\" text, \"memo\" text, \"expired_at\" TIMESTAMP, \"completed_at\" TIMESTAMP, \"failed_at\" TIMESTAMP, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP DEFAULT now(), \"payment_details\" json, \"blockchain_data\" json, \"statement\" json, \"related_extension\" character varying(64), \"related_entity_id\" character varying(64), CONSTRAINT \"PK_197ab7af18c93fbb0c9b28b4a59\" PRIMARY KEY (\"id\"))",
  "DO $$ BEGIN CREATE TYPE \"public\".\"payment_files_kind_enum\" AS ENUM('PAYMENT_PROOF'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"payment_files\" (\"id\" SERIAL NOT NULL, \"coopname\" character varying NOT NULL, \"payment_hash\" character varying NOT NULL, \"kind\" \"public\".\"payment_files_kind_enum\" NOT NULL, \"checksum_sha256\" character varying(64) NOT NULL, \"mime_type\" character varying(120) NOT NULL, \"size_bytes\" integer NOT NULL, \"storage_key\" character varying(512) NOT NULL, \"original_filename\" character varying(255), \"uploaded_by_username\" character varying NOT NULL, \"uploaded_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_ce02c5038ad1ac2ab490537f07b\" PRIMARY KEY (\"id\")); COMMENT ON COLUMN \"payment_files\".\"original_filename\" IS 'Оригинальное имя загруженного файла — для отображения и поиска'",
  "CREATE TABLE IF NOT EXISTS \"notification_outbox\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(255) NOT NULL, \"workflowId\" character varying(255) NOT NULL, \"channel\" character varying(32) NOT NULL, \"recipientSubscriberId\" character varying(255) NOT NULL, \"recipientEmail\" character varying(255), \"recipientUsername\" character varying(255), \"payload\" json, \"actorSubscriberId\" character varying(255), \"idempotencyKey\" character varying(64) NOT NULL, \"status\" character varying(16) NOT NULL DEFAULT 'pending', \"attempts\" integer NOT NULL DEFAULT '0', \"maxAttempts\" integer NOT NULL DEFAULT '5', \"scheduledAt\" TIMESTAMP NOT NULL, \"lastError\" text, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_83d47c7dba1da2d038749fe757e\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"payment_state\" (\"accountNumber\" character varying(50) NOT NULL, \"statementDate\" character varying(10) NOT NULL, \"lastProcessedPage\" integer NOT NULL DEFAULT '1', \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_8c5b79a830f66f8a78f8c01623b\" PRIMARY KEY (\"accountNumber\", \"statementDate\"))",
  "CREATE TABLE IF NOT EXISTS \"notification_inbox\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(255) NOT NULL, \"outboxId\" uuid NOT NULL, \"recipientSubscriberId\" character varying(255) NOT NULL, \"recipientUsername\" character varying(255), \"workflowId\" character varying(255) NOT NULL, \"title\" character varying(512) NOT NULL, \"body\" text NOT NULL, \"payload\" json, \"actorSubscriberId\" character varying(255), \"isRead\" boolean NOT NULL DEFAULT false, \"readAt\" TIMESTAMP, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_c012d0f936cba300e084d3d8d5a\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"notification_deliveries\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"outboxId\" uuid NOT NULL, \"coopname\" character varying(255) NOT NULL, \"channel\" character varying(32) NOT NULL, \"recipientSubscriberId\" character varying(255) NOT NULL, \"workflowId\" character varying(255) NOT NULL, \"attemptNumber\" integer NOT NULL, \"status\" character varying(16) NOT NULL, \"providerResponse\" text, \"error\" text, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_81daeff81f237bd384f7cfc4a4c\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"mutation_logs\" (\"_id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying(255), \"mutation_name\" character varying(255) NOT NULL, \"username\" character varying(255) NOT NULL, \"arguments\" jsonb NOT NULL, \"duration_ms\" integer NOT NULL, \"status\" character varying(20) NOT NULL, \"error_message\" text, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_b9e664a2d1916bb216849998218\" PRIMARY KEY (\"_id\"))",
  "CREATE TABLE IF NOT EXISTS \"migrations\" (\"version\" character varying NOT NULL, \"name\" character varying NOT NULL, \"executedAt\" TIMESTAMP NOT NULL, \"success\" boolean NOT NULL DEFAULT true, \"logs\" text, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_48d16a7a82a1b1d3103a0c605e1\" PRIMARY KEY (\"version\"))",
  "CREATE TABLE IF NOT EXISTS \"membership_exit_requests\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coopname\" character varying NOT NULL, \"username\" character varying NOT NULL, \"exit_hash\" character varying(64) NOT NULL, \"statement\" jsonb NOT NULL, \"token\" character varying(1024) NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_c71c44ba9d41296ba0748530ee2\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"meet_processed\" (\"hash\" character varying NOT NULL, \"coopname\" jsonb NOT NULL, \"presider\" character varying NOT NULL, \"secretary\" character varying NOT NULL, \"results\" jsonb NOT NULL, \"signed_ballots\" integer NOT NULL, \"quorum_percent\" integer NOT NULL, \"quorum_passed\" boolean NOT NULL, \"decision\" jsonb NOT NULL, CONSTRAINT \"PK_a422d7d8d16a5de245a4ac4214d\" PRIMARY KEY (\"hash\"))",
  "CREATE TABLE IF NOT EXISTS \"extensions_logs\" (\"id\" SERIAL NOT NULL, \"name\" character varying(12) NOT NULL, \"extension_local_id\" integer NOT NULL DEFAULT '0', \"data\" jsonb NOT NULL DEFAULT '{}', \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_bc2b123d0854015250d7b165d22\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"ipn\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"provider\" character varying(50) NOT NULL, \"data\" jsonb NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_d301ba412540fd525249645926d\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"blockchain_forks\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"chain_id\" character varying NOT NULL, \"block_num\" bigint NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_45e8e8bfa7f331a4c5dfd51878e\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"ledger_operations\" (\"global_sequence\" bigint NOT NULL, \"coopname\" character varying(12) NOT NULL, \"action\" character varying(20) NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"account_id\" bigint, \"quantity\" character varying(100), \"comment\" text, \"hash\" character varying(64), \"username\" character varying(12), CONSTRAINT \"PK_112bdb60e151bd9fae7ac385037\" PRIMARY KEY (\"global_sequence\"))",
  "CREATE TABLE IF NOT EXISTS \"extensions\" (\"name\" character varying(12) NOT NULL, \"enabled\" boolean NOT NULL DEFAULT true, \"config\" jsonb NOT NULL DEFAULT '{}', \"schema_version\" integer NOT NULL DEFAULT '1', \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_049b5a9a1938e67b19196c7cfea\" PRIMARY KEY (\"name\"))",
  "CREATE TABLE IF NOT EXISTS \"draft_translations\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"draft_id\" bigint NOT NULL, \"lang\" character varying(16) NOT NULL, \"block_num\" bigint NOT NULL, \"value\" jsonb NOT NULL, \"present\" boolean NOT NULL DEFAULT true, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_b2c91a60be5f9567b9559fcda99\" UNIQUE (\"draft_id\", \"lang\", \"block_num\"), CONSTRAINT \"PK_7d5d15c0f49d269b63a9a275cfe\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"draft_templates\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"registry_id\" bigint NOT NULL, \"block_num\" bigint NOT NULL, \"value\" jsonb NOT NULL, \"present\" boolean NOT NULL DEFAULT true, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_f0293727847fc362617ccd48920\" UNIQUE (\"registry_id\", \"block_num\"), CONSTRAINT \"PK_702989e2137730dad7bce950de8\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"blockchain_deltas\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"chain_id\" character varying NOT NULL, \"block_num\" bigint NOT NULL, \"block_id\" character varying NOT NULL, \"block_time\" TIMESTAMP WITH TIME ZONE, \"present\" boolean NOT NULL, \"code\" character varying NOT NULL, \"scope\" character varying NOT NULL, \"table\" character varying NOT NULL, \"primary_key\" character varying NOT NULL, \"value\" jsonb, \"repeat\" boolean NOT NULL DEFAULT false, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_82b75f71b19761c80e82018d6a3\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"consumer_dedup\" (\"event_id\" character varying(512) NOT NULL, \"applied_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"block_num\" bigint, CONSTRAINT \"PK_d99bfea33207fab6dce3593c3f3\" PRIMARY KEY (\"event_id\"))",
  "CREATE TABLE IF NOT EXISTS \"chain_texts\" (\"digest\" character varying(64) NOT NULL, \"text\" text NOT NULL, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_72701acc35cb2ab392c721ebd75\" PRIMARY KEY (\"digest\"))",
  "CREATE TABLE IF NOT EXISTS \"candidates\" (\"username\" character varying NOT NULL, \"coopname\" character varying NOT NULL, \"braname\" character varying, \"status\" character varying NOT NULL, \"registered_at\" TIMESTAMP, \"type\" character varying NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"statement\" json, \"wallet_agreement\" json, \"signature_agreement\" json, \"privacy_agreement\" json, \"user_agreement\" json, \"blagorost_offer\" json, \"generator_offer\" json, \"program_agreements\" jsonb NOT NULL DEFAULT '{}', \"intake_answers\" jsonb NOT NULL DEFAULT '{}', \"program_key\" character varying, \"registration_hash\" character varying NOT NULL, \"referer\" character varying, \"public_key\" character varying NOT NULL, \"meta\" character varying, CONSTRAINT \"PK_5bf422cbe966fa7e6a335f76d7b\" PRIMARY KEY (\"username\"))",
  "CREATE TABLE IF NOT EXISTS \"meet_pre\" (\"hash\" character varying NOT NULL, \"coopname\" character varying NOT NULL, \"initiator\" character varying NOT NULL, \"presider\" character varying NOT NULL, \"secretary\" character varying NOT NULL, \"agenda\" jsonb NOT NULL, \"open_at\" TIMESTAMP NOT NULL, \"close_at\" TIMESTAMP NOT NULL, \"proposal\" jsonb, \"details\" text, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_6f0e282d41fee369cf30ae9e393\" PRIMARY KEY (\"hash\"))",
  "CREATE TABLE IF NOT EXISTS \"agreements\" (\"_id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"block_num\" integer NOT NULL DEFAULT '0', \"present\" boolean NOT NULL DEFAULT false, \"status\" character varying NOT NULL DEFAULT 'registered', \"_created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"_updated_at\" TIMESTAMP NOT NULL DEFAULT now(), \"id\" integer, \"coopname\" character varying(12) NOT NULL, \"username\" character varying(12) NOT NULL, \"type\" character varying(50) NOT NULL, \"program_id\" integer NOT NULL, \"draft_id\" integer NOT NULL, \"version\" integer NOT NULL, \"document\" json NOT NULL, \"blockchain_status\" character varying(20) NOT NULL, \"updated_at\" TIMESTAMP NOT NULL, CONSTRAINT \"UQ_01532f6c999d44c776e3d1fa4c8\" UNIQUE (\"id\"), CONSTRAINT \"PK_e9a2c223a2757e41dbb05113436\" PRIMARY KEY (\"_id\"))",
  "CREATE TABLE IF NOT EXISTS \"blockchain_actions\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"transaction_id\" character varying(64) NOT NULL, \"account\" character varying(16) NOT NULL, \"block_num\" bigint NOT NULL, \"block_id\" character varying(64) NOT NULL, \"block_time\" TIMESTAMP WITH TIME ZONE, \"chain_id\" character varying(64) NOT NULL, \"name\" character varying(16) NOT NULL, \"receiver\" character varying(16) NOT NULL, \"authorization\" jsonb NOT NULL, \"data\" jsonb NOT NULL, \"action_ordinal\" integer NOT NULL, \"global_sequence\" character varying(32) NOT NULL, \"account_ram_deltas\" jsonb NOT NULL, \"console\" text, \"receipt\" jsonb NOT NULL, \"creator_action_ordinal\" integer NOT NULL, \"context_free\" boolean NOT NULL, \"elapsed\" integer NOT NULL, \"repeat\" boolean NOT NULL DEFAULT false, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_430392bdea58360e8b4abded407\" PRIMARY KEY (\"id\"))",
  "ALTER TABLE \"entity_versions\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"entity_versions\" ADD COLUMN IF NOT EXISTS \"entity_table\" character varying(100) NOT NULL",
  "ALTER TABLE \"entity_versions\" ADD COLUMN IF NOT EXISTS \"entity_id\" character varying(36) NOT NULL",
  "ALTER TABLE \"entity_versions\" ADD COLUMN IF NOT EXISTS \"previous_data\" jsonb NOT NULL",
  "ALTER TABLE \"entity_versions\" ADD COLUMN IF NOT EXISTS \"block_num\" integer",
  "ALTER TABLE \"entity_versions\" ADD COLUMN IF NOT EXISTS \"change_type\" character varying(50) NOT NULL",
  "ALTER TABLE \"entity_versions\" ADD COLUMN IF NOT EXISTS \"metadata\" jsonb",
  "ALTER TABLE \"entity_versions\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"invalidated_entities\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"invalidated_entities\" ADD COLUMN IF NOT EXISTS \"entity_table\" character varying(100) NOT NULL",
  "ALTER TABLE \"invalidated_entities\" ADD COLUMN IF NOT EXISTS \"entity_id\" character varying(64) NOT NULL",
  "ALTER TABLE \"invalidated_entities\" ADD COLUMN IF NOT EXISTS \"data\" jsonb NOT NULL",
  "ALTER TABLE \"invalidated_entities\" ADD COLUMN IF NOT EXISTS \"invalidated_by_block\" integer NOT NULL",
  "ALTER TABLE \"invalidated_entities\" ADD COLUMN IF NOT EXISTS \"fork_event_id\" character varying(128)",
  "ALTER TABLE \"invalidated_entities\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"invalidated_entity_versions\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"invalidated_entity_versions\" ADD COLUMN IF NOT EXISTS \"entity_table\" character varying(100) NOT NULL",
  "ALTER TABLE \"invalidated_entity_versions\" ADD COLUMN IF NOT EXISTS \"entity_id\" character varying(64) NOT NULL",
  "ALTER TABLE \"invalidated_entity_versions\" ADD COLUMN IF NOT EXISTS \"previous_data\" jsonb NOT NULL",
  "ALTER TABLE \"invalidated_entity_versions\" ADD COLUMN IF NOT EXISTS \"original_block_num\" integer",
  "ALTER TABLE \"invalidated_entity_versions\" ADD COLUMN IF NOT EXISTS \"invalidated_by_block\" integer NOT NULL",
  "ALTER TABLE \"invalidated_entity_versions\" ADD COLUMN IF NOT EXISTS \"fork_event_id\" character varying(128)",
  "ALTER TABLE \"invalidated_entity_versions\" ADD COLUMN IF NOT EXISTS \"change_type\" character varying(50) NOT NULL",
  "ALTER TABLE \"invalidated_entity_versions\" ADD COLUMN IF NOT EXISTS \"metadata\" jsonb",
  "ALTER TABLE \"invalidated_entity_versions\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"tracking_rules\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"tracking_rules\" ADD COLUMN IF NOT EXISTS \"hash\" character varying(64) NOT NULL",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"tracking_rules\"'::regclass AND conname = 'UQ_d50bb72d95ea76a5c5e26cc5984') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_d50bb72d95ea76a5c5e26cc5984' AND relkind = 'i') THEN ALTER TABLE \"tracking_rules\" ADD CONSTRAINT \"UQ_d50bb72d95ea76a5c5e26cc5984\" UNIQUE (\"hash\"); END IF; END $$",
  "ALTER TABLE \"tracking_rules\" ADD COLUMN IF NOT EXISTS \"event_type\" character varying(20) NOT NULL",
  "ALTER TABLE \"tracking_rules\" ADD COLUMN IF NOT EXISTS \"vars_field\" character varying(50) NOT NULL",
  "ALTER TABLE \"tracking_rules\" ADD COLUMN IF NOT EXISTS \"metadata\" jsonb",
  "ALTER TABLE \"tracking_rules\" ADD COLUMN IF NOT EXISTS \"active\" boolean NOT NULL DEFAULT true",
  "ALTER TABLE \"tracking_rules\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"web_push_subscriptions\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"web_push_subscriptions\" ADD COLUMN IF NOT EXISTS \"username\" character varying(255) NOT NULL",
  "ALTER TABLE \"web_push_subscriptions\" ADD COLUMN IF NOT EXISTS \"endpoint\" text NOT NULL",
  "ALTER TABLE \"web_push_subscriptions\" ADD COLUMN IF NOT EXISTS \"p256dhKey\" character varying(255) NOT NULL",
  "ALTER TABLE \"web_push_subscriptions\" ADD COLUMN IF NOT EXISTS \"authKey\" character varying(255) NOT NULL",
  "ALTER TABLE \"web_push_subscriptions\" ADD COLUMN IF NOT EXISTS \"userAgent\" text",
  "ALTER TABLE \"web_push_subscriptions\" ADD COLUMN IF NOT EXISTS \"isActive\" boolean NOT NULL DEFAULT true",
  "ALTER TABLE \"web_push_subscriptions\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"web_push_subscriptions\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"vaults\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"vaults\" ADD COLUMN IF NOT EXISTS \"username\" character varying(50) NOT NULL",
  "ALTER TABLE \"vaults\" ADD COLUMN IF NOT EXISTS \"permission\" character varying(20) NOT NULL DEFAULT 'active'",
  "ALTER TABLE \"vaults\" ADD COLUMN IF NOT EXISTS \"wif\" text NOT NULL",
  "ALTER TABLE \"vaults\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"vaults\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"username\" character varying(50) NOT NULL",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"users\"'::regclass AND conname = 'UQ_fe0bb3f6520ee0469504521e710') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_fe0bb3f6520ee0469504521e710' AND relkind = 'i') THEN ALTER TABLE \"users\" ADD CONSTRAINT \"UQ_fe0bb3f6520ee0469504521e710\" UNIQUE (\"username\"); END IF; END $$",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"status\" character varying(20) NOT NULL",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"message\" text NOT NULL DEFAULT ''",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"is_registered\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"has_account\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"type\" character varying(20) NOT NULL",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"public_key\" text NOT NULL DEFAULT ''",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"referer\" character varying(100) NOT NULL DEFAULT ''",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"email\" character varying(255)",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"role\" character varying(20) NOT NULL DEFAULT 'user'",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"is_email_verified\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"subscriber_id\" character varying(100) NOT NULL DEFAULT ''",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"subscriber_hash\" character varying(255) NOT NULL DEFAULT ''",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"legacy_mongo_id\" character varying(50)",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"joined_at\" TIMESTAMP WITH TIME ZONE",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"users\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"_id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"block_num\" integer NOT NULL DEFAULT '0'",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"present\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"status\" character varying NOT NULL DEFAULT 'UNDEFINED'",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"_created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"_updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"id\" character varying(20) NOT NULL",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"user_wallets\"'::regclass AND conname = 'UQ_f98089275dcfc65d59b1d347167') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_f98089275dcfc65d59b1d347167' AND relkind = 'i') THEN ALTER TABLE \"user_wallets\" ADD CONSTRAINT \"UQ_f98089275dcfc65d59b1d347167\" UNIQUE (\"id\"); END IF; END $$",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(12) NOT NULL",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"wallet_name\" character varying(12) NOT NULL",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"username\" character varying(12) NOT NULL",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"available\" character varying(50) NOT NULL",
  "ALTER TABLE \"user_wallets\" ADD COLUMN IF NOT EXISTS \"blocked\" character varying(50) NOT NULL",
  "ALTER TABLE \"user_agreements\" ADD COLUMN IF NOT EXISTS \"_id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"user_agreements\" ADD COLUMN IF NOT EXISTS \"block_num\" integer NOT NULL DEFAULT '0'",
  "ALTER TABLE \"user_agreements\" ADD COLUMN IF NOT EXISTS \"present\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"user_agreements\" ADD COLUMN IF NOT EXISTS \"status\" character varying NOT NULL DEFAULT 'UNDEFINED'",
  "ALTER TABLE \"user_agreements\" ADD COLUMN IF NOT EXISTS \"_created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"user_agreements\" ADD COLUMN IF NOT EXISTS \"_updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"user_agreements\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(12) NOT NULL",
  "ALTER TABLE \"user_agreements\" ADD COLUMN IF NOT EXISTS \"username\" character varying(12) NOT NULL",
  "ALTER TABLE \"user_agreements\" ADD COLUMN IF NOT EXISTS \"programs\" jsonb NOT NULL DEFAULT '[]'",
  "ALTER TABLE \"tokens\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"tokens\" ADD COLUMN IF NOT EXISTS \"token\" character varying(1024) NOT NULL",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"tokens\"'::regclass AND conname = 'UQ_6a8ca5961656d13c16c04079dd3') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_6a8ca5961656d13c16c04079dd3' AND relkind = 'i') THEN ALTER TABLE \"tokens\" ADD CONSTRAINT \"UQ_6a8ca5961656d13c16c04079dd3\" UNIQUE (\"token\"); END IF; END $$",
  "ALTER TABLE \"tokens\" ADD COLUMN IF NOT EXISTS \"user_id\" character varying(50) NOT NULL",
  "ALTER TABLE \"tokens\" ADD COLUMN IF NOT EXISTS \"type\" character varying(20) NOT NULL",
  "ALTER TABLE \"tokens\" ADD COLUMN IF NOT EXISTS \"expires\" TIMESTAMP NOT NULL",
  "ALTER TABLE \"tokens\" ADD COLUMN IF NOT EXISTS \"blacklisted\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"tokens\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"tokens\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"system_status\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(12) NOT NULL",
  "ALTER TABLE \"system_status\" ADD COLUMN IF NOT EXISTS \"status\" \"public\".\"system_status_status_enum\" NOT NULL DEFAULT 'install'",
  "ALTER TABLE \"system_status\" ADD COLUMN IF NOT EXISTS \"install_code\" character varying(255)",
  "ALTER TABLE \"system_status\" ADD COLUMN IF NOT EXISTS \"install_code_expires_at\" TIMESTAMP",
  "ALTER TABLE \"system_status\" ADD COLUMN IF NOT EXISTS \"init_by_server\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"system_status\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"system_status\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(50) NOT NULL",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"package\" character varying(64) NOT NULL",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"doc_hash\" character varying(64) NOT NULL DEFAULT ''",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"hash\" character varying(64) NOT NULL",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"username\" character varying(50) NOT NULL DEFAULT ''",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"status\" character varying(20) NOT NULL DEFAULT 'submitted'",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"action\" character varying(20) NOT NULL DEFAULT ''",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"registry_id\" integer NOT NULL DEFAULT '0'",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"full_title\" text NOT NULL DEFAULT ''",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"content_text\" text NOT NULL DEFAULT ''",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"signers_text\" text NOT NULL DEFAULT ''",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"block_num\" bigint",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"document_created_at\" TIMESTAMP WITH TIME ZONE",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"document_aggregate\" jsonb",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"source_action_data\" jsonb",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"signed_documents\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"blockchain_sync_state\" ADD COLUMN IF NOT EXISTS \"key\" character varying(50) NOT NULL",
  "ALTER TABLE \"blockchain_sync_state\" ADD COLUMN IF NOT EXISTS \"block_num\" bigint NOT NULL",
  "ALTER TABLE \"blockchain_sync_state\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(12) NOT NULL",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"provider_name\" character varying(50) NOT NULL DEFAULT 'qrpay'",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"authorized_default_workspace\" character varying(50) NOT NULL",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"authorized_default_route\" character varying(50) NOT NULL",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"non_authorized_default_workspace\" character varying(50) NOT NULL",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"non_authorized_default_route\" character varying(50) NOT NULL",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"extra_settings\" jsonb NOT NULL DEFAULT '{}'",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"settings\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"_id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"block_num\" integer NOT NULL DEFAULT '0'",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"present\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"status\" character varying NOT NULL DEFAULT 'UNDEFINED'",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"_created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"_updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"id\" character varying(20) NOT NULL",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"program_wallets\"'::regclass AND conname = 'UQ_71875fb46556328da4588eb3fb3') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_71875fb46556328da4588eb3fb3' AND relkind = 'i') THEN ALTER TABLE \"program_wallets\" ADD CONSTRAINT \"UQ_71875fb46556328da4588eb3fb3\" UNIQUE (\"id\"); END IF; END $$",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(12) NOT NULL",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"program_id\" character varying(20) NOT NULL",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"agreement_id\" character varying(20) NOT NULL",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"username\" character varying(12) NOT NULL",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"available\" character varying(50) NOT NULL",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"blocked\" character varying(50) NOT NULL",
  "ALTER TABLE \"program_wallets\" ADD COLUMN IF NOT EXISTS \"membership_contribution\" character varying(50) NOT NULL",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"hash\" character varying NOT NULL",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying NOT NULL",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"username\" character varying NOT NULL",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"quantity\" integer NOT NULL",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"symbol\" character varying NOT NULL",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"type\" \"public\".\"payments_type_enum\" NOT NULL",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"direction\" \"public\".\"payments_direction_enum\" NOT NULL",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"status\" \"public\".\"payments_status_enum\" NOT NULL DEFAULT 'pending'",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"provider\" character varying",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"payment_method_id\" character varying",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"secret\" character varying",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"message\" text",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"memo\" text",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"expired_at\" TIMESTAMP",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"completed_at\" TIMESTAMP",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"failed_at\" TIMESTAMP",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP DEFAULT now()",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"payment_details\" json",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"blockchain_data\" json",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"statement\" json",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"related_extension\" character varying(64)",
  "ALTER TABLE \"payments\" ADD COLUMN IF NOT EXISTS \"related_entity_id\" character varying(64)",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"id\" SERIAL NOT NULL",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying NOT NULL",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"payment_hash\" character varying NOT NULL",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"kind\" \"public\".\"payment_files_kind_enum\" NOT NULL",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"checksum_sha256\" character varying(64) NOT NULL",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"mime_type\" character varying(120) NOT NULL",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"size_bytes\" integer NOT NULL",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"storage_key\" character varying(512) NOT NULL",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"original_filename\" character varying(255)",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"uploaded_by_username\" character varying NOT NULL",
  "ALTER TABLE \"payment_files\" ADD COLUMN IF NOT EXISTS \"uploaded_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(255) NOT NULL",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"workflowId\" character varying(255) NOT NULL",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"channel\" character varying(32) NOT NULL",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"recipientSubscriberId\" character varying(255) NOT NULL",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"recipientEmail\" character varying(255)",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"recipientUsername\" character varying(255)",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"payload\" json",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"actorSubscriberId\" character varying(255)",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"idempotencyKey\" character varying(64) NOT NULL",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"status\" character varying(16) NOT NULL DEFAULT 'pending'",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"attempts\" integer NOT NULL DEFAULT '0'",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"maxAttempts\" integer NOT NULL DEFAULT '5'",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"scheduledAt\" TIMESTAMP NOT NULL",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"lastError\" text",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"notification_outbox\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"payment_state\" ADD COLUMN IF NOT EXISTS \"accountNumber\" character varying(50) NOT NULL",
  "ALTER TABLE \"payment_state\" ADD COLUMN IF NOT EXISTS \"statementDate\" character varying(10) NOT NULL",
  "ALTER TABLE \"payment_state\" ADD COLUMN IF NOT EXISTS \"lastProcessedPage\" integer NOT NULL DEFAULT '1'",
  "ALTER TABLE \"payment_state\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"payment_state\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(255) NOT NULL",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"outboxId\" uuid NOT NULL",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"recipientSubscriberId\" character varying(255) NOT NULL",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"recipientUsername\" character varying(255)",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"workflowId\" character varying(255) NOT NULL",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"title\" character varying(512) NOT NULL",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"body\" text NOT NULL",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"payload\" json",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"actorSubscriberId\" character varying(255)",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"isRead\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"readAt\" TIMESTAMP",
  "ALTER TABLE \"notification_inbox\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"outboxId\" uuid NOT NULL",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(255) NOT NULL",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"channel\" character varying(32) NOT NULL",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"recipientSubscriberId\" character varying(255) NOT NULL",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"workflowId\" character varying(255) NOT NULL",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"attemptNumber\" integer NOT NULL",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"status\" character varying(16) NOT NULL",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"providerResponse\" text",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"error\" text",
  "ALTER TABLE \"notification_deliveries\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"mutation_logs\" ADD COLUMN IF NOT EXISTS \"_id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"mutation_logs\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(255)",
  "ALTER TABLE \"mutation_logs\" ADD COLUMN IF NOT EXISTS \"mutation_name\" character varying(255) NOT NULL",
  "ALTER TABLE \"mutation_logs\" ADD COLUMN IF NOT EXISTS \"username\" character varying(255) NOT NULL",
  "ALTER TABLE \"mutation_logs\" ADD COLUMN IF NOT EXISTS \"arguments\" jsonb NOT NULL",
  "ALTER TABLE \"mutation_logs\" ADD COLUMN IF NOT EXISTS \"duration_ms\" integer NOT NULL",
  "ALTER TABLE \"mutation_logs\" ADD COLUMN IF NOT EXISTS \"status\" character varying(20) NOT NULL",
  "ALTER TABLE \"mutation_logs\" ADD COLUMN IF NOT EXISTS \"error_message\" text",
  "ALTER TABLE \"mutation_logs\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()",
  "ALTER TABLE \"migrations\" ADD COLUMN IF NOT EXISTS \"version\" character varying NOT NULL",
  "ALTER TABLE \"migrations\" ADD COLUMN IF NOT EXISTS \"name\" character varying NOT NULL",
  "ALTER TABLE \"migrations\" ADD COLUMN IF NOT EXISTS \"executedAt\" TIMESTAMP NOT NULL",
  "ALTER TABLE \"migrations\" ADD COLUMN IF NOT EXISTS \"success\" boolean NOT NULL DEFAULT true",
  "ALTER TABLE \"migrations\" ADD COLUMN IF NOT EXISTS \"logs\" text",
  "ALTER TABLE \"migrations\" ADD COLUMN IF NOT EXISTS \"createdAt\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"migrations\" ADD COLUMN IF NOT EXISTS \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"membership_exit_requests\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"membership_exit_requests\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying NOT NULL",
  "ALTER TABLE \"membership_exit_requests\" ADD COLUMN IF NOT EXISTS \"username\" character varying NOT NULL",
  "ALTER TABLE \"membership_exit_requests\" ADD COLUMN IF NOT EXISTS \"exit_hash\" character varying(64) NOT NULL",
  "ALTER TABLE \"membership_exit_requests\" ADD COLUMN IF NOT EXISTS \"statement\" jsonb NOT NULL",
  "ALTER TABLE \"membership_exit_requests\" ADD COLUMN IF NOT EXISTS \"token\" character varying(1024) NOT NULL",
  "ALTER TABLE \"membership_exit_requests\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"membership_exit_requests\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"meet_processed\" ADD COLUMN IF NOT EXISTS \"hash\" character varying NOT NULL",
  "ALTER TABLE \"meet_processed\" ADD COLUMN IF NOT EXISTS \"coopname\" jsonb NOT NULL",
  "ALTER TABLE \"meet_processed\" ADD COLUMN IF NOT EXISTS \"presider\" character varying NOT NULL",
  "ALTER TABLE \"meet_processed\" ADD COLUMN IF NOT EXISTS \"secretary\" character varying NOT NULL",
  "ALTER TABLE \"meet_processed\" ADD COLUMN IF NOT EXISTS \"results\" jsonb NOT NULL",
  "ALTER TABLE \"meet_processed\" ADD COLUMN IF NOT EXISTS \"signed_ballots\" integer NOT NULL",
  "ALTER TABLE \"meet_processed\" ADD COLUMN IF NOT EXISTS \"quorum_percent\" integer NOT NULL",
  "ALTER TABLE \"meet_processed\" ADD COLUMN IF NOT EXISTS \"quorum_passed\" boolean NOT NULL",
  "ALTER TABLE \"meet_processed\" ADD COLUMN IF NOT EXISTS \"decision\" jsonb NOT NULL",
  "ALTER TABLE \"extensions_logs\" ADD COLUMN IF NOT EXISTS \"id\" SERIAL NOT NULL",
  "ALTER TABLE \"extensions_logs\" ADD COLUMN IF NOT EXISTS \"name\" character varying(12) NOT NULL",
  "ALTER TABLE \"extensions_logs\" ADD COLUMN IF NOT EXISTS \"extension_local_id\" integer NOT NULL DEFAULT '0'",
  "ALTER TABLE \"extensions_logs\" ADD COLUMN IF NOT EXISTS \"data\" jsonb NOT NULL DEFAULT '{}'",
  "ALTER TABLE \"extensions_logs\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"extensions_logs\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"ipn\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"ipn\" ADD COLUMN IF NOT EXISTS \"provider\" character varying(50) NOT NULL",
  "ALTER TABLE \"ipn\" ADD COLUMN IF NOT EXISTS \"data\" jsonb NOT NULL",
  "ALTER TABLE \"ipn\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"ipn\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"blockchain_forks\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"blockchain_forks\" ADD COLUMN IF NOT EXISTS \"chain_id\" character varying NOT NULL",
  "ALTER TABLE \"blockchain_forks\" ADD COLUMN IF NOT EXISTS \"block_num\" bigint NOT NULL",
  "ALTER TABLE \"blockchain_forks\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"ledger_operations\" ADD COLUMN IF NOT EXISTS \"global_sequence\" bigint NOT NULL",
  "ALTER TABLE \"ledger_operations\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(12) NOT NULL",
  "ALTER TABLE \"ledger_operations\" ADD COLUMN IF NOT EXISTS \"action\" character varying(20) NOT NULL",
  "ALTER TABLE \"ledger_operations\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"ledger_operations\" ADD COLUMN IF NOT EXISTS \"account_id\" bigint",
  "ALTER TABLE \"ledger_operations\" ADD COLUMN IF NOT EXISTS \"quantity\" character varying(100)",
  "ALTER TABLE \"ledger_operations\" ADD COLUMN IF NOT EXISTS \"comment\" text",
  "ALTER TABLE \"ledger_operations\" ADD COLUMN IF NOT EXISTS \"hash\" character varying(64)",
  "ALTER TABLE \"ledger_operations\" ADD COLUMN IF NOT EXISTS \"username\" character varying(12)",
  "ALTER TABLE \"extensions\" ADD COLUMN IF NOT EXISTS \"name\" character varying(12) NOT NULL",
  "ALTER TABLE \"extensions\" ADD COLUMN IF NOT EXISTS \"enabled\" boolean NOT NULL DEFAULT true",
  "ALTER TABLE \"extensions\" ADD COLUMN IF NOT EXISTS \"config\" jsonb NOT NULL DEFAULT '{}'",
  "ALTER TABLE \"extensions\" ADD COLUMN IF NOT EXISTS \"schema_version\" integer NOT NULL DEFAULT '1'",
  "ALTER TABLE \"extensions\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"extensions\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"draft_translations\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"draft_translations\" ADD COLUMN IF NOT EXISTS \"draft_id\" bigint NOT NULL",
  "ALTER TABLE \"draft_translations\" ADD COLUMN IF NOT EXISTS \"lang\" character varying(16) NOT NULL",
  "ALTER TABLE \"draft_translations\" ADD COLUMN IF NOT EXISTS \"block_num\" bigint NOT NULL",
  "ALTER TABLE \"draft_translations\" ADD COLUMN IF NOT EXISTS \"value\" jsonb NOT NULL",
  "ALTER TABLE \"draft_translations\" ADD COLUMN IF NOT EXISTS \"present\" boolean NOT NULL DEFAULT true",
  "ALTER TABLE \"draft_translations\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"draft_templates\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"draft_templates\" ADD COLUMN IF NOT EXISTS \"registry_id\" bigint NOT NULL",
  "ALTER TABLE \"draft_templates\" ADD COLUMN IF NOT EXISTS \"block_num\" bigint NOT NULL",
  "ALTER TABLE \"draft_templates\" ADD COLUMN IF NOT EXISTS \"value\" jsonb NOT NULL",
  "ALTER TABLE \"draft_templates\" ADD COLUMN IF NOT EXISTS \"present\" boolean NOT NULL DEFAULT true",
  "ALTER TABLE \"draft_templates\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"chain_id\" character varying NOT NULL",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"block_num\" bigint NOT NULL",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"block_id\" character varying NOT NULL",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"block_time\" TIMESTAMP WITH TIME ZONE",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"present\" boolean NOT NULL",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"code\" character varying NOT NULL",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"scope\" character varying NOT NULL",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"table\" character varying NOT NULL",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"primary_key\" character varying NOT NULL",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"value\" jsonb",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"repeat\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"blockchain_deltas\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"consumer_dedup\" ADD COLUMN IF NOT EXISTS \"event_id\" character varying(512) NOT NULL",
  "ALTER TABLE \"consumer_dedup\" ADD COLUMN IF NOT EXISTS \"applied_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()",
  "ALTER TABLE \"consumer_dedup\" ADD COLUMN IF NOT EXISTS \"block_num\" bigint",
  "ALTER TABLE \"chain_texts\" ADD COLUMN IF NOT EXISTS \"digest\" character varying(64) NOT NULL",
  "ALTER TABLE \"chain_texts\" ADD COLUMN IF NOT EXISTS \"text\" text NOT NULL",
  "ALTER TABLE \"chain_texts\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"username\" character varying NOT NULL",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying NOT NULL",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"braname\" character varying",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"status\" character varying NOT NULL",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"registered_at\" TIMESTAMP",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"type\" character varying NOT NULL",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"statement\" json",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"wallet_agreement\" json",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"signature_agreement\" json",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"privacy_agreement\" json",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"user_agreement\" json",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"blagorost_offer\" json",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"generator_offer\" json",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"program_agreements\" jsonb NOT NULL DEFAULT '{}'",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"intake_answers\" jsonb NOT NULL DEFAULT '{}'",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"program_key\" character varying",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"registration_hash\" character varying NOT NULL",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"referer\" character varying",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"public_key\" character varying NOT NULL",
  "ALTER TABLE \"candidates\" ADD COLUMN IF NOT EXISTS \"meta\" character varying",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"hash\" character varying NOT NULL",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying NOT NULL",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"initiator\" character varying NOT NULL",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"presider\" character varying NOT NULL",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"secretary\" character varying NOT NULL",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"agenda\" jsonb NOT NULL",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"open_at\" TIMESTAMP NOT NULL",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"close_at\" TIMESTAMP NOT NULL",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"proposal\" jsonb",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"details\" text",
  "ALTER TABLE \"meet_pre\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"_id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"block_num\" integer NOT NULL DEFAULT '0'",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"present\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"status\" character varying NOT NULL DEFAULT 'registered'",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"_created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"_updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"id\" integer",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"agreements\"'::regclass AND conname = 'UQ_01532f6c999d44c776e3d1fa4c8') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_01532f6c999d44c776e3d1fa4c8' AND relkind = 'i') THEN ALTER TABLE \"agreements\" ADD CONSTRAINT \"UQ_01532f6c999d44c776e3d1fa4c8\" UNIQUE (\"id\"); END IF; END $$",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"coopname\" character varying(12) NOT NULL",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"username\" character varying(12) NOT NULL",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"type\" character varying(50) NOT NULL",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"program_id\" integer NOT NULL",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"draft_id\" integer NOT NULL",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"version\" integer NOT NULL",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"document\" json NOT NULL",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"blockchain_status\" character varying(20) NOT NULL",
  "ALTER TABLE \"agreements\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"transaction_id\" character varying(64) NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"account\" character varying(16) NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"block_num\" bigint NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"block_id\" character varying(64) NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"block_time\" TIMESTAMP WITH TIME ZONE",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"chain_id\" character varying(64) NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"name\" character varying(16) NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"receiver\" character varying(16) NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"authorization\" jsonb NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"data\" jsonb NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"action_ordinal\" integer NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"global_sequence\" character varying(32) NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"account_ram_deltas\" jsonb NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"console\" text",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"receipt\" jsonb NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"creator_action_ordinal\" integer NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"context_free\" boolean NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"elapsed\" integer NOT NULL",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"repeat\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"blockchain_actions\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"draft_translations\"'::regclass AND conname = 'UQ_b2c91a60be5f9567b9559fcda99') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_b2c91a60be5f9567b9559fcda99' AND relkind = 'i') THEN ALTER TABLE \"draft_translations\" ADD CONSTRAINT \"UQ_b2c91a60be5f9567b9559fcda99\" UNIQUE (\"draft_id\", \"lang\", \"block_num\"); END IF; END $$",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"draft_templates\"'::regclass AND conname = 'UQ_f0293727847fc362617ccd48920') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_f0293727847fc362617ccd48920' AND relkind = 'i') THEN ALTER TABLE \"draft_templates\" ADD CONSTRAINT \"UQ_f0293727847fc362617ccd48920\" UNIQUE (\"registry_id\", \"block_num\"); END IF; END $$",
  "CREATE INDEX IF NOT EXISTS \"idx_entity_versions_block_num\" ON \"entity_versions\" (\"block_num\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_entity_versions_entity_table_id\" ON \"entity_versions\" (\"entity_table\", \"entity_id\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_invalidated_entities_table_id\" ON \"invalidated_entities\" (\"entity_table\", \"entity_id\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_invalidated_entities_fork_event\" ON \"invalidated_entities\" (\"fork_event_id\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_invalidated_entities_block\" ON \"invalidated_entities\" (\"invalidated_by_block\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_invalidated_versions_table_id\" ON \"invalidated_entity_versions\" (\"entity_table\", \"entity_id\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_invalidated_versions_fork_event\" ON \"invalidated_entity_versions\" (\"fork_event_id\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_invalidated_versions_block\" ON \"invalidated_entity_versions\" (\"invalidated_by_block\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_d50bb72d95ea76a5c5e26cc598\" ON \"tracking_rules\" (\"hash\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_92aa70cad0f08382b5ebb87704\" ON \"web_push_subscriptions\" (\"endpoint\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_b118ed464d3c9fafb60054b796\" ON \"web_push_subscriptions\" (\"username\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_d43d178932d7d250c49d75c300\" ON \"vaults\" (\"username\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_97ac0e7e992c6edfe8c09a499f\" ON \"vaults\" (\"username\", \"permission\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_8daea108ae1952da832ed0bb17\" ON \"users\" (\"joined_at\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_ace513fa30d485cfd25c11a9e4\" ON \"users\" (\"role\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_94e2000b5f7ee1f9c491f0f8a8\" ON \"users\" (\"type\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_3676155292d72c67cd4e090514\" ON \"users\" (\"status\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_490ca1761f9f18d457b2dfa65e\" ON \"users\" (\"subscriber_id\") WHERE subscriber_id IS NOT NULL AND subscriber_id != ''",
  "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IDX_490ca1761f9f18d457b2dfa65e' AND indexdef NOT LIKE '% WHERE %') THEN DROP INDEX \"IDX_490ca1761f9f18d457b2dfa65e\"; CREATE UNIQUE INDEX \"IDX_490ca1761f9f18d457b2dfa65e\" ON \"users\" (\"subscriber_id\") WHERE subscriber_id IS NOT NULL AND subscriber_id != ''; END IF; END $$",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_65cbf5fcb331619593ee334c7c\" ON \"users\" (\"email\") WHERE email IS NOT NULL",
  "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IDX_65cbf5fcb331619593ee334c7c' AND indexdef NOT LIKE '% WHERE %') THEN DROP INDEX \"IDX_65cbf5fcb331619593ee334c7c\"; CREATE UNIQUE INDEX \"IDX_65cbf5fcb331619593ee334c7c\" ON \"users\" (\"email\") WHERE email IS NOT NULL; END IF; END $$",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_fe0bb3f6520ee0469504521e71\" ON \"users\" (\"username\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"idx_user_wallets_natural_key\" ON \"user_wallets\" (\"coopname\", \"wallet_name\", \"username\") WHERE \"present\" = true",
  "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_user_wallets_natural_key' AND indexdef NOT LIKE '% WHERE %') THEN DROP INDEX \"idx_user_wallets_natural_key\"; CREATE UNIQUE INDEX \"idx_user_wallets_natural_key\" ON \"user_wallets\" (\"coopname\", \"wallet_name\", \"username\") WHERE \"present\" = true; END IF; END $$",
  "CREATE INDEX IF NOT EXISTS \"idx_user_wallets_wallet_name\" ON \"user_wallets\" (\"wallet_name\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_user_wallets_username\" ON \"user_wallets\" (\"username\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_user_wallets_coopname\" ON \"user_wallets\" (\"coopname\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_user_wallets_blockchain_id\" ON \"user_wallets\" (\"id\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"idx_user_agreements_coopname_username\" ON \"user_agreements\" (\"coopname\", \"username\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_user_agreements_username\" ON \"user_agreements\" (\"username\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_user_agreements_coopname\" ON \"user_agreements\" (\"coopname\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_abb9696b8e001c59b4b241926f\" ON \"tokens\" (\"expires\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_306030d9411d291750fd115857\" ON \"tokens\" (\"user_id\", \"type\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_cd401677a2027dadbfc8a5b36d\" ON \"tokens\" (\"token\", \"type\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_27db409268ca038af56a9ea89e\" ON \"signed_documents\" (\"coopname\", \"username\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_82b968d5d59585db7700d06c01\" ON \"signed_documents\" (\"coopname\", \"status\", \"action\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_ff2ae480e7f33681c7abc15b15\" ON \"signed_documents\" (\"coopname\", \"status\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_dfd7bfc2a17b7e9708079f7a6c\" ON \"signed_documents\" (\"coopname\", \"package\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_0e0774af7892bcb57f7067fcb4\" ON \"signed_documents\" (\"coopname\", \"hash\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_7b9cc3ad5aa4883bf58b2e0cb3\" ON \"signed_documents\" (\"coopname\", \"doc_hash\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_program_wallets_username_program_id\" ON \"program_wallets\" (\"username\", \"program_id\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_program_wallets_program_id\" ON \"program_wallets\" (\"program_id\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_program_wallets_username\" ON \"program_wallets\" (\"username\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_program_wallets_coopname\" ON \"program_wallets\" (\"coopname\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_program_wallets_blockchain_id\" ON \"program_wallets\" (\"id\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_payment_files_payment\" ON \"payment_files\" (\"coopname\", \"payment_hash\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"uq_payment_files_checksum\" ON \"payment_files\" (\"coopname\", \"checksum_sha256\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_94ad46ddcfb45bd1b9c2097927\" ON \"notification_outbox\" (\"coopname\", \"createdAt\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_b8291e6ec9c8a52ef1b90789e0\" ON \"notification_outbox\" (\"idempotencyKey\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_0c8fd09ed7cc98de4788aebfc0\" ON \"notification_outbox\" (\"status\", \"scheduledAt\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_d0670e245f815fce4315c0b6e6\" ON \"notification_inbox\" (\"coopname\", \"createdAt\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_5e0fddfe6e28ae1eb8e1148070\" ON \"notification_inbox\" (\"recipientSubscriberId\", \"isRead\", \"createdAt\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_431f44d4c7fa3abc4efe6cb3f3\" ON \"notification_deliveries\" (\"outboxId\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_75368002d135faf448fb7ebb6f\" ON \"notification_deliveries\" (\"recipientSubscriberId\", \"createdAt\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_79ada82919a29d669bd31e43d2\" ON \"notification_deliveries\" (\"coopname\", \"createdAt\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_beb0db01563a47e1047cff5109\" ON \"mutation_logs\" (\"coopname\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_daf66dbe6d28bed1321162e6e4\" ON \"mutation_logs\" (\"mutation_name\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_bdc743366fe7f6924268558899\" ON \"mutation_logs\" (\"username\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_a511c4bcdf49772b186e509e4a\" ON \"mutation_logs\" (\"status\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_cbde1e8acbfa232d8e56b45c94\" ON \"mutation_logs\" (\"created_at\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_3ad5da7c5901b0822f14f989e1\" ON \"mutation_logs\" (\"status\", \"created_at\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_dbf35170302c988bebb9c45ee4\" ON \"mutation_logs\" (\"coopname\", \"created_at\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_c833b98882905d24631081d73d\" ON \"mutation_logs\" (\"username\", \"created_at\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_670d189dc7743eff0110f76e2f\" ON \"mutation_logs\" (\"mutation_name\", \"created_at\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_6ef0377c2089091429c7b2d7d4\" ON \"membership_exit_requests\" (\"coopname\", \"username\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_33db0590a06fff0d7b3930f580\" ON \"ipn\" (\"provider\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_bd5f8d86ac38f794a29eb66776\" ON \"ipn\" (\"provider\", \"data\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_374a43c2ca1639a4de85298b9e\" ON \"blockchain_forks\" (\"block_num\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_d26846c659c3f3b5547f571569\" ON \"ledger_operations\" (\"coopname\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_7c0ed01027e92617ecf717179a\" ON \"ledger_operations\" (\"hash\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_901a67abcc2c4aef77a94d5291\" ON \"ledger_operations\" (\"username\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_5c8714d0356f2a555de3eb6522\" ON \"ledger_operations\" (\"coopname\", \"account_id\", \"created_at\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_bee9cf4f4f9c03eac53ce458f9\" ON \"ledger_operations\" (\"coopname\", \"created_at\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_b2c91a60be5f9567b9559fcda9\" ON \"draft_translations\" (\"draft_id\", \"lang\", \"block_num\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_f0293727847fc362617ccd4892\" ON \"draft_templates\" (\"registry_id\", \"block_num\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_fb9475960468b1f6064fd2ac22\" ON \"blockchain_deltas\" (\"code\", \"scope\", \"table\", \"primary_key\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_8355383849f8fe945374ec03f8\" ON \"blockchain_deltas\" (\"primary_key\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_1cc7a5943291992f28873fce8b\" ON \"blockchain_deltas\" (\"block_num\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_38cc571fec7889bb40d63b3d4e\" ON \"blockchain_deltas\" (\"code\", \"table\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_consumer_dedup_applied_at\" ON \"consumer_dedup\" (\"applied_at\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_consumer_dedup_block_num\" ON \"consumer_dedup\" (\"block_num\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_agreements_blockchain_status\" ON \"agreements\" (\"blockchain_status\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_agreements_status\" ON \"agreements\" (\"status\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_agreements_program_id\" ON \"agreements\" (\"program_id\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_agreements_type\" ON \"agreements\" (\"type\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_agreements_username\" ON \"agreements\" (\"username\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_agreements_coopname\" ON \"agreements\" (\"coopname\") ",
  "CREATE INDEX IF NOT EXISTS \"idx_agreements_id\" ON \"agreements\" (\"id\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_500f35ace6109bd812b77e0ec9\" ON \"blockchain_actions\" (\"global_sequence\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_d95b6d9483cc0e342c496dd0a8\" ON \"blockchain_actions\" (\"block_num\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_36b4efbc9c231c0dec7a1ea5e6\" ON \"blockchain_actions\" (\"account\", \"name\") ",
];

export class CoreBaseline1790197276751 implements MigrationInterface {
  name = 'CoreBaseline1790197276751';

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {
    throw new Error('CoreBaseline1790197276751 не откатывается: удаление таблиц стартовой миграции стёрло бы данные');
  }
}
