export { api as contentRevisionsApi } from './api'
export type { IContentEntityType, IContentRevision, IContentRevisionSummary } from './api'
export { extractContentConflict, type IContentConflict } from './lib/conflict'
export { unifiedLineDiff } from './lib/lineDiff'
export { useUnsavedGuard } from './model/useUnsavedGuard'
export { default as EditorSaveBar } from './ui/EditorSaveBar.vue'
export { default as RevisionsDialog } from './ui/RevisionsDialog.vue'
export { default as ConflictDialog } from './ui/ConflictDialog.vue'
export { default as RevisionsButton } from './ui/RevisionsButton.vue'
