/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MarketplaceKuDetailsGeocodeStatusEnum = "FAILED" | "OK" | "PENDING";

export type MarketplaceKuDetailsStatusEnum = "ACTIVE" | "INACTIVE";

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AvailableCategories {
  added_by: string;
  category_id: number;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_active: Generated<boolean>;
  type_id: number | null;
  updated_at: Generated<Timestamp>;
}

export interface Categories {
  category_name: string;
  created_at: Generated<Timestamp>;
  description_category_id: number;
  disabled: Generated<boolean>;
  parent_id: number | null;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceAplReception {
  braname: string;
  chairman_account: string | null;
  chairman_signchair_tx_hash: string | null;
  chairman_signed_at: Timestamp | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  created_by_operator_account: string;
  cycle_id: string;
  expeditor_data: Json | null;
  fact_quantity_per_order: Json;
  id: Generated<string>;
  offerer_account: string;
  shipment_id: string;
  status: string;
  supplier_signed_at: Timestamp | null;
  supplier_signed_documents: Json | null;
  supplier_signsupp_tx_hash: string | null;
  total_amount: Numeric;
  ttn_number: string | null;
  updated_at: Generated<Timestamp>;
  variant: string;
}

export interface MarketplaceCart {
  coopname: string;
  created_at: Generated<Timestamp>;
  delivery_braname: string | null;
  id: Generated<string>;
  orderer_account: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceCartItem {
  cart_id: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  offer_id: string;
  package_id: Generated<string>;
  quantity: Numeric;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceCategory {
  coopname: string | null;
  display_name: string;
  id: number;
  mvp_baseline: Generated<boolean>;
  sort_order: number;
}

export interface MarketplaceConsolidatedRequest {
  accepted_at: Timestamp | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  cycle_ended_at: Timestamp | null;
  cycle_started_at: Timestamp;
  decline_reason: string | null;
  declined_at: Timestamp | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  offer_id: string;
  status: string;
  supplier_account: string;
  total_amount: Numeric;
  total_quantity: number;
  triggered_by_supplier_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceContainer {
  braname: string;
  cell_id: string | null;
  code: string;
  container_type_id: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  label: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceContainerType {
  coopname: string;
  created_at: Generated<Timestamp>;
  height_cm: Generated<number>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  length_cm: Generated<number>;
  max_weight_kg: Numeric | null;
  name: string;
  updated_at: Generated<Timestamp>;
  volume_m3: Generated<Numeric>;
  width_cm: Generated<number>;
}

export interface MarketplaceInventory {
  arrival_price: Numeric | null;
  barcode_format: string | null;
  barcode_value: string | null;
  braname: string;
  cell_id: string | null;
  container_id: string | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  expiry_date: Timestamp | null;
  id: Generated<string>;
  labeled_at: Timestamp | null;
  labeled_by_operator_account: string | null;
  order_id: string;
  orderer_account_snapshot: string;
  origin: Generated<string>;
  ownership: Generated<string>;
  package_size: Generated<Numeric>;
  product_name_snapshot: string;
  published_offer_id: string | null;
  quantity_per_label: number;
  received_at: Timestamp | null;
  received_by_operator_account: string | null;
  reserved_order_id: string | null;
  return_claim_id: string | null;
  shelf: string | null;
  shipment_id: string;
  status: string;
  unit_of_measure: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceIssuanceSaga {
  act_document_hash: string | null;
  act1_document: Json | null;
  act2_document: Json | null;
  attempts: Generated<number>;
  braname: string;
  closed_at: Timestamp | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decision_id: string | null;
  decision_mode: Generated<string>;
  fact: Json;
  id: Generated<string>;
  last_error: string | null;
  member_account: string;
  operator_account: string;
  order_hash: string;
  order_id: string;
  proposal_id: string | null;
  protocol_document: Json | null;
  stage: string;
  statement_document: Json | null;
  tx_hashes: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceKuDetails {
  coopname: string;
  /**
   * braname в core coop_ku
   */
  core_braname: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  geocode_error_message: string | null;
  geocode_status: Generated<MarketplaceKuDetailsGeocodeStatusEnum>;
  /**
   * Адрес, по которому посчитаны координаты (кэш-ключ геокода)
   */
  geocoded_address: string | null;
  geocoded_at: Timestamp | null;
  id: Generated<number>;
  lat: number | null;
  lng: number | null;
  status: Generated<MarketplaceKuDetailsStatusEnum>;
  updated_at: Generated<Timestamp>;
  working_hours_json: Json;
}

export interface MarketplaceModerationLog {
  action: string;
  by_account: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  offer_id: string;
  reason: string | null;
}

export interface MarketplaceOffer {
  approved_at: Timestamp | null;
  approved_by: string | null;
  barcode_strategy: Generated<string>;
  category_id: number;
  coopname: string;
  created_at: Generated<Timestamp>;
  delivery_points: Generated<Json>;
  description: string | null;
  id: Generated<string>;
  images: Generated<Json>;
  pack_size: number | null;
  packages: Generated<Json>;
  price_per_unit: Numeric;
  product_name: string;
  quantity_available: Generated<Numeric>;
  quantity_blocked: Generated<Numeric>;
  quantity_consumed: Generated<Numeric>;
  reject_reason: string | null;
  rejected_at: Timestamp | null;
  rejected_by: string | null;
  sale_form: Generated<string>;
  shelf_life_days: Generated<number>;
  status: string;
  stock_braname: string | null;
  stock_origin_offer_id: string | null;
  supplier_account: string;
  unit_of_measure: string;
  unlimited_flag: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  vitrine_id: string;
  warranty_days: Generated<number>;
}

export interface MarketplaceOrder {
  accepted_at: Timestamp | null;
  accepted_cost: Numeric | null;
  blocked_at: Timestamp | null;
  cancelled_at: Timestamp | null;
  checkout_id: string | null;
  coopname: string;
  create_tx: Json | null;
  created_at: Generated<Timestamp>;
  current_warehouse_braname: string | null;
  cycle_id: string | null;
  delivery_braname: string;
  delivery_signer_account: string | null;
  id: Generated<string>;
  issuance_fact: Json | null;
  issue_closed_tx_hash: string | null;
  issue_decision_id: string | null;
  issue_statement_at: Timestamp | null;
  last_status_reason: string | null;
  markdown_cost: Numeric | null;
  markdown_due: Numeric | null;
  membership_fee: Numeric | null;
  offer_hash: string;
  offer_id: string;
  on_chain_block_num: Int8 | null;
  on_chain_id: string | null;
  on_chain_present: Generated<boolean>;
  order_hash: string;
  orderer_account: string;
  package_id: string | null;
  package_size: Generated<Numeric>;
  payout_status: string | null;
  price_per_unit: Numeric;
  quantity: Numeric;
  ready_announced_at: Timestamp | null;
  received_at: Timestamp | null;
  shipment_id: string | null;
  status: string;
  supplier_account: string;
  total_cost: Numeric;
  unit_of_measure: Generated<string>;
  updated_at: Generated<Timestamp>;
  warranty_period_secs: number;
  warranty_until: Timestamp | null;
}

export interface MarketplaceOutgoingPaymentRequest {
  amount: Numeric;
  apl_reception_id: string;
  completed_at: Timestamp | null;
  coopname: string;
  core_payment_id: string | null;
  created_at: Generated<Timestamp>;
  decline_reason: string | null;
  id: Generated<string>;
  order_hash: string;
  order_id: string;
  payee_account: string;
  payout_destination: string | null;
  payout_tx_hash: string | null;
  purpose: string;
  status: string;
  symbol: string;
  updated_at: Generated<Timestamp>;
  withheld_amount: Generated<Numeric>;
}

export interface MarketplaceReturnClaim {
  accepted_at: Timestamp | null;
  actual_quantity: number;
  cancel_statement: Json | null;
  coopname: string;
  council_decision_id: string | null;
  council_decision_mode: string | null;
  council_protocol: Json | null;
  created_at: Generated<Timestamp>;
  decision_log: Generated<Json>;
  defect_category: string | null;
  delivery_braname: string;
  expected_resolution: string;
  fact_cost: Numeric;
  fee_refund: Generated<Numeric>;
  fee_refund_pending_at: Timestamp | null;
  id: Generated<string>;
  ledger_snapshot: Json | null;
  on_site_inspection: Json | null;
  order_hash: string;
  order_id: string;
  orderer_account: string;
  photos: Json;
  reason_text: string;
  request_hash: string;
  statement: Json | null;
  status: string;
  submretrn_tx_hash: string;
  supplier_account: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceReview {
  author_account: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  hidden_at: Timestamp | null;
  hidden_by: string | null;
  hidden_reason: string | null;
  id: Generated<string>;
  offer_id: string;
  order_id: string;
  stars: number;
  status: Generated<string>;
  supplier_account: string;
  text: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceShipment {
  braname: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  cycle_id: string;
  delivery_variant: string;
  id: Generated<string>;
  offerer_account: string;
  status: string;
  total_amount: Numeric;
  ttn_data: Json | null;
  ttn_document_id: string | null;
  ttn_number: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceStockProposal {
  braname: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  created_order_ids: Generated<Json>;
  id: Generated<string>;
  items: Generated<Json>;
  member_account: string;
  operator_account: string;
  resolved_at: Timestamp | null;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceStorageCell {
  braname: string;
  code: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  label: string | null;
  level: number;
  section: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceSupplier {
  contract_date: Timestamp | null;
  contract_document_url: string | null;
  contract_number: string | null;
  coopname: string;
  id: Generated<string>;
  member_account: string;
  model: string;
  requested_at: Generated<Timestamp>;
  requested_by: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  status: string;
}

export interface MarketplaceSupplierClaim {
  actual_quantity: number;
  amount: Numeric;
  claim_hash: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  decide_tx_hash: string | null;
  decided_at: Timestamp | null;
  delivery_braname: string;
  id: Generated<string>;
  inspection_result: Generated<string>;
  issue_tx_hash: Generated<string>;
  issued_at: Timestamp;
  order_hash: string;
  order_id: string;
  orderer_account: string;
  photos: Generated<Json>;
  reason_text: string;
  reclamation: Json | null;
  return_claim_id: string;
  status: string;
  supplier_account: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceSupplierProfile {
  about: Generated<string>;
  coopname: string;
  cover: Json | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  id: Generated<string>;
  supplier_account: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceSupplierSettings {
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  payout_method_id: string | null;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface MarketplaceSupplyValidationLog {
  attempted_groups: Json;
  coopname: string;
  created_at: Generated<Timestamp>;
  cycle_id: string;
  id: Generated<string>;
  offerer_account: string;
  outcome: string;
  reason: string | null;
  reason_code: string | null;
}

export interface MarketplaceTtnDocument {
  accept_braname: string;
  content_html: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  currency: string;
  document_hash: string;
  id: Generated<string>;
  meta: Json;
  registry_id: number;
  shipment_id: string;
  supplier_account: string;
  total_amount: Numeric;
  ttn_data: Json;
  ttn_number: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceVitrine {
  coopname: string;
  created_at: Generated<Timestamp>;
  display_name: string;
  id: string;
  is_default: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceWriteoffProposal {
  authorized_at: Timestamp | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  cycle_started_at: Timestamp;
  decided_by_account: string | null;
  decision_id: Int8 | null;
  decision_log: Generated<Json>;
  executed_at: Timestamp | null;
  id: Generated<string>;
  items: Json;
  proposal_hash: Generated<string>;
  proposed_by_account: string | null;
  protocol_doc: Json | null;
  reject_reason: string | null;
  rejected_at: Timestamp | null;
  statement_doc: Json | null;
  status: string;
  submitted_at: Timestamp | null;
  total_amount: string;
  trigger: string;
  updated_at: Generated<Timestamp>;
}

export interface Types {
  created_at: Generated<Timestamp>;
  description_category_id: number;
  disabled: Generated<boolean>;
  type_id: number;
  type_name: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  available_categories: AvailableCategories;
  categories: Categories;
  marketplace_apl_reception: MarketplaceAplReception;
  marketplace_cart: MarketplaceCart;
  marketplace_cart_item: MarketplaceCartItem;
  marketplace_category: MarketplaceCategory;
  marketplace_consolidated_request: MarketplaceConsolidatedRequest;
  marketplace_container: MarketplaceContainer;
  marketplace_container_type: MarketplaceContainerType;
  marketplace_inventory: MarketplaceInventory;
  marketplace_issuance_saga: MarketplaceIssuanceSaga;
  marketplace_ku_details: MarketplaceKuDetails;
  marketplace_moderation_log: MarketplaceModerationLog;
  marketplace_offer: MarketplaceOffer;
  marketplace_order: MarketplaceOrder;
  marketplace_outgoing_payment_request: MarketplaceOutgoingPaymentRequest;
  marketplace_return_claim: MarketplaceReturnClaim;
  marketplace_review: MarketplaceReview;
  marketplace_shipment: MarketplaceShipment;
  marketplace_stock_proposal: MarketplaceStockProposal;
  marketplace_storage_cell: MarketplaceStorageCell;
  marketplace_supplier: MarketplaceSupplier;
  marketplace_supplier_claim: MarketplaceSupplierClaim;
  marketplace_supplier_profile: MarketplaceSupplierProfile;
  marketplace_supplier_settings: MarketplaceSupplierSettings;
  marketplace_supply_validation_log: MarketplaceSupplyValidationLog;
  marketplace_ttn_document: MarketplaceTtnDocument;
  marketplace_vitrine: MarketplaceVitrine;
  marketplace_writeoff_proposal: MarketplaceWriteoffProposal;
  types: Types;
}
