// AUTO-GENERATED by cooptypes/scripts/gen-from-cpp.ts — DO NOT EDIT.
// Source: contracts/cpp/lib/core/ledger2/wallets.hpp
// Run `pnpm --filter cooptypes gen:from-cpp` to regenerate.

import type { IName } from '../interfaces/ledger2'

export type WalletKind = 'USER_SHARED' | 'COOPERATIVE'

export interface WalletMeta {
  /** Машинный идентификатор — eosio::name в контракте. */
  name: IName
  /** Человекочитаемое название для UI. */
  human_name: string
  /** Тип кошелька: USER_SHARED — L3-разрез по пайщику; COOPERATIVE — единый баланс. */
  kind: WalletKind
}

/**
 * Реестр кошельков ledger2 — точная копия `LEDGER2_WALLET_REGISTRY` из C++.
 */
export const LEDGER2_WALLET_REGISTRY: readonly WalletMeta[] = [
  { name: "w.reg.minshr", human_name: "Минимальный паевой взнос", kind: "USER_SHARED" },
  { name: "w.wal.share", human_name: "Паевой взнос пайщика", kind: "USER_SHARED" },
  { name: "w.wal.member", human_name: "ЦК — членская часть пайщика", kind: "USER_SHARED" },
  { name: "w.cap.blago", human_name: "ЦПП «Благорост» — единый кошелёк программы у пайщика", kind: "USER_SHARED" },
  { name: "w.cap.preimp", human_name: "Первичный учёт РИД-взносов до перехода на электронный учёт", kind: "USER_SHARED" },
  { name: "w.mkt.order", human_name: "ЦПП «Стол Заказов» — паевой резерв под заказ у пайщика", kind: "USER_SHARED" },
  { name: "w.mkt.share", human_name: "ЦПП «Стол Заказов» — свободный паевой пайщика в программе", kind: "USER_SHARED" },
  { name: "w.mkt.member", human_name: "ЦПП «Стол Заказов» — членский взнос пайщика в программе", kind: "USER_SHARED" },
  { name: "w.mkt.claim", human_name: "ЦПП «Стол Заказов» — непризнанные гарантийные претензии поставщику", kind: "USER_SHARED" },
  { name: "w.mkt.debt", human_name: "ЦПП «Стол Заказов» — признанный гарантийный долг поставщика к удержанию", kind: "USER_SHARED" },
  { name: "w.mkt.topay", human_name: "ЦПП «Стол Заказов» — к оплате поставщику за принятое имущество", kind: "USER_SHARED" },
  { name: "w.brn.person", human_name: "Персональный кошелёк доверенного кооперативного участка", kind: "USER_SHARED" },
  { name: "w.brn.common", human_name: "Общий кошелёк членских взносов кооперативного участка", kind: "USER_SHARED" },
  { name: "w.exp.adv", human_name: "Подотчётные средства пайщика", kind: "USER_SHARED" },
  { name: "w.reg.pend", human_name: "Регистрационный взнос в ожидании решения совета", kind: "USER_SHARED" },
  { name: "w.edu.expns", human_name: "Пул расходов ЦПП «Образование»", kind: "COOPERATIVE" },
  { name: "w.edu.fund", human_name: "Фонд ЦПП «Образование»", kind: "COOPERATIVE" },
  { name: "w.edu.escrow", human_name: "Взносы ЦПП «Образование», удержанные до конца гарантийного срока", kind: "COOPERATIVE" },
  { name: "w.edu.teach", human_name: "Резерв выплат преподавателям ЦПП «Образование»", kind: "COOPERATIVE" },
  { name: "w.edu.member", human_name: "ЦПП «Образование» — членский взнос пайщика за доступ к курсу", kind: "USER_SHARED" },
  { name: "w.edu.hold", human_name: "ЦПП «Образование» — материалы преподавателя на ответственном хранении", kind: "USER_SHARED" },
  { name: "w.cap.gen", human_name: "ЦПП «Генератор» — единый кошелёк программы", kind: "COOPERATIVE" },
  { name: "w.reg.entry", human_name: "Вступительные взносы", kind: "COOPERATIVE" },
  { name: "w.wal.wthdrw", human_name: "Возвраты паевых взносов пайщикам (deprecated, не используется в новых операциях)", kind: "COOPERATIVE" },
  { name: "w.wal.wpend", human_name: "Резерв паевого под заявку на возврат", kind: "COOPERATIVE" },
  { name: "w.sov.infra", human_name: "Членские взносы за инфраструктуру кооп. платформы", kind: "COOPERATIVE" },
  { name: "w.sov.delgte", human_name: "Делегатские членские взносы", kind: "COOPERATIVE" },
  { name: "w.sov.expns", human_name: "Хозяйственные расходы из числа целевого финансирования", kind: "COOPERATIVE" },
  { name: "w.sov.mnused", human_name: "Использованные минимальные паевые взносы", kind: "COOPERATIVE" },
  { name: "w.cap.loan", human_name: "Выданные пайщикам беспроцентные займы", kind: "COOPERATIVE" },
  { name: "w.mkt.payout", human_name: "Выплаты поставщикам", kind: "COOPERATIVE" },
  { name: "w.mkt.fee", human_name: "Резерв членских взносов «Стола заказов» под заказы", kind: "COOPERATIVE" },
  { name: "w.brn.pool", human_name: "Транзитный пул ручного распределения кооперативного участка", kind: "COOPERATIVE" },
  { name: "w.brn.expns", human_name: "Пул расходов кооперативного участка", kind: "COOPERATIVE" },
  { name: "w.cap.pgexp", human_name: "Пул программных расходов ЦПП «Благорост»", kind: "COOPERATIVE" },
  { name: "w.sov.ndfl", human_name: "Удержанный НДФЛ к перечислению", kind: "COOPERATIVE" },
] as const

export interface ProgramWalletMapping {
  /** Машинный идентификатор кошелька. */
  wallet_name: IName
  /** Требуемый program_id для cross-contract проверки в `wallet::users.programs[]`; 0 — без проверки. */
  required_program_id: number
  /** Человекочитаемая метка программы из inline-комментария hpp; null для program_id == 0. */
  program_label: string | null
}

/**
 * Маппинг USER_SHARED-кошелька → program_id (`LEDGER2_USER_SHARED_PROGRAM_MAPPING`).
 * N→1: один program_id может ссылаться на несколько wallet_name (ЦК = share + member).
 */
export const LEDGER2_USER_SHARED_PROGRAM_MAPPING: readonly ProgramWalletMapping[] = [
  { wallet_name: "w.reg.minshr", required_program_id: 0, program_label: null },
  { wallet_name: "w.wal.share", required_program_id: 1, program_label: "ЦК" },
  { wallet_name: "w.wal.member", required_program_id: 1, program_label: "ЦК" },
  { wallet_name: "w.cap.blago", required_program_id: 4, program_label: "Благорост" },
  { wallet_name: "w.cap.gen", required_program_id: 3, program_label: "Генератор" },
  { wallet_name: "w.cap.preimp", required_program_id: 0, program_label: null },
  { wallet_name: "w.mkt.order", required_program_id: 2, program_label: "Marketplace" },
  { wallet_name: "w.mkt.share", required_program_id: 2, program_label: "Marketplace" },
  { wallet_name: "w.mkt.member", required_program_id: 2, program_label: "Marketplace" },
  { wallet_name: "w.mkt.claim", required_program_id: 0, program_label: null },
  { wallet_name: "w.mkt.debt", required_program_id: 0, program_label: null },
  { wallet_name: "w.mkt.topay", required_program_id: 0, program_label: null },
  { wallet_name: "w.brn.person", required_program_id: 0, program_label: null },
  { wallet_name: "w.brn.common", required_program_id: 0, program_label: null },
  { wallet_name: "w.exp.adv", required_program_id: 0, program_label: null },
  { wallet_name: "w.reg.pend", required_program_id: 0, program_label: null },
  { wallet_name: "w.edu.member", required_program_id: 5, program_label: "Образование" },
  { wallet_name: "w.edu.hold", required_program_id: 6, program_label: "Образование-преподавание" },
] as const

/** Что выход из кооператива делает с кошельком пайщика. */
export type ExitWalletPolicy = 'MAIN' | 'RETURN_TO_MAIN' | 'FORFEIT' | 'BLOCKER' | 'UNTOUCHED'

export interface ExitWalletRule {
  /** Машинный идентификатор кошелька. */
  wallet_name: IName
  /** MAIN — главный паевой, цель сбора; RETURN_TO_MAIN — возвращается пайщику; FORFEIT — остаётся кооперативу; BLOCKER — ненулевой остаток держит выход; UNTOUCHED — выход не трогает. */
  policy: ExitWalletPolicy
  /** Операция переноса на главный паевой; null у всех политик, кроме RETURN_TO_MAIN. */
  transfer_op: IName | null
  /** Для BLOCKER — причина отказа пайщику; для остальных — пояснение к решению. */
  note: string
}

/**
 * Что выход делает с каждым кошельком пайщика — точная копия `EXIT_WALLET_POLICY`
 * из C++ (lib/core/ledger2/exit_policy.hpp). Контракт `confirmexit` обходит эту
 * таблицу, собирает доступные балансы возвращаемых кошельков и ставит их на
 * возврат; предрасчёт на столе считает по ней же — суммы совпадают.
 */
export const LEDGER2_EXIT_WALLET_POLICY: readonly ExitWalletRule[] = [
  { wallet_name: "w.wal.share", policy: "MAIN", transfer_op: null, note: "Главный паевой взнос — на него собирается возврат" },
  { wallet_name: "w.reg.minshr", policy: "RETURN_TO_MAIN", transfer_op: "o.reg.mvmin", note: "Минимальный паевой взнос" },
  { wallet_name: "w.cap.blago", policy: "RETURN_TO_MAIN", transfer_op: "o.cap.wthcap", note: "Паевой взнос ЦПП «Благорост»" },
  { wallet_name: "w.mkt.share", policy: "RETURN_TO_MAIN", transfer_op: "o.mkt.recall", note: "Свободный паевой взнос ЦПП «Стол заказов»" },
  { wallet_name: "w.edu.member", policy: "RETURN_TO_MAIN", transfer_op: "o.edu.retshr", note: "Членский взнос ЦПП «Образование» (п. 4.2.5 Положения)" },
  { wallet_name: "w.mkt.member", policy: "FORFEIT", transfer_op: null, note: "Членский взнос ЦПП «Стол заказов» — Положение возврата не предусматривает" },
  { wallet_name: "w.mkt.order", policy: "BLOCKER", transfer_op: null, note: "под заказы Стола заказов зарезервирован паевой взнос — завершите или отмените заказы" },
  { wallet_name: "w.exp.adv", policy: "BLOCKER", transfer_op: null, note: "не закрыт подотчёт по служебной записке — отчитайтесь или верните аванс" },
  { wallet_name: "w.edu.hold", policy: "BLOCKER", transfer_op: null, note: "идёт гарантийный срок по переданным материалам занятий — дождитесь его окончания" },
  { wallet_name: "w.wal.member", policy: "UNTOUCHED", transfer_op: null, note: "Членская часть Цифрового кошелька — политика выхода не определена" },
  { wallet_name: "w.cap.preimp", policy: "UNTOUCHED", transfer_op: null, note: "Пред-импорт РИД — учётный кошелёк, не средства пайщика" },
  { wallet_name: "w.mkt.claim", policy: "UNTOUCHED", transfer_op: null, note: "Требование к контрагенту по договору поставки, а не участие пайщика" },
  { wallet_name: "w.mkt.debt", policy: "UNTOUCHED", transfer_op: null, note: "Задолженность поставщика по договору поставки" },
  { wallet_name: "w.mkt.topay", policy: "UNTOUCHED", transfer_op: null, note: "Обязательство кооператива перед поставщиком" },
  { wallet_name: "w.brn.person", policy: "UNTOUCHED", transfer_op: null, note: "Распределение кооперативного участка — назначает председатель участка" },
  { wallet_name: "w.brn.common", policy: "UNTOUCHED", transfer_op: null, note: "Общий кошелёк участка: L3-разрез по участку, а не по пайщику" },
  { wallet_name: "w.reg.pend", policy: "UNTOUCHED", transfer_op: null, note: "Взнос кандидата до вступления — выходить ещё неоткуда" },
] as const

/**
 * Кошельки, остатки которых возвращаются пайщику при выходе, — выведено из
 * таблицы политики (MAIN + RETURN_TO_MAIN).
 */
export const LEDGER2_EXIT_REFUND_WALLETS: readonly IName[] = [
  "w.wal.share",
  "w.reg.minshr",
  "w.cap.blago",
  "w.mkt.share",
  "w.edu.member",
] as const
