/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CapitalFavoritesTargetTypeEnum = "ARTIFACT" | "COMPONENT" | "ISSUE" | "PROJECT";

export type CapitalIssuesPriorityEnum = "high" | "low" | "medium" | "urgent";

export type CapitalMeasuresSeriesModeEnum = "level" | "rate";

export type CapitalMetricContributionsSourceEnum = "issue_done" | "issue_reopen" | "manual";

export type CapitalProcessInstancesStatusEnum = "cancelled" | "completed" | "running";

export type CapitalProcessTemplatesStatusEnum = "active" | "archived" | "draft";

export type CapitalProjectOrigin = "blockchain" | "local";

export type CapitalProjectPriority = "high" | "low" | "medium" | "urgent";

export type CapitalStoriesContentFormatEnum = "BPMN" | "DRAWIO" | "MARKDOWN" | "MERMAID";

export type ChatcoopCallTranscriptionsStatusEnum = "active" | "completed" | "failed";

export type EdubridgeAccessTasksCarrierEnum = "getcourse" | "onsite" | "skillspace" | "telegram" | "vk";

export type EdubridgeAccessTasksKindEnum = "grant" | "revoke";

export type EdubridgeAccessTasksStatusEnum = "done" | "failed" | "needs_attention" | "pending" | "running";

export type EdubridgeConnectorBindingsCarrierEnum = "getcourse" | "onsite" | "skillspace" | "telegram" | "vk";

export type EdubridgeConnectorBindingsHealthEnum = "failing" | "license_limit" | "ok" | "unknown";

export type EdubridgeContributionsCouncilOutcomeEnum = "declined" | "expired";

export type EdubridgeContributionsRidTypeEnum = "assessment_material" | "course_program" | "lesson_recording" | "methodical_material" | "other";

export type EdubridgeContributionsStatusEnum = "accepted" | "act_signed" | "council_approved" | "declined" | "draft" | "held" | "submitted";

export type EdubridgeCoursesCarrierEnum = "getcourse" | "onsite" | "skillspace" | "telegram" | "vk";

export type EdubridgeCoursesDirectionEnum = "closed_community" | "online_platform" | "onsite";

export type EdubridgeCoursesStatusEnum = "archived" | "draft" | "published";

export type EdubridgeEnrollmentsAccessStateEnum = "granted" | "needs_attention" | "none" | "pending" | "revoked";

export type EdubridgeEnrollmentsPeriodEnum = "course" | "month" | "year";

export type EdubridgeEnrollmentsStatusEnum = "active" | "cancelled" | "expired" | "pending" | "revoked";

export type EdubridgeLearnersRecipientTypeEnum = "email" | "onsite" | "telegram";

export type EdubridgeReturnRequestsStatusEnum = "approved" | "declined" | "pending";

export type EdubridgeTeacherAssignmentsStatusEnum = "active" | "closed";

export type EdubridgeTeacherContractsStatusEnum = "active" | "declined" | "pending_approval" | "terminated";

export type ExpenseFilesKindEnum = "CLOSING_DOC" | "PAYMENT_PROOF" | "REPORT_FILE" | "RETURN_PROOF";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MarketplaceKuDetailsGeocodeStatusEnum = "FAILED" | "OK" | "PENDING";

export type MarketplaceKuDetailsStatusEnum = "ACTIVE" | "INACTIVE";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaymentFilesKindEnum = "PAYMENT_PROOF";

export type PaymentsDirectionEnum = "incoming" | "outgoing";

export type PaymentsStatusEnum = "awaiting_authorization" | "cancelled" | "completed" | "expired" | "failed" | "paid" | "pending" | "processing" | "refunded";

export type PaymentsTypeEnum = "aid" | "deposit" | "expense" | "expense_overspend" | "expense_return" | "membership_exit" | "payment" | "registration" | "registration_refund" | "tax" | "withdrawal";

export type SystemStatusStatusEnum = "active" | "initialized" | "install" | "maintenance";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Agreements {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  blockchain_status: string;
  coopname: string;
  document: Json;
  draft_id: number;
  id: number | null;
  present: Generated<boolean>;
  program_id: number;
  status: Generated<string>;
  type: string;
  updated_at: Timestamp;
  username: string;
  version: number;
}

export interface AvailableCategories {
  added_by: string;
  category_id: number;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_active: Generated<boolean>;
  type_id: number | null;
  updated_at: Generated<Timestamp>;
}

export interface BalanceCorrections {
  account_display_id: string;
  balance_pre_previous: Generated<Numeric>;
  balance_previous: Generated<Numeric>;
  coopname: string;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  year: number;
}

export interface BlockchainActions {
  account: string;
  account_ram_deltas: Json;
  action_ordinal: number;
  authorization: Json;
  block_id: string;
  block_num: Int8;
  block_time: Timestamp | null;
  chain_id: string;
  console: string | null;
  context_free: boolean;
  created_at: Generated<Timestamp>;
  creator_action_ordinal: number;
  data: Json;
  elapsed: number;
  global_sequence: string;
  id: Generated<string>;
  name: string;
  receipt: Json;
  receiver: string;
  repeat: Generated<boolean>;
  transaction_id: string;
}

export interface BlockchainDeltas {
  block_id: string;
  block_num: Int8;
  block_time: Timestamp | null;
  chain_id: string;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  present: boolean;
  primary_key: string;
  repeat: Generated<boolean>;
  scope: string;
  table: string;
  value: Json | null;
}

export interface BlockchainForks {
  block_num: Int8;
  chain_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
}

export interface BlockchainSyncState {
  block_num: Int8;
  key: string;
  updated_at: Generated<Timestamp>;
}

export interface Candidates {
  blagorost_offer: Json | null;
  braname: string | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  generator_offer: Json | null;
  intake_answers: Generated<Json>;
  meta: string | null;
  privacy_agreement: Json | null;
  program_agreements: Generated<Json>;
  program_key: string | null;
  public_key: string;
  referer: string | null;
  registered_at: Timestamp | null;
  registration_hash: string;
  signature_agreement: Json | null;
  statement: Json | null;
  status: string;
  type: string;
  user_agreement: Json | null;
  username: string;
  wallet_agreement: Json | null;
}

export interface CapitalAppendixes {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  appendix: Json | null;
  appendix_hash: string;
  block_num: Generated<number>;
  blockchain_status: string | null;
  contribution: string | null;
  coopname: string | null;
  created_at: Timestamp | null;
  id: number | null;
  present: Generated<boolean>;
  project_hash: string | null;
  status: Generated<string>;
  username: string | null;
}

export interface CapitalComments {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  commentor_id: string;
  content: string;
  edited_at: Timestamp | null;
  issue_id: string;
  present: Generated<boolean>;
  reactions: Generated<Json>;
  status: Generated<string>;
}

export interface CapitalCommits {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  amounts: Json | null;
  block_num: Generated<number>;
  blockchain_status: string | null;
  commit_hash: string;
  coopname: string | null;
  created_at: Timestamp | null;
  data: Json | null;
  description: string | null;
  id: number | null;
  meta: string | null;
  present: Generated<boolean>;
  project_hash: string | null;
  status: Generated<string>;
  username: string | null;
}

export interface CapitalComponentMetrics {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  coopname: string;
  created_by: string;
  deadline: Timestamp | null;
  measure_hash: string;
  metric_hash: string;
  present: Generated<boolean>;
  project_hash: string;
  status: Generated<string>;
  target_value: Generated<number>;
}

export interface CapitalContentRevisions {
  _id: Generated<string>;
  author: string;
  base_rev: number | null;
  content_format: string | null;
  content_hash: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  entity_hash: string;
  entity_type: string;
  merged: Generated<boolean>;
  origin: string;
  restored_from_rev: number | null;
  rev: number;
  title: string;
}

export interface CapitalContributors {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  about: string | null;
  appendixes: Json | null;
  blagorost_agreement_hash: string | null;
  blagorost_offer_hash: string | null;
  block_num: Generated<number>;
  blockchain_status: string | null;
  contract: Json | null;
  contributed_as_author: string | null;
  contributed_as_contributor: string | null;
  contributed_as_coordinator: string | null;
  contributed_as_creator: string | null;
  contributed_as_investor: string | null;
  contributed_as_propertor: string | null;
  contributor_hash: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  debt_amount: string | null;
  display_name: string;
  energy: number | null;
  generation_contract_hash: string | null;
  generator_offer_hash: string | null;
  hours_per_day: number | null;
  id: number | null;
  is_external_blagorost_agreement: Generated<boolean>;
  is_external_contract: Generated<boolean>;
  last_energy_update: Timestamp | null;
  level: number | null;
  memo: string | null;
  present: Generated<boolean>;
  program_key: string | null;
  rate_per_hour: string | null;
  reward_per_share_last: string | null;
  status: Generated<string>;
  storage_agreement_hash: string | null;
  username: string;
}

export interface CapitalCycles {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  end_date: Timestamp;
  name: string;
  present: Generated<boolean>;
  start_date: Timestamp;
  status: Generated<string>;
}

export interface CapitalDebts {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  amount: string;
  approved_statement: Json;
  authorization: Json;
  block_num: Generated<number>;
  blockchain_status: string;
  coopname: string | null;
  created_at: Timestamp | null;
  debt_hash: string;
  id: number | null;
  memo: string | null;
  present: Generated<boolean>;
  project_hash: string | null;
  repaid_at: Timestamp | null;
  statement: Json;
  status: Generated<string>;
  username: string | null;
}

export interface CapitalExpenses {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  amount: string;
  approved_statement: Json;
  authorization: Json;
  block_num: Generated<number>;
  blockchain_status: string;
  coopname: string;
  created_at: Timestamp | null;
  description: string;
  expense_hash: string;
  expense_statement: Json;
  fund_id: string;
  id: number | null;
  present: Generated<boolean>;
  project_hash: string;
  spended_at: Timestamp;
  status: Generated<string>;
  username: string;
}

export interface CapitalFavorites {
  _id: Generated<string>;
  coopname: string;
  created_at: Generated<Timestamp>;
  target_hash: string;
  target_type: CapitalFavoritesTargetTypeEnum;
  username: string;
}

export interface CapitalGithubBranchCommitSyncState {
  branch: string;
  coopname: string;
  github_repository: string;
  id: Generated<string>;
  last_synced_tip_sha: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CapitalGithubFileIndexes {
  coopname: string;
  created_at: Generated<Timestamp>;
  entity_hash: string;
  entity_type: string;
  file_path: string;
  github_sha: string | null;
  id: Generated<string>;
  last_synced_at: Generated<Timestamp>;
}

export interface CapitalInvests {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  amount: string;
  block_num: Generated<number>;
  blockchain_status: string;
  coopname: string;
  coordinator: string | null;
  coordinator_amount: string | null;
  created_at: Timestamp | null;
  id: number | null;
  invest_hash: string;
  invested_at: Timestamp;
  present: Generated<boolean>;
  project_hash: string;
  statement: Json;
  status: Generated<string>;
  username: string;
}

export interface CapitalIssueLinkedGitCommits {
  commit_message: string;
  committed_at: Timestamp;
  consumed_by_commit_hash: string | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  diff_text: string;
  first_seen_branch: string | null;
  git_author_email: string | null;
  git_author_login: string | null;
  github_owner: string;
  github_repo: string;
  github_sha: string;
  html_url: string;
  id: Generated<string>;
  in_default_branch: Generated<boolean>;
  issue_hash: string;
  patch_id: string | null;
  project_hash: string;
  username: string;
}

export interface CapitalIssueLinkedGitCommitShas {
  coopname: string;
  created_at: Generated<Timestamp>;
  github_sha: string;
  id: Generated<string>;
  linked_commit_id: string;
  seen_branch: string | null;
}

export interface CapitalIssueMetricBindings {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  delta: Generated<number>;
  issue_hash: string;
  metric_hash: string;
  present: Generated<boolean>;
  status: Generated<string>;
}

export interface CapitalIssues {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  content_rev: Generated<number>;
  coopname: string;
  created_by: string;
  creators: Generated<string[]>;
  cycle_id: string | null;
  description: string | null;
  estimate: Generated<number>;
  id: string;
  issue_hash: string;
  metadata: Generated<Json>;
  present: Generated<boolean>;
  priority: Generated<CapitalIssuesPriorityEnum>;
  project_hash: string | null;
  sort_order: Generated<number>;
  status: Generated<string>;
  submaster: string | null;
  title: string;
}

export interface CapitalMeasures {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  coopname: string;
  created_by: string;
  measure_hash: string;
  present: Generated<boolean>;
  series_mode: Generated<CapitalMeasuresSeriesModeEnum>;
  status: Generated<string>;
  title: string;
  unit: string;
}

export interface CapitalMetricContributions {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  contribution_hash: string;
  delta: Generated<number>;
  issue_hash: string | null;
  metric_hash: string;
  occurred_at: Timestamp;
  present: Generated<boolean>;
  source: CapitalMetricContributionsSourceEnum;
  status: Generated<string>;
  username: string;
}

export interface CapitalProcessInstances {
  completed_at: Timestamp | null;
  coopname: string;
  cycle: Generated<number>;
  id: Generated<string>;
  project_hash: string;
  started_at: Generated<Timestamp>;
  started_by: string;
  status: Generated<CapitalProcessInstancesStatusEnum>;
  step_states: Generated<Json>;
  template_id: string;
}

export interface CapitalProcessTemplates {
  coopname: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  edges: Generated<Json>;
  id: Generated<string>;
  project_hash: string;
  status: Generated<CapitalProcessTemplatesStatusEnum>;
  steps: Generated<Json>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface CapitalProgramProperties {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  act: Json;
  authorization: Json;
  block_num: Generated<number>;
  blockchain_status: string;
  coopname: string;
  created_at: Timestamp;
  id: number | null;
  present: Generated<boolean>;
  property_amount: string;
  property_description: string;
  property_hash: string;
  statement: Json;
  status: Generated<string>;
  username: string;
}

export interface CapitalProgramWallets {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  capital_available: string;
  coopname: string;
  id: number | null;
  last_program_crps: number;
  present: Generated<boolean>;
  status: Generated<string>;
  username: string;
}

export interface CapitalProgramWithdraws {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  amount: string;
  block_num: Generated<number>;
  blockchain_status: string;
  coopname: string;
  created_at: Timestamp;
  id: number | null;
  present: Generated<boolean>;
  statement: Json;
  status: Generated<string>;
  username: string;
  withdraw_hash: string;
}

export interface CapitalProjectProperties {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  blockchain_status: string;
  coopname: string;
  created_at: Timestamp;
  id: number | null;
  present: Generated<boolean>;
  project_hash: string;
  property_amount: string;
  property_description: string;
  property_hash: string;
  status: Generated<string>;
  username: string;
}

export interface CapitalProjects {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  authorization: Json | null;
  block_num: Generated<number>;
  blockchain_status: string;
  content_rev: Generated<number>;
  coopname: string;
  counts: Json;
  created_at: Timestamp;
  crps: Json;
  data: string | null;
  description: string;
  development_repository_url: string | null;
  fact: Json;
  id: number | null;
  invite: string | null;
  is_authorized: Generated<boolean>;
  is_opened: Generated<boolean>;
  is_planed: Generated<boolean>;
  issue_counter: Generated<number>;
  local_owner: string | null;
  master: string;
  matrix_component_announcement_events: Json | null;
  matrix_room_id: string | null;
  meta: string | null;
  origin: Generated<CapitalProjectOrigin>;
  parent_hash: string | null;
  plan: Json;
  prefix: string;
  present: Generated<boolean>;
  priority: Generated<CapitalProjectPriority>;
  project_hash: string;
  status: Generated<string>;
  title: string;
  voting: Json;
  voting_deadline: Timestamp | null;
}

export interface CapitalResults {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  act: Json | null;
  authorization: Json | null;
  block_num: Generated<number>;
  blockchain_status: string | null;
  coopname: string;
  created_at: Timestamp | null;
  data: string | null;
  debt_amount: string | null;
  id: number | null;
  present: Generated<boolean>;
  project_hash: string;
  result_hash: string;
  statement: Json | null;
  status: Generated<string>;
  total_amount: string | null;
  username: string;
}

export interface CapitalSegments {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  author_base: string | null;
  author_bonus: string | null;
  available_for_program: string | null;
  available_for_wallet: string | null;
  block_num: Generated<number>;
  capital_contributor_shares: string | null;
  contributor_bonus: string | null;
  coopname: string;
  coordinator_base: string | null;
  coordinator_investments: string | null;
  creator_base: string | null;
  creator_bonus: string | null;
  debt_amount: string | null;
  debt_settled: string | null;
  direct_creator_bonus: string | null;
  equal_author_bonus: string | null;
  has_vote: Generated<boolean>;
  id: number | null;
  intellectual_cost: string | null;
  investor_amount: string | null;
  investor_base: string | null;
  is_author: Generated<boolean>;
  is_completed: Generated<boolean>;
  is_contributor: Generated<boolean>;
  is_coordinator: Generated<boolean>;
  is_creator: Generated<boolean>;
  is_investor: Generated<boolean>;
  is_propertor: Generated<boolean>;
  is_votes_calculated: Generated<boolean>;
  last_author_base_reward_per_share: Generated<number>;
  last_author_bonus_reward_per_share: Generated<number>;
  last_contributor_reward_per_share: Generated<number>;
  last_known_coordinators_investment_pool: string | null;
  last_known_creators_base_pool: string | null;
  last_known_invest_pool: string | null;
  present: Generated<boolean>;
  project_hash: string;
  property_base: string | null;
  provisional_amount: string | null;
  share_percent: Generated<number>;
  status: Generated<string>;
  total_segment_base_cost: string | null;
  total_segment_bonus_cost: string | null;
  total_segment_cost: string | null;
  username: string;
  voting_bonus: string | null;
}

export interface CapitalState {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  config: Json;
  coopname: string;
  global_available_invest_pool: string;
  id: number | null;
  present: Generated<boolean>;
  program_membership_available: string;
  program_membership_cumulative_reward_per_share: number;
  program_membership_distributed: string;
  program_membership_funded: string;
  status: Generated<string>;
}

export interface CapitalStories {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  content_format: Generated<CapitalStoriesContentFormatEnum>;
  content_rev: Generated<number>;
  coopname: string;
  created_by: string;
  description: string | null;
  issue_hash: string | null;
  matrix_requirement_announcement_events: Json | null;
  present: Generated<boolean>;
  project_hash: string | null;
  sort_order: Generated<number>;
  status: Generated<string>;
  story_hash: string;
  title: string;
}

export interface CapitalTimeEntries {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  /**
   * Хеш коммита, если время уже закоммичено
   */
  commit_hash: string | null;
  /**
   * Хеш участника
   */
  contributor_hash: string;
  /**
   * Имя кооператива
   */
  coopname: string;
  /**
   * Дата работы (YYYY-MM-DD)
   */
  date: Timestamp;
  /**
   * Тип начисления времени: hourly (почасовое) или estimate (по завершению задачи)
   */
  entry_type: Generated<string | null>;
  /**
   * Снимок estimate на момент начисления времени (для отслеживания изменений)
   */
  estimate_snapshot: Numeric | null;
  /**
   * Количество часов
   */
  hours: Numeric;
  /**
   * Флаг, что время закоммичено
   */
  is_committed: Generated<boolean>;
  /**
   * Хеш задачи
   */
  issue_hash: string;
  present: Generated<boolean>;
  /**
   * Хеш проекта
   */
  project_hash: string;
  status: Generated<string>;
}

export interface CapitalTimerSessions {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  contributor_hash: string;
  coopname: string;
  issue_hash: string;
  paused_at: Timestamp | null;
  present: Generated<boolean>;
  project_hash: string;
  started_at: Timestamp;
  status: Generated<string>;
  stopped_at: Timestamp | null;
  total_paused_ms: Generated<Int8>;
}

export interface CapitalVotes {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  amount: string;
  block_num: Generated<number>;
  coopname: string;
  id: number | null;
  present: Generated<boolean>;
  project_hash: string;
  recipient: string;
  status: Generated<string>;
  voted_at: Timestamp;
  voter: string;
}

export interface CardcoopAttestations {
  attestation_id: string | null;
  card_id: string;
  card_number: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_error: string | null;
  member_since: string;
  revoked_at: Timestamp | null;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface CardcoopConnectState {
  delivered_hash: string | null;
  id: string;
  last_error: string | null;
  rp_client_id: string | null;
  rp_client_secret: string | null;
  rp_issuer: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CardcoopEntrySessions {
  card_id: string;
  card_number: string | null;
  created_at: Generated<Timestamp>;
  disclosure_id: string | null;
  id: Generated<string>;
  memberships: Generated<Json>;
  outcome: string;
  profile: Json | null;
  profile_taken_at: Timestamp | null;
  profile_type: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string | null;
}

export interface CardcoopOperatorAnnouncements {
  coopname: string;
  created_at: Generated<Timestamp>;
  delivered: Generated<boolean>;
  display_name: string;
  last_error: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CardcoopPendingExits {
  coopname: string;
  created_at: Generated<Timestamp>;
  exit_hash: string;
  username: string;
}

export interface CardcoopPendingLinks {
  card_id: string;
  card_number: string | null;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface CardcoopUsedGrants {
  card_id: string;
  created_at: Generated<Timestamp>;
  grant_jti: string;
  to_coopname: string;
  username: string;
}

export interface Categories {
  category_name: string;
  created_at: Generated<Timestamp>;
  description_category_id: number;
  disabled: Generated<boolean>;
  parent_id: number | null;
  updated_at: Generated<Timestamp>;
}

export interface ChainTexts {
  created_at: Generated<Timestamp>;
  digest: string;
  text: string;
}

export interface ChairmanApprovals {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  approval_hash: string;
  approved_document: Json | null;
  block_num: Generated<number>;
  callback_action_approve: string;
  callback_action_decline: string;
  callback_contract: string;
  coopname: string;
  created_at: Timestamp;
  document: Json;
  id: number;
  meta: string;
  present: Generated<boolean>;
  status: Generated<string>;
  username: string;
}

export interface ChatcoopCalendarEvents {
  created_at: Generated<Timestamp>;
  created_by_username: string;
  description: string | null;
  ends_at: Timestamp | null;
  ics_sequence: Generated<number>;
  id: Generated<string>;
  matrix_room_id: string;
  starts_at: Timestamp;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface ChatcoopCalendarIcsSubscriptions {
  coop_username: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  secret_sha256_hex: string;
}

export interface ChatcoopCallTranscriptions {
  created_at: Generated<Timestamp>;
  ended_at: Timestamp | null;
  id: Generated<string>;
  matrix_room_id: string;
  memo: Generated<string>;
  participants: Generated<Json>;
  room_id: string;
  room_name: string;
  started_at: Timestamp;
  status: Generated<ChatcoopCallTranscriptionsStatusEnum>;
  updated_at: Generated<Timestamp>;
}

export interface ChatcoopManagedMatrixRooms {
  created_at: Generated<Timestamp>;
  display_label: string;
  encrypted: boolean;
  id: Generated<string>;
  matrix_room_id: string;
  message_history_backfill_complete: Generated<boolean>;
  message_history_pagination_token: string | null;
  project_hash: string | null;
  room_kind: string;
  secretary_in_room: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface ChatcoopRoomMessageHistory {
  body_text: string;
  call_transcription_id: string | null;
  coop_username: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  livekit_room_name: string | null;
  matrix_event_id: string;
  matrix_room_id: string;
  message_kind: string;
  origin_server_ts: Int8;
  sender_display_name: string | null;
  sender_matrix_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ChatcoopState {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_initialized: Generated<boolean>;
  secretary_initialized: Generated<boolean>;
  secretary_matrix_user_id: string | null;
  secretary_password_encrypted: string | null;
  secretary_username: string | null;
  space_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ChatcoopTranscriptionSegments {
  created_at: Generated<Timestamp>;
  end_offset: number;
  id: Generated<string>;
  speaker_identity: string;
  speaker_name: string;
  start_offset: number;
  text: string;
  transcription_id: string;
}

export interface ConsumerDedup {
  applied_at: Generated<Timestamp>;
  block_num: Int8 | null;
  event_id: string;
}

export interface DraftTemplates {
  block_num: Int8;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  present: Generated<boolean>;
  registry_id: Int8;
  value: Json;
}

export interface DraftTranslations {
  block_num: Int8;
  created_at: Generated<Timestamp>;
  draft_id: Int8;
  id: Generated<string>;
  lang: string;
  present: Generated<boolean>;
  value: Json;
}

export interface EdubridgeAccessTasks {
  attempts: Generated<number>;
  carrier: EdubridgeAccessTasksCarrierEnum;
  coopname: string;
  created_at: Generated<Timestamp>;
  done_at: Timestamp | null;
  enrollment_id: string;
  id: Generated<string>;
  kind: EdubridgeAccessTasksKindEnum;
  last_error: string | null;
  last_result: string | null;
  next_attempt_at: Timestamp;
  recipient_override: Json | null;
  status: Generated<EdubridgeAccessTasksStatusEnum>;
  trigger_trx: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeConnectorBindings {
  carrier: EdubridgeConnectorBindingsCarrierEnum;
  coopname: string;
  created_at: Generated<Timestamp>;
  credentials_encrypted: string | null;
  credentials_updated_at: Timestamp | null;
  enabled: Generated<boolean>;
  health: Generated<EdubridgeConnectorBindingsHealthEnum>;
  id: Generated<string>;
  last_check_at: Timestamp | null;
  last_check_message: string | null;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeContributions {
  act_hash: string | null;
  act_signed: Json | null;
  amount: string;
  assignment_id: string;
  coopname: string;
  council_agenda_id: string | null;
  council_decision_id: string | null;
  council_outcome: EdubridgeContributionsCouncilOutcomeEnum | null;
  council_project_hash: string | null;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decision_document: Json | null;
  decision_hash: string | null;
  decline_reason: string | null;
  description: Generated<string>;
  hold_until: Timestamp | null;
  id: Generated<string>;
  lesson_id: string | null;
  links: Generated<Json>;
  rid_hash: string;
  rid_type: EdubridgeContributionsRidTypeEnum;
  statement_document: Json | null;
  statement_hash: string | null;
  status: Generated<EdubridgeContributionsStatusEnum>;
  storage_act_document: Json | null;
  storage_act_hash: string | null;
  teacher_username: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeCourses {
  carrier: EdubridgeCoursesCarrierEnum;
  chain_ref: Generated<Int8>;
  coopname: string;
  course_discount_bp: Generated<number>;
  course_payment_enabled: Generated<boolean>;
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  direction: Generated<EdubridgeCoursesDirectionEnum>;
  external_checked_at: Timestamp | null;
  external_ref: Generated<string>;
  external_title_seen: string | null;
  fee_month: string;
  grade: Generated<string | null>;
  guarantee_days: Generated<number>;
  id: Generated<string>;
  image: Json | null;
  lesson_minutes: Generated<number>;
  lessons_per_month: Generated<number>;
  lessons_total: Generated<number>;
  level_id: string | null;
  pay_per_learner: Generated<boolean>;
  planned_hourly_rate: Generated<string>;
  schedule: Generated<string>;
  section_id: string | null;
  sort_order: Generated<number>;
  starts_at: Timestamp | null;
  status: Generated<EdubridgeCoursesStatusEnum>;
  subject: Generated<string | null>;
  syllabus: Generated<string>;
  teacher_reserve_balance: string | null;
  teacher_settled_total: string | null;
  teacher_usernames: Generated<Json>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeEnrollments {
  access_state: Generated<EdubridgeEnrollmentsAccessStateEnum>;
  cancelled_at: Timestamp | null;
  close_error: string | null;
  close_pending_since: Timestamp | null;
  coopname: string;
  course_id: string;
  created_at: Generated<Timestamp>;
  expiry_notified_at: Timestamp | null;
  group_id: string | null;
  id: Generated<string>;
  joined_at: Timestamp | null;
  learner_id: string;
  locked_amount: string | null;
  member_username: string;
  paid_amount: Generated<string>;
  paid_months: number | null;
  paid_until: Timestamp | null;
  period: EdubridgeEnrollmentsPeriodEnum;
  refund_reason: string | null;
  refunded_amount: string | null;
  statement_hash: string | null;
  status: Generated<EdubridgeEnrollmentsStatusEnum>;
  sub_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeGroups {
  chain_ref: Generated<Int8>;
  coopname: string;
  course_discount_bp: Generated<number>;
  course_id: string;
  course_payment_enabled: Generated<boolean>;
  created_at: Generated<Timestamp>;
  enrollment_closed_on_start: Generated<boolean>;
  enrollment_open: Generated<boolean>;
  external_ref: Generated<string>;
  fee_month: string;
  guarantee_days: Generated<number>;
  id: Generated<string>;
  lesson_minutes: Generated<number>;
  lessons_per_month: Generated<number>;
  lessons_total: Generated<number>;
  pay_per_learner: Generated<boolean>;
  planned_hourly_rate: Generated<string>;
  starts_at: Timestamp | null;
  status: Generated<string>;
  teacher_reserve_balance: string | null;
  teacher_settled_total: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeGuaranteeClaims {
  amount: string;
  claim_hash: string;
  coopname: string;
  council_agenda_id: string | null;
  council_decision_id: string | null;
  council_project_hash: string | null;
  course_id: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decision_hash: string | null;
  enrollment_id: string;
  id: Generated<string>;
  links: Generated<Json>;
  member_username: string;
  reason: string;
  statement_document: Json;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeLearners {
  chain_ref: Generated<Int8>;
  coopname: string;
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  is_self: Generated<boolean>;
  member_username: string;
  platform_removed_at: Timestamp | null;
  recipient_type: Generated<EdubridgeLearnersRecipientTypeEnum>;
  recipient_value: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeLessons {
  assignment_id: string;
  contribution_id: string | null;
  coopname: string;
  course_id: string;
  created_at: Generated<Timestamp>;
  duration_minutes: number;
  group_id: string | null;
  held_at: Timestamp;
  id: Generated<string>;
  learners_count: number | null;
  lesson_number: number;
  materials: Generated<Json>;
  teacher_username: string;
  topic: Generated<string>;
}

export interface EdubridgeLevels {
  archived: Generated<boolean>;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  section_id: string;
  sort_order: Generated<number>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeReturnRequests {
  amount: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decline_reason: Generated<string>;
  id: Generated<string>;
  member_username: string;
  statement_document: Json;
  statement_hash: string;
  status: Generated<EdubridgeReturnRequestsStatusEnum>;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeSections {
  archived: Generated<boolean>;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  sort_order: Generated<number>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeShareReturns {
  amount: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  payment_hash: string;
  return_statement_document: Json;
  teacher_username: string;
  transfer_statement_document: Json;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeTeacherAssignments {
  chain_ref: Generated<Int8>;
  coopname: string;
  course_id: string;
  created_at: Generated<Timestamp>;
  expected_result: Generated<string>;
  hourly_rate: Generated<string>;
  id: Generated<string>;
  minutes_per_month: Generated<number>;
  period_from: Timestamp;
  period_to: Timestamp;
  schedule: Generated<string>;
  status: Generated<EdubridgeTeacherAssignmentsStatusEnum>;
  teacher_username: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeTeacherContracts {
  approved_at: Timestamp | null;
  contract_document: Json | null;
  contract_hash: string;
  contract_number: string;
  coopname: string;
  decline_reason: Generated<string>;
  hourly_rate: Generated<string>;
  id: Generated<string>;
  signed_at: Generated<Timestamp>;
  status: Generated<EdubridgeTeacherContractsStatusEnum>;
  teacher_username: string;
  updated_at: Generated<Timestamp>;
}

export interface EdubridgeTeacherProfiles {
  about: Generated<string>;
  coopname: string;
  created_at: Generated<Timestamp>;
  hourly_rate: Generated<string>;
  id: Generated<string>;
  teacher_username: string;
  updated_at: Generated<Timestamp>;
}

export interface EntityVersions {
  block_num: number | null;
  change_type: string;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_table: string;
  id: Generated<string>;
  metadata: Json | null;
  previous_data: Json;
}

export interface ExpenseFiles {
  checksum_sha256: string;
  coopname: string;
  id: Generated<number>;
  item_hash: string | null;
  kind: ExpenseFilesKindEnum;
  mime_type: string;
  /**
   * Оригинальное имя загруженного файла — для отображения и поиска
   */
  original_filename: string | null;
  proposal_hash: string;
  size_bytes: number;
  storage_key: string;
  uploaded_at: Generated<Timestamp>;
  uploaded_by_username: string;
}

export interface ExpensePlans {
  /**
   * Сумма расхода в валюте кооператива
   */
  amount: Numeric;
  /**
   * Кооперативный участок; NULL — расход уровня кооператива
   */
  braname: string | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  /**
   * Кто добавил запись
   */
  creator: string;
  /**
   * Срок оплаты. Обязателен для новых записей; NULL остался у записей до отмены приоритетов
   */
  due_date: Timestamp | null;
  id: Generated<number>;
  /**
   * По этой записи уже добавлен следующий экземпляр серии (защита от повторного порождения)
   */
  next_spawned: Generated<boolean>;
  /**
   * Когда расход фактически оплачен; оплаченные записи не удерживают резерв
   */
  paid_at: Timestamp | null;
  /**
   * Реквизиты получателя платежа (строкой — передаётся в платёжку кассиру)
   */
  pay_to: string;
  /**
   * Расход, которым оплачивается запись (служебная записка шасси расходов); NULL — оплата не запускалась
   */
  proposal_hash: string | null;
  /**
   * Периодичность серии: NONE — разовый; MONTHLY/QUARTERLY/YEARLY — повторяющийся
   */
  recurrence: Generated<string>;
  /**
   * Назначение расхода
   */
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface ExpenseProposals {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  blockchain_status: number | null;
  callback: Json | null;
  coopname: string;
  created_at: Timestamp | null;
  decision_doc: Json | null;
  id: number | null;
  items: Json | null;
  present: Generated<boolean>;
  proposal_hash: string;
  source_wallet: string;
  statement_doc: Json | null;
  status: Generated<string>;
  total_actual: string;
  total_planned: string;
  updated_at: Timestamp | null;
  username: string;
}

export interface ExpenseRequisiteSnapshots {
  coopname: string;
  created_at: Generated<Timestamp>;
  /**
   * Снимок данных платёжного метода на момент создания СЗ
   */
  data: Json | null;
  id: Generated<number>;
  item_hash: string;
  /**
   * Идентификатор платёжного метода получателя (для пайщиков)
   */
  method_id: string | null;
  /**
   * Тип метода (sbp / bank_transfer)
   */
  method_type: string | null;
  /**
   * Назначение платежа (оплата по счёту) — для поручения кассиру
   */
  payment_purpose: string | null;
  proposal_hash: string;
  /**
   * Получатель платежа (username пайщика или имя организации)
   */
  recipient: string;
  /**
   * Реквизиты строкой — как в документе СЗ
   */
  requisites: string;
}

export interface Extensions {
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  name: string;
  schema_version: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface ExtensionsLogs {
  created_at: Generated<Timestamp>;
  data: Generated<Json>;
  extension_local_id: Generated<number>;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface GeneratedReports {
  coopname: string;
  corrections_snapshot: Json | null;
  created_at: Generated<Timestamp>;
  file_name: string;
  generated_by: string;
  id: Generated<string>;
  is_valid: Generated<boolean>;
  organization_snapshot: Json;
  period: number | null;
  report_type: string;
  validation_errors: Json | null;
  xml: string;
  year: number;
}

export interface InvalidatedEntities {
  created_at: Generated<Timestamp>;
  data: Json;
  entity_id: string;
  entity_table: string;
  fork_event_id: string | null;
  id: Generated<string>;
  invalidated_by_block: number;
}

export interface InvalidatedEntityVersions {
  change_type: string;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_table: string;
  fork_event_id: string | null;
  id: Generated<string>;
  invalidated_by_block: number;
  metadata: Json | null;
  original_block_num: number | null;
  previous_data: Json;
}

export interface Ipn {
  created_at: Generated<Timestamp>;
  data: Json;
  id: Generated<string>;
  provider: string;
  updated_at: Generated<Timestamp>;
}

export interface KuDecisionQuestions {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  context: Generated<string>;
  coopname: string;
  counter_votes_abstained: Generated<number>;
  counter_votes_against: Generated<number>;
  counter_votes_for: Generated<number>;
  decision: string;
  decision_id: number;
  id: number | null;
  number: number;
  present: Generated<boolean>;
  status: Generated<string>;
  title: string;
  voters_abstained: Generated<Json>;
  voters_against: Generated<Json>;
  voters_for: Generated<Json>;
}

export interface KuDecisions {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  address: Generated<string>;
  authority: Json | null;
  authorization: Json | null;
  block_num: Generated<number>;
  braname: Generated<string>;
  branch_email: string | null;
  branch_name: string | null;
  branch_phone: string | null;
  cancelled: Generated<boolean>;
  chairman: Generated<string>;
  close_at: Timestamp | null;
  coopname: string;
  created_at: Timestamp | null;
  hash: string;
  id: number | null;
  initiator: string;
  liability: Json | null;
  meet_at: Timestamp | null;
  meet_place: string | null;
  meet_reminder_sent: Generated<boolean>;
  open_at: Timestamp | null;
  participants: Generated<Json>;
  petition: Json | null;
  present: Generated<boolean>;
  proposal: Json | null;
  protocol: Json | null;
  signed_ballots: Generated<number>;
  status: Generated<string>;
  type: string;
}

export interface KuTrustRequests {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  application: Json | null;
  authority: Json | null;
  block_num: Generated<number>;
  braname: string;
  coopname: string;
  hash: string;
  id: number | null;
  present: Generated<boolean>;
  status: Generated<string>;
  username: string;
}

export interface LedgerOperations {
  account_id: Int8 | null;
  action: string;
  comment: string | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  global_sequence: Int8;
  hash: string | null;
  quantity: string | null;
  username: string | null;
}

export interface MarketplaceAplReception {
  braname: string;
  chairman_account: string | null;
  chairman_signchair_tx_hash: string | null;
  chairman_signed_at: Timestamp | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  created_by_operator_account: string;
  cycle_id: string;
  expeditor_data: Json | null;
  fact_quantity_per_order: Json;
  id: Generated<string>;
  offerer_account: string;
  shipment_id: string;
  status: string;
  supplier_signed_at: Timestamp | null;
  supplier_signed_documents: Json | null;
  supplier_signsupp_tx_hash: string | null;
  total_amount: Numeric;
  ttn_number: string | null;
  updated_at: Generated<Timestamp>;
  variant: string;
}

export interface MarketplaceCart {
  coopname: string;
  created_at: Generated<Timestamp>;
  delivery_braname: string | null;
  id: Generated<string>;
  orderer_account: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceCartItem {
  cart_id: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  offer_id: string;
  package_id: Generated<string>;
  quantity: Numeric;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceCategory {
  coopname: string | null;
  display_name: string;
  id: number;
  mvp_baseline: Generated<boolean>;
  sort_order: number;
}

export interface MarketplaceConsolidatedRequest {
  accepted_at: Timestamp | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  cycle_ended_at: Timestamp | null;
  cycle_started_at: Timestamp;
  decline_reason: string | null;
  declined_at: Timestamp | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  offer_id: string;
  status: string;
  supplier_account: string;
  total_amount: Numeric;
  total_quantity: number;
  triggered_by_supplier_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceContainer {
  braname: string;
  cell_id: string | null;
  code: string;
  container_type_id: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  label: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceContainerType {
  coopname: string;
  created_at: Generated<Timestamp>;
  height_cm: Generated<number>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  length_cm: Generated<number>;
  max_weight_kg: Numeric | null;
  name: string;
  updated_at: Generated<Timestamp>;
  volume_m3: Generated<Numeric>;
  width_cm: Generated<number>;
}

export interface MarketplaceInventory {
  arrival_price: Numeric | null;
  barcode_format: string | null;
  barcode_value: string | null;
  braname: string;
  cell_id: string | null;
  container_id: string | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  expiry_date: Timestamp | null;
  id: Generated<string>;
  labeled_at: Timestamp | null;
  labeled_by_operator_account: string | null;
  order_id: string;
  orderer_account_snapshot: string;
  origin: Generated<string>;
  ownership: Generated<string>;
  package_size: Generated<Numeric>;
  product_name_snapshot: string;
  published_offer_id: string | null;
  quantity_per_label: number;
  received_at: Timestamp | null;
  received_by_operator_account: string | null;
  reserved_order_id: string | null;
  return_claim_id: string | null;
  shelf: string | null;
  shipment_id: string;
  status: string;
  unit_of_measure: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceIssuanceSaga {
  act_document_hash: string | null;
  act1_document: Json | null;
  act2_document: Json | null;
  attempts: Generated<number>;
  braname: string;
  closed_at: Timestamp | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decision_id: string | null;
  decision_mode: Generated<string>;
  fact: Json;
  id: Generated<string>;
  last_error: string | null;
  member_account: string;
  operator_account: string;
  order_hash: string;
  order_id: string;
  proposal_id: string | null;
  protocol_document: Json | null;
  stage: string;
  statement_document: Json | null;
  tx_hashes: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceKuDetails {
  coopname: string;
  /**
   * braname в core coop_ku
   */
  core_braname: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  geocode_error_message: string | null;
  geocode_status: Generated<MarketplaceKuDetailsGeocodeStatusEnum>;
  /**
   * Адрес, по которому посчитаны координаты (кэш-ключ геокода)
   */
  geocoded_address: string | null;
  geocoded_at: Timestamp | null;
  id: Generated<number>;
  lat: number | null;
  lng: number | null;
  status: Generated<MarketplaceKuDetailsStatusEnum>;
  updated_at: Generated<Timestamp>;
  working_hours_json: Json;
}

export interface MarketplaceModerationLog {
  action: string;
  by_account: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  offer_id: string;
  reason: string | null;
}

export interface MarketplaceOffer {
  approved_at: Timestamp | null;
  approved_by: string | null;
  barcode_strategy: Generated<string>;
  category_id: number;
  coopname: string;
  created_at: Generated<Timestamp>;
  delivery_points: Generated<Json>;
  description: string | null;
  id: Generated<string>;
  images: Generated<Json>;
  pack_size: number | null;
  packages: Generated<Json>;
  price_per_unit: Numeric;
  product_name: string;
  quantity_available: Generated<Numeric>;
  quantity_blocked: Generated<Numeric>;
  quantity_consumed: Generated<Numeric>;
  reject_reason: string | null;
  rejected_at: Timestamp | null;
  rejected_by: string | null;
  sale_form: Generated<string>;
  shelf_life_days: Generated<number>;
  status: string;
  stock_braname: string | null;
  stock_origin_offer_id: string | null;
  supplier_account: string;
  unit_of_measure: string;
  unlimited_flag: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  vitrine_id: string;
  warranty_days: Generated<number>;
}

export interface MarketplaceOrder {
  accepted_at: Timestamp | null;
  accepted_cost: Numeric | null;
  blocked_at: Timestamp | null;
  cancelled_at: Timestamp | null;
  checkout_id: string | null;
  coopname: string;
  create_tx: Json | null;
  created_at: Generated<Timestamp>;
  current_warehouse_braname: string | null;
  cycle_id: string | null;
  delivery_braname: string;
  delivery_signer_account: string | null;
  id: Generated<string>;
  issuance_fact: Json | null;
  issue_closed_tx_hash: string | null;
  issue_decision_id: string | null;
  issue_statement_at: Timestamp | null;
  last_status_reason: string | null;
  markdown_cost: Numeric | null;
  markdown_due: Numeric | null;
  membership_fee: Numeric | null;
  offer_hash: string;
  offer_id: string;
  on_chain_block_num: Int8 | null;
  on_chain_id: string | null;
  on_chain_present: Generated<boolean>;
  order_hash: string;
  orderer_account: string;
  package_id: string | null;
  package_size: Generated<Numeric>;
  payout_status: string | null;
  price_per_unit: Numeric;
  quantity: Numeric;
  ready_announced_at: Timestamp | null;
  received_at: Timestamp | null;
  shipment_id: string | null;
  status: string;
  supplier_account: string;
  total_cost: Numeric;
  unit_of_measure: Generated<string>;
  updated_at: Generated<Timestamp>;
  warranty_period_secs: number;
  warranty_until: Timestamp | null;
}

export interface MarketplaceOutgoingPaymentRequest {
  amount: Numeric;
  apl_reception_id: string;
  completed_at: Timestamp | null;
  coopname: string;
  core_payment_id: string | null;
  created_at: Generated<Timestamp>;
  decline_reason: string | null;
  id: Generated<string>;
  order_hash: string;
  order_id: string;
  payee_account: string;
  payout_destination: string | null;
  payout_tx_hash: string | null;
  purpose: string;
  status: string;
  symbol: string;
  updated_at: Generated<Timestamp>;
  withheld_amount: Generated<Numeric>;
}

export interface MarketplaceReturnClaim {
  accepted_at: Timestamp | null;
  actual_quantity: number;
  cancel_statement: Json | null;
  coopname: string;
  council_decision_id: string | null;
  council_decision_mode: string | null;
  council_protocol: Json | null;
  created_at: Generated<Timestamp>;
  decision_log: Generated<Json>;
  defect_category: string | null;
  delivery_braname: string;
  expected_resolution: string;
  fact_cost: Numeric;
  fee_refund: Generated<Numeric>;
  fee_refund_pending_at: Timestamp | null;
  id: Generated<string>;
  ledger_snapshot: Json | null;
  on_site_inspection: Json | null;
  order_hash: string;
  order_id: string;
  orderer_account: string;
  photos: Json;
  reason_text: string;
  request_hash: string;
  statement: Json | null;
  status: string;
  submretrn_tx_hash: string;
  supplier_account: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceShipment {
  braname: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  cycle_id: string;
  delivery_variant: string;
  id: Generated<string>;
  offerer_account: string;
  status: string;
  total_amount: Numeric;
  ttn_data: Json | null;
  ttn_document_id: string | null;
  ttn_number: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceStockProposal {
  braname: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  created_order_ids: Generated<Json>;
  id: Generated<string>;
  items: Generated<Json>;
  member_account: string;
  operator_account: string;
  resolved_at: Timestamp | null;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceStorageCell {
  braname: string;
  code: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  label: string | null;
  level: number;
  section: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceSupplier {
  contract_date: Timestamp | null;
  contract_document_url: string | null;
  contract_number: string | null;
  coopname: string;
  id: Generated<string>;
  member_account: string;
  model: string;
  requested_at: Generated<Timestamp>;
  requested_by: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  status: string;
}

export interface MarketplaceSupplierClaim {
  actual_quantity: number;
  amount: Numeric;
  claim_hash: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  decide_tx_hash: string | null;
  decided_at: Timestamp | null;
  delivery_braname: string;
  id: Generated<string>;
  inspection_result: Generated<string>;
  issue_tx_hash: Generated<string>;
  issued_at: Timestamp;
  order_hash: string;
  order_id: string;
  orderer_account: string;
  photos: Generated<Json>;
  reason_text: string;
  reclamation: Json | null;
  return_claim_id: string;
  status: string;
  supplier_account: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceSupplierSettings {
  coopname: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  payout_method_id: string | null;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface MarketplaceSupplyValidationLog {
  attempted_groups: Json;
  coopname: string;
  created_at: Generated<Timestamp>;
  cycle_id: string;
  id: Generated<string>;
  offerer_account: string;
  outcome: string;
  reason: string | null;
  reason_code: string | null;
}

export interface MarketplaceTtnDocument {
  accept_braname: string;
  content_html: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  currency: string;
  document_hash: string;
  id: Generated<string>;
  meta: Json;
  registry_id: number;
  shipment_id: string;
  supplier_account: string;
  total_amount: Numeric;
  ttn_data: Json;
  ttn_number: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceVitrine {
  coopname: string;
  created_at: Generated<Timestamp>;
  display_name: string;
  id: string;
  is_default: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface MarketplaceWriteoffProposal {
  authorized_at: Timestamp | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  cycle_started_at: Timestamp;
  decided_by_account: string | null;
  decision_id: Int8 | null;
  decision_log: Generated<Json>;
  executed_at: Timestamp | null;
  id: Generated<string>;
  items: Json;
  proposal_hash: Generated<string>;
  proposed_by_account: string | null;
  protocol_doc: Json | null;
  reject_reason: string | null;
  rejected_at: Timestamp | null;
  statement_doc: Json | null;
  status: string;
  submitted_at: Timestamp | null;
  total_amount: string;
  trigger: string;
  updated_at: Generated<Timestamp>;
}

export interface MatrixUsers {
  coop_username: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  matrix_user_id: string;
  matrix_username: string;
  updated_at: Generated<Timestamp>;
}

export interface MeetPre {
  agenda: Json;
  close_at: Timestamp;
  coopname: string;
  created_at: Generated<Timestamp>;
  details: string | null;
  hash: string;
  initiator: string;
  open_at: Timestamp;
  presider: string;
  proposal: Json | null;
  secretary: string;
}

export interface MeetProcessed {
  coopname: Json;
  decision: Json;
  hash: string;
  presider: string;
  quorum_passed: boolean;
  quorum_percent: number;
  results: Json;
  secretary: string;
  signed_ballots: number;
}

export interface MembershipExitRequests {
  annulment: Json | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  exit_hash: string;
  id: Generated<string>;
  statement: Json;
  token: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface Migrations {
  createdAt: Generated<Timestamp>;
  executedAt: Timestamp;
  logs: string | null;
  name: string;
  success: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  version: string;
}

export interface MutationLogs {
  _id: Generated<string>;
  arguments: Json;
  coopname: string | null;
  created_at: Generated<Timestamp>;
  duration_ms: number;
  error_message: string | null;
  mutation_name: string;
  status: string;
  username: string;
}

export interface NotificationDeliveries {
  attemptNumber: number;
  channel: string;
  coopname: string;
  createdAt: Generated<Timestamp>;
  error: string | null;
  id: Generated<string>;
  outboxId: string;
  providerResponse: string | null;
  recipientSubscriberId: string;
  status: string;
  workflowId: string;
}

export interface NotificationInbox {
  actorSubscriberId: string | null;
  body: string;
  coopname: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isRead: Generated<boolean>;
  outboxId: string;
  payload: Json | null;
  readAt: Timestamp | null;
  recipientSubscriberId: string;
  recipientUsername: string | null;
  title: string;
  workflowId: string;
}

export interface NotificationOutbox {
  actorSubscriberId: string | null;
  attempts: Generated<number>;
  channel: string;
  coopname: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idempotencyKey: string;
  lastError: string | null;
  maxAttempts: Generated<number>;
  payload: Json | null;
  recipientEmail: string | null;
  recipientSubscriberId: string;
  recipientUsername: string | null;
  scheduledAt: Timestamp;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  workflowId: string;
}

export interface PaymentFiles {
  checksum_sha256: string;
  coopname: string;
  id: Generated<number>;
  kind: PaymentFilesKindEnum;
  mime_type: string;
  /**
   * Оригинальное имя загруженного файла — для отображения и поиска
   */
  original_filename: string | null;
  payment_hash: string;
  size_bytes: number;
  storage_key: string;
  uploaded_at: Generated<Timestamp>;
  uploaded_by_username: string;
}

export interface Payments {
  blockchain_data: Json | null;
  completed_at: Timestamp | null;
  coopname: string;
  created_at: Generated<Timestamp>;
  direction: PaymentsDirectionEnum;
  expired_at: Timestamp | null;
  failed_at: Timestamp | null;
  hash: string;
  id: Generated<string>;
  memo: string | null;
  message: string | null;
  payment_details: Json | null;
  payment_method_id: string | null;
  provider: string | null;
  quantity: Numeric;
  related_entity_id: string | null;
  related_extension: string | null;
  secret: string | null;
  statement: Json | null;
  status: Generated<PaymentsStatusEnum>;
  symbol: string;
  type: PaymentsTypeEnum;
  updated_at: Generated<Timestamp | null>;
  username: string;
}

export interface PaymentState {
  accountNumber: string;
  created_at: Generated<Timestamp>;
  lastProcessedPage: Generated<number>;
  statementDate: string;
  updated_at: Generated<Timestamp>;
}

export interface ProgramWallets {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  agreement_id: string;
  available: string;
  block_num: Generated<number>;
  blocked: string;
  coopname: string;
  id: string;
  membership_contribution: string;
  present: Generated<boolean>;
  program_id: string;
  status: Generated<string>;
  username: string;
}

export interface ReportDrafts {
  coopname: string;
  created_at: Generated<Timestamp>;
  edited_fields: Generated<Json>;
  edits_json: Json;
  id: Generated<string>;
  owner_username: string;
  period: number | null;
  report_type: string;
  updated_at: Generated<Timestamp>;
  year: number;
}

export interface ReportRequisites {
  address_override: string | null;
  chairman_position: string | null;
  coopname: string;
  okfs: string | null;
  okopf: string | null;
  okpo: string | null;
  oktmo: string | null;
  okved: string | null;
  pfr_reg_number: string | null;
  phone_override: string | null;
  sfr_reg_number: string | null;
  signer_inn: string | null;
  signer_rep_doc: string | null;
  signer_snils: string | null;
  signer_type: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface ReportSubmissionMarks {
  coopname: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  mark: string;
  period: number | null;
  report_type: string;
  updated_at: Generated<Timestamp>;
  year: number;
}

export interface RoleAssignments {
  assigned_at: Generated<Timestamp>;
  assigned_by: string;
  coopname: string;
  extension_name: string;
  id: Generated<number>;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  role: string;
  username: string;
}

export interface SchemaMigrations {
  id: Generated<number>;
  name: string;
  timestamp: Int8;
}

export interface Settings {
  authorized_default_route: string;
  authorized_default_workspace: string;
  coopname: string;
  created_at: Generated<Timestamp>;
  extra_settings: Generated<Json>;
  non_authorized_default_route: string;
  non_authorized_default_workspace: string;
  provider_name: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface SignedDocuments {
  action: Generated<string>;
  block_num: Int8 | null;
  content_text: Generated<string>;
  coopname: string;
  created_at: Generated<Timestamp>;
  doc_hash: Generated<string>;
  document_aggregate: Json | null;
  document_created_at: Timestamp | null;
  full_title: Generated<string>;
  hash: string;
  id: Generated<string>;
  package: string;
  registry_id: Generated<number>;
  signers_text: Generated<string>;
  source_action_data: Json | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: Generated<string>;
}

export interface SovietRobotDecisions {
  attempts: Generated<number>;
  coopname: string;
  created_at: Generated<Timestamp>;
  decision_hash: string;
  decision_id: number;
  decision_type: string;
  id: Generated<string>;
  last_error: string | null;
  next_attempt_at: Timestamp | null;
  protocol_hash: string | null;
  stage: Generated<string>;
  tx_hashes: Generated<Json>;
  updated_at: Generated<Timestamp>;
  username: string;
  votes: Generated<Json>;
  waiting_for: Generated<Json>;
}

export interface SovietRobotKeys {
  coopname: string;
  created_at: Generated<Timestamp>;
  encrypted_wif: string;
  id: Generated<string>;
  member: string;
  permission_name: string;
  public_key: string;
  updated_at: Generated<Timestamp>;
}

export interface SystemStatus {
  coopname: string;
  created_at: Generated<Timestamp>;
  init_by_server: Generated<boolean>;
  install_code: string | null;
  install_code_expires_at: Timestamp | null;
  status: Generated<SystemStatusStatusEnum>;
  updated_at: Generated<Timestamp>;
}

export interface Tokens {
  blacklisted: Generated<boolean>;
  created_at: Generated<Timestamp>;
  expires: Timestamp;
  id: Generated<string>;
  token: string;
  type: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TrackingRules {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  event_type: string;
  hash: string;
  id: Generated<string>;
  metadata: Json | null;
  vars_field: string;
}

export interface Types {
  created_at: Generated<Timestamp>;
  description_category_id: number;
  disabled: Generated<boolean>;
  type_id: number;
  type_name: string;
  updated_at: Generated<Timestamp>;
}

export interface UnionChats {
  coop_username: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  matrix_user_id: string;
  room_id: string;
  union_name: string;
  union_person_id: string;
}

export interface UserAgreements {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  block_num: Generated<number>;
  coopname: string;
  present: Generated<boolean>;
  programs: Generated<Json>;
  status: Generated<string>;
  username: string;
}

export interface Users {
  avatar_key: string | null;
  avatar_mime: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  has_account: Generated<boolean>;
  id: Generated<string>;
  is_email_verified: Generated<boolean>;
  is_registered: Generated<boolean>;
  joined_at: Timestamp | null;
  legacy_mongo_id: string | null;
  message: Generated<string>;
  public_key: Generated<string>;
  referer: Generated<string>;
  role: Generated<string>;
  status: string;
  subscriber_hash: Generated<string>;
  subscriber_id: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface UserWallets {
  _created_at: Generated<Timestamp>;
  _id: Generated<string>;
  _updated_at: Generated<Timestamp>;
  available: string;
  block_num: Generated<number>;
  blocked: string;
  coopname: string;
  id: string;
  present: Generated<boolean>;
  status: Generated<string>;
  username: string;
  wallet_name: string;
}

export interface Vaults {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  permission: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string;
  wif: string;
}

export interface WebPushSubscriptions {
  authKey: string;
  createdAt: Generated<Timestamp>;
  endpoint: string;
  id: Generated<string>;
  isActive: Generated<boolean>;
  p256dhKey: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  username: string;
}

export interface DB {
  agreements: Agreements;
  available_categories: AvailableCategories;
  balance_corrections: BalanceCorrections;
  blockchain_actions: BlockchainActions;
  blockchain_deltas: BlockchainDeltas;
  blockchain_forks: BlockchainForks;
  blockchain_sync_state: BlockchainSyncState;
  candidates: Candidates;
  capital_appendixes: CapitalAppendixes;
  capital_comments: CapitalComments;
  capital_commits: CapitalCommits;
  capital_component_metrics: CapitalComponentMetrics;
  capital_content_revisions: CapitalContentRevisions;
  capital_contributors: CapitalContributors;
  capital_cycles: CapitalCycles;
  capital_debts: CapitalDebts;
  capital_expenses: CapitalExpenses;
  capital_favorites: CapitalFavorites;
  capital_github_branch_commit_sync_state: CapitalGithubBranchCommitSyncState;
  capital_github_file_indexes: CapitalGithubFileIndexes;
  capital_invests: CapitalInvests;
  capital_issue_linked_git_commit_shas: CapitalIssueLinkedGitCommitShas;
  capital_issue_linked_git_commits: CapitalIssueLinkedGitCommits;
  capital_issue_metric_bindings: CapitalIssueMetricBindings;
  capital_issues: CapitalIssues;
  capital_measures: CapitalMeasures;
  capital_metric_contributions: CapitalMetricContributions;
  capital_process_instances: CapitalProcessInstances;
  capital_process_templates: CapitalProcessTemplates;
  capital_program_properties: CapitalProgramProperties;
  capital_program_wallets: CapitalProgramWallets;
  capital_program_withdraws: CapitalProgramWithdraws;
  capital_project_properties: CapitalProjectProperties;
  capital_projects: CapitalProjects;
  capital_results: CapitalResults;
  capital_segments: CapitalSegments;
  capital_state: CapitalState;
  capital_stories: CapitalStories;
  capital_time_entries: CapitalTimeEntries;
  capital_timer_sessions: CapitalTimerSessions;
  capital_votes: CapitalVotes;
  cardcoop_attestations: CardcoopAttestations;
  cardcoop_connect_state: CardcoopConnectState;
  cardcoop_entry_sessions: CardcoopEntrySessions;
  cardcoop_operator_announcements: CardcoopOperatorAnnouncements;
  cardcoop_pending_exits: CardcoopPendingExits;
  cardcoop_pending_links: CardcoopPendingLinks;
  cardcoop_used_grants: CardcoopUsedGrants;
  categories: Categories;
  chain_texts: ChainTexts;
  chairman_approvals: ChairmanApprovals;
  chatcoop_calendar_events: ChatcoopCalendarEvents;
  chatcoop_calendar_ics_subscriptions: ChatcoopCalendarIcsSubscriptions;
  chatcoop_call_transcriptions: ChatcoopCallTranscriptions;
  chatcoop_managed_matrix_rooms: ChatcoopManagedMatrixRooms;
  chatcoop_room_message_history: ChatcoopRoomMessageHistory;
  chatcoop_state: ChatcoopState;
  chatcoop_transcription_segments: ChatcoopTranscriptionSegments;
  consumer_dedup: ConsumerDedup;
  draft_templates: DraftTemplates;
  draft_translations: DraftTranslations;
  edubridge_access_tasks: EdubridgeAccessTasks;
  edubridge_connector_bindings: EdubridgeConnectorBindings;
  edubridge_contributions: EdubridgeContributions;
  edubridge_courses: EdubridgeCourses;
  edubridge_enrollments: EdubridgeEnrollments;
  edubridge_groups: EdubridgeGroups;
  edubridge_guarantee_claims: EdubridgeGuaranteeClaims;
  edubridge_learners: EdubridgeLearners;
  edubridge_lessons: EdubridgeLessons;
  edubridge_levels: EdubridgeLevels;
  edubridge_return_requests: EdubridgeReturnRequests;
  edubridge_sections: EdubridgeSections;
  edubridge_share_returns: EdubridgeShareReturns;
  edubridge_teacher_assignments: EdubridgeTeacherAssignments;
  edubridge_teacher_contracts: EdubridgeTeacherContracts;
  edubridge_teacher_profiles: EdubridgeTeacherProfiles;
  entity_versions: EntityVersions;
  expense_files: ExpenseFiles;
  expense_plans: ExpensePlans;
  expense_proposals: ExpenseProposals;
  expense_requisite_snapshots: ExpenseRequisiteSnapshots;
  extensions: Extensions;
  extensions_logs: ExtensionsLogs;
  generated_reports: GeneratedReports;
  invalidated_entities: InvalidatedEntities;
  invalidated_entity_versions: InvalidatedEntityVersions;
  ipn: Ipn;
  ku_decision_questions: KuDecisionQuestions;
  ku_decisions: KuDecisions;
  ku_trust_requests: KuTrustRequests;
  ledger_operations: LedgerOperations;
  marketplace_apl_reception: MarketplaceAplReception;
  marketplace_cart: MarketplaceCart;
  marketplace_cart_item: MarketplaceCartItem;
  marketplace_category: MarketplaceCategory;
  marketplace_consolidated_request: MarketplaceConsolidatedRequest;
  marketplace_container: MarketplaceContainer;
  marketplace_container_type: MarketplaceContainerType;
  marketplace_inventory: MarketplaceInventory;
  marketplace_issuance_saga: MarketplaceIssuanceSaga;
  marketplace_ku_details: MarketplaceKuDetails;
  marketplace_moderation_log: MarketplaceModerationLog;
  marketplace_offer: MarketplaceOffer;
  marketplace_order: MarketplaceOrder;
  marketplace_outgoing_payment_request: MarketplaceOutgoingPaymentRequest;
  marketplace_return_claim: MarketplaceReturnClaim;
  marketplace_shipment: MarketplaceShipment;
  marketplace_stock_proposal: MarketplaceStockProposal;
  marketplace_storage_cell: MarketplaceStorageCell;
  marketplace_supplier: MarketplaceSupplier;
  marketplace_supplier_claim: MarketplaceSupplierClaim;
  marketplace_supplier_settings: MarketplaceSupplierSettings;
  marketplace_supply_validation_log: MarketplaceSupplyValidationLog;
  marketplace_ttn_document: MarketplaceTtnDocument;
  marketplace_vitrine: MarketplaceVitrine;
  marketplace_writeoff_proposal: MarketplaceWriteoffProposal;
  matrix_users: MatrixUsers;
  meet_pre: MeetPre;
  meet_processed: MeetProcessed;
  membership_exit_requests: MembershipExitRequests;
  migrations: Migrations;
  mutation_logs: MutationLogs;
  notification_deliveries: NotificationDeliveries;
  notification_inbox: NotificationInbox;
  notification_outbox: NotificationOutbox;
  payment_files: PaymentFiles;
  payment_state: PaymentState;
  payments: Payments;
  program_wallets: ProgramWallets;
  report_drafts: ReportDrafts;
  report_requisites: ReportRequisites;
  report_submission_marks: ReportSubmissionMarks;
  role_assignments: RoleAssignments;
  schema_migrations: SchemaMigrations;
  settings: Settings;
  signed_documents: SignedDocuments;
  soviet_robot_decisions: SovietRobotDecisions;
  soviet_robot_keys: SovietRobotKeys;
  system_status: SystemStatus;
  tokens: Tokens;
  tracking_rules: TrackingRules;
  types: Types;
  union_chats: UnionChats;
  user_agreements: UserAgreements;
  user_wallets: UserWallets;
  users: Users;
  vaults: Vaults;
  web_push_subscriptions: WebPushSubscriptions;
}
