import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Стартовая миграция таблиц расширения «chatcoop»: 10 таблиц.
 *
 * Идемпотентна: на пустой базе создаёт всё, на базе, которую раньше вёл
 * synchronize, добавляет только недостающее и ничего не удаляет.
 *
 * Сгенерировано командой `pnpm schema:baseline` — SQL выписан TypeORM из сущностей.
 */
const UP: readonly string[] = [
  "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"",
  "CREATE TABLE IF NOT EXISTS \"matrix_users\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coop_username\" character varying NOT NULL, \"matrix_user_id\" character varying NOT NULL, \"matrix_username\" character varying NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_8bc3567992a3552521e11d22508\" UNIQUE (\"coop_username\"), CONSTRAINT \"PK_f7b6e32ab9fc81e0ca9b95863fb\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"matrix_tokens\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coop_username\" character varying NOT NULL, \"matrix_user_id\" character varying NOT NULL, \"token\" character varying NOT NULL, \"expires_at\" TIMESTAMP NOT NULL, \"is_used\" boolean NOT NULL DEFAULT false, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_25b1718a2dcd40432f9cd1aad20\" UNIQUE (\"token\"), CONSTRAINT \"PK_b8f9d9d263168daaa7eada011a3\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"union_chats\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coop_username\" character varying NOT NULL, \"matrix_user_id\" character varying NOT NULL, \"room_id\" character varying NOT NULL, \"union_person_id\" character varying NOT NULL, \"union_name\" character varying NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_c7b6ad5e47d99e0031618cbe788\" PRIMARY KEY (\"id\"))",
  "DO $$ BEGIN CREATE TYPE \"public\".\"chatcoop_call_transcriptions_status_enum\" AS ENUM('active', 'completed', 'failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$",
  "CREATE TABLE IF NOT EXISTS \"chatcoop_call_transcriptions\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"room_id\" character varying NOT NULL, \"matrix_room_id\" character varying NOT NULL, \"room_name\" character varying NOT NULL, \"started_at\" TIMESTAMP NOT NULL, \"ended_at\" TIMESTAMP, \"participants\" jsonb NOT NULL DEFAULT '[]', \"status\" \"public\".\"chatcoop_call_transcriptions_status_enum\" NOT NULL DEFAULT 'active', \"memo\" text NOT NULL DEFAULT '', \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_820d6ad842c007249eaafa40a0e\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"chatcoop_transcription_segments\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"transcription_id\" character varying NOT NULL, \"speaker_identity\" character varying NOT NULL, \"speaker_name\" character varying NOT NULL, \"text\" text NOT NULL, \"start_offset\" double precision NOT NULL, \"end_offset\" double precision NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_72f900aad5e9ee992debfa33b8a\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"chatcoop_managed_matrix_rooms\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"matrix_room_id\" character varying(255) NOT NULL, \"encrypted\" boolean NOT NULL, \"room_kind\" character varying(32) NOT NULL, \"display_label\" character varying(500) NOT NULL, \"project_hash\" character varying(64), \"secretary_in_room\" boolean NOT NULL DEFAULT false, \"message_history_pagination_token\" text, \"message_history_backfill_complete\" boolean NOT NULL DEFAULT false, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_6504adbe903181d9e5b6280afff\" UNIQUE (\"matrix_room_id\"), CONSTRAINT \"PK_a19c7e2f3a0991b30f5d34ff6f9\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"chatcoop_room_message_history\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"matrix_room_id\" character varying(255) NOT NULL, \"matrix_event_id\" character varying(255) NOT NULL, \"call_transcription_id\" uuid, \"livekit_room_name\" character varying(512), \"sender_matrix_user_id\" character varying(255) NOT NULL, \"sender_display_name\" character varying(500), \"coop_username\" character varying(255), \"message_kind\" character varying(16) NOT NULL, \"body_text\" text NOT NULL, \"origin_server_ts\" bigint NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_13c0a8df9956f8d6bf8c79a59b7\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"chatcoop_state\" (\"id\" character varying(36) NOT NULL DEFAULT 'default', \"space_id\" character varying(255), \"is_initialized\" boolean NOT NULL DEFAULT false, \"secretary_matrix_user_id\" character varying(255), \"secretary_initialized\" boolean NOT NULL DEFAULT false, \"secretary_username\" character varying(255), \"secretary_password_encrypted\" text, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_543471408b384a75b4b44682365\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"chatcoop_calendar_events\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"matrix_room_id\" character varying(255) NOT NULL, \"title\" character varying(500) NOT NULL, \"description\" text, \"starts_at\" TIMESTAMP WITH TIME ZONE NOT NULL, \"ends_at\" TIMESTAMP WITH TIME ZONE, \"created_by_username\" character varying(255) NOT NULL, \"ics_sequence\" integer NOT NULL DEFAULT '0', \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_e5d9c09afa48a1e991b219654b1\" PRIMARY KEY (\"id\"))",
  "CREATE TABLE IF NOT EXISTS \"chatcoop_calendar_ics_subscriptions\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"coop_username\" character varying(255) NOT NULL, \"secret_sha256_hex\" character varying(64) NOT NULL, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_11269ddfb5cefcf4047a56cc2cd\" PRIMARY KEY (\"id\"))",
  "ALTER TABLE \"matrix_users\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"matrix_users\" ADD COLUMN IF NOT EXISTS \"coop_username\" character varying NOT NULL",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"matrix_users\"'::regclass AND conname = 'UQ_8bc3567992a3552521e11d22508') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_8bc3567992a3552521e11d22508' AND relkind = 'i') THEN ALTER TABLE \"matrix_users\" ADD CONSTRAINT \"UQ_8bc3567992a3552521e11d22508\" UNIQUE (\"coop_username\"); END IF; END $$",
  "ALTER TABLE \"matrix_users\" ADD COLUMN IF NOT EXISTS \"matrix_user_id\" character varying NOT NULL",
  "ALTER TABLE \"matrix_users\" ADD COLUMN IF NOT EXISTS \"matrix_username\" character varying NOT NULL",
  "ALTER TABLE \"matrix_users\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"matrix_users\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"matrix_tokens\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"matrix_tokens\" ADD COLUMN IF NOT EXISTS \"coop_username\" character varying NOT NULL",
  "ALTER TABLE \"matrix_tokens\" ADD COLUMN IF NOT EXISTS \"matrix_user_id\" character varying NOT NULL",
  "ALTER TABLE \"matrix_tokens\" ADD COLUMN IF NOT EXISTS \"token\" character varying NOT NULL",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"matrix_tokens\"'::regclass AND conname = 'UQ_25b1718a2dcd40432f9cd1aad20') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_25b1718a2dcd40432f9cd1aad20' AND relkind = 'i') THEN ALTER TABLE \"matrix_tokens\" ADD CONSTRAINT \"UQ_25b1718a2dcd40432f9cd1aad20\" UNIQUE (\"token\"); END IF; END $$",
  "ALTER TABLE \"matrix_tokens\" ADD COLUMN IF NOT EXISTS \"expires_at\" TIMESTAMP NOT NULL",
  "ALTER TABLE \"matrix_tokens\" ADD COLUMN IF NOT EXISTS \"is_used\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"matrix_tokens\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"union_chats\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"union_chats\" ADD COLUMN IF NOT EXISTS \"coop_username\" character varying NOT NULL",
  "ALTER TABLE \"union_chats\" ADD COLUMN IF NOT EXISTS \"matrix_user_id\" character varying NOT NULL",
  "ALTER TABLE \"union_chats\" ADD COLUMN IF NOT EXISTS \"room_id\" character varying NOT NULL",
  "ALTER TABLE \"union_chats\" ADD COLUMN IF NOT EXISTS \"union_person_id\" character varying NOT NULL",
  "ALTER TABLE \"union_chats\" ADD COLUMN IF NOT EXISTS \"union_name\" character varying NOT NULL",
  "ALTER TABLE \"union_chats\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"room_id\" character varying NOT NULL",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"matrix_room_id\" character varying NOT NULL",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"room_name\" character varying NOT NULL",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"started_at\" TIMESTAMP NOT NULL",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"ended_at\" TIMESTAMP",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"participants\" jsonb NOT NULL DEFAULT '[]'",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"status\" \"public\".\"chatcoop_call_transcriptions_status_enum\" NOT NULL DEFAULT 'active'",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"memo\" text NOT NULL DEFAULT ''",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_call_transcriptions\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_transcription_segments\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"chatcoop_transcription_segments\" ADD COLUMN IF NOT EXISTS \"transcription_id\" character varying NOT NULL",
  "ALTER TABLE \"chatcoop_transcription_segments\" ADD COLUMN IF NOT EXISTS \"speaker_identity\" character varying NOT NULL",
  "ALTER TABLE \"chatcoop_transcription_segments\" ADD COLUMN IF NOT EXISTS \"speaker_name\" character varying NOT NULL",
  "ALTER TABLE \"chatcoop_transcription_segments\" ADD COLUMN IF NOT EXISTS \"text\" text NOT NULL",
  "ALTER TABLE \"chatcoop_transcription_segments\" ADD COLUMN IF NOT EXISTS \"start_offset\" double precision NOT NULL",
  "ALTER TABLE \"chatcoop_transcription_segments\" ADD COLUMN IF NOT EXISTS \"end_offset\" double precision NOT NULL",
  "ALTER TABLE \"chatcoop_transcription_segments\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"matrix_room_id\" character varying(255) NOT NULL",
  "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '\"chatcoop_managed_matrix_rooms\"'::regclass AND conname = 'UQ_6504adbe903181d9e5b6280afff') AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'UQ_6504adbe903181d9e5b6280afff' AND relkind = 'i') THEN ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD CONSTRAINT \"UQ_6504adbe903181d9e5b6280afff\" UNIQUE (\"matrix_room_id\"); END IF; END $$",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"encrypted\" boolean NOT NULL",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"room_kind\" character varying(32) NOT NULL",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"display_label\" character varying(500) NOT NULL",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"project_hash\" character varying(64)",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"secretary_in_room\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"message_history_pagination_token\" text",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"message_history_backfill_complete\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_managed_matrix_rooms\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"matrix_room_id\" character varying(255) NOT NULL",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"matrix_event_id\" character varying(255) NOT NULL",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"call_transcription_id\" uuid",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"livekit_room_name\" character varying(512)",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"sender_matrix_user_id\" character varying(255) NOT NULL",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"sender_display_name\" character varying(500)",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"coop_username\" character varying(255)",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"message_kind\" character varying(16) NOT NULL",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"body_text\" text NOT NULL",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"origin_server_ts\" bigint NOT NULL",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_room_message_history\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_state\" ADD COLUMN IF NOT EXISTS \"id\" character varying(36) NOT NULL DEFAULT 'default'",
  "ALTER TABLE \"chatcoop_state\" ADD COLUMN IF NOT EXISTS \"space_id\" character varying(255)",
  "ALTER TABLE \"chatcoop_state\" ADD COLUMN IF NOT EXISTS \"is_initialized\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"chatcoop_state\" ADD COLUMN IF NOT EXISTS \"secretary_matrix_user_id\" character varying(255)",
  "ALTER TABLE \"chatcoop_state\" ADD COLUMN IF NOT EXISTS \"secretary_initialized\" boolean NOT NULL DEFAULT false",
  "ALTER TABLE \"chatcoop_state\" ADD COLUMN IF NOT EXISTS \"secretary_username\" character varying(255)",
  "ALTER TABLE \"chatcoop_state\" ADD COLUMN IF NOT EXISTS \"secretary_password_encrypted\" text",
  "ALTER TABLE \"chatcoop_state\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_state\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_calendar_events\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"chatcoop_calendar_events\" ADD COLUMN IF NOT EXISTS \"matrix_room_id\" character varying(255) NOT NULL",
  "ALTER TABLE \"chatcoop_calendar_events\" ADD COLUMN IF NOT EXISTS \"title\" character varying(500) NOT NULL",
  "ALTER TABLE \"chatcoop_calendar_events\" ADD COLUMN IF NOT EXISTS \"description\" text",
  "ALTER TABLE \"chatcoop_calendar_events\" ADD COLUMN IF NOT EXISTS \"starts_at\" TIMESTAMP WITH TIME ZONE NOT NULL",
  "ALTER TABLE \"chatcoop_calendar_events\" ADD COLUMN IF NOT EXISTS \"ends_at\" TIMESTAMP WITH TIME ZONE",
  "ALTER TABLE \"chatcoop_calendar_events\" ADD COLUMN IF NOT EXISTS \"created_by_username\" character varying(255) NOT NULL",
  "ALTER TABLE \"chatcoop_calendar_events\" ADD COLUMN IF NOT EXISTS \"ics_sequence\" integer NOT NULL DEFAULT '0'",
  "ALTER TABLE \"chatcoop_calendar_events\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_calendar_events\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "ALTER TABLE \"chatcoop_calendar_ics_subscriptions\" ADD COLUMN IF NOT EXISTS \"id\" uuid NOT NULL DEFAULT uuid_generate_v4()",
  "ALTER TABLE \"chatcoop_calendar_ics_subscriptions\" ADD COLUMN IF NOT EXISTS \"coop_username\" character varying(255) NOT NULL",
  "ALTER TABLE \"chatcoop_calendar_ics_subscriptions\" ADD COLUMN IF NOT EXISTS \"secret_sha256_hex\" character varying(64) NOT NULL",
  "ALTER TABLE \"chatcoop_calendar_ics_subscriptions\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP NOT NULL DEFAULT now()",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_0d8cef56844e0bf2ced012113e\" ON \"union_chats\" (\"coop_username\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_b702a625441ea9642730a80f89\" ON \"chatcoop_call_transcriptions\" (\"room_id\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_38d0037aae40c46e9f53fa0d37\" ON \"chatcoop_call_transcriptions\" (\"matrix_room_id\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_b413e28a57a8a8bad95c999252\" ON \"chatcoop_transcription_segments\" (\"transcription_id\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_f9bb9ede3c8e8dab23cfb1c7de\" ON \"chatcoop_transcription_segments\" (\"speaker_identity\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_chatcoop_managed_matrix_rooms_room_kind\" ON \"chatcoop_managed_matrix_rooms\" (\"room_kind\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_chatcoop_room_msg_hist_room_ts\" ON \"chatcoop_room_message_history\" (\"matrix_room_id\", \"origin_server_ts\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_88e9529345ee6921dbe4de7543\" ON \"chatcoop_room_message_history\" (\"matrix_room_id\", \"matrix_event_id\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_chatcoop_calendar_events_matrix_room\" ON \"chatcoop_calendar_events\" (\"matrix_room_id\") ",
  "CREATE INDEX IF NOT EXISTS \"IDX_chatcoop_calendar_events_created_by\" ON \"chatcoop_calendar_events\" (\"created_by_username\") ",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_dc134e7cb39da2aa725bd15526\" ON \"chatcoop_calendar_ics_subscriptions\" (\"coop_username\") ",
];

export class ChatcoopBaseline1790197276755 implements MigrationInterface {
  name = 'ChatcoopBaseline1790197276755';

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {
    throw new Error('ChatcoopBaseline1790197276755 не откатывается: удаление таблиц стартовой миграции стёрло бы данные');
  }
}
