site_name: Цифровой Кооператив
extra_javascript:
  - js/metrika.js
  
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: teal

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: teal
  font:
    text: Roboto Mono
    
  logo: assets/logo-white.png
  icon:
    repo: fontawesome/brands/github
    tag:
      chairman: fontawesome/solid/user-tie
      member: fontawesome/solid/users
      user: fontawesome/solid/user
      dev: fontawesome/solid/code
  
  language: ru
  features:
    - content.code.copy
    - navigation.path
    # - navigation.tabs
    # - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.expand
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - search.share
    - navigation.top
    - navigation.footer
    
repo_url: https://github.com/coopenomics/mono

plugins:
  - search
  - macros
  - section-index
  - tags
  # - awesome-pages
  # - table-reader
  # - social:https://squidfunk.github.io/mkdocs-material/
  #   cards_layout: default

extra_css:
  - css/extra.css
  
extra:
  generator: false
  tags:
    Председатель: chairman
    Член совета: member
    Пайщик: user
    Разработчик: dev
  # social:
  #   - icon: fontawesome/brands/telegram
  #     link: https://twitter.com/your-profile

copyright: ПК «ВОСХОД» &copy; 2025

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
nav:  
  - Введение: index.md
  - Лицензия: new/installation/index.md          # Главная страница раздела
  - Облачная поставка: new/connection/index.md
  - Установка: new/installation/chairman.md
  - Дашборд подключения: new/connection/dashboard.md
  - Разработчикам:
    - new/installation/dev.md
    - Архитектура: new/installation/dev/architecture.md
    - Быстрый старт: new/installation/dev/quick-start.md
    - Язык API: new/installation/dev/graphql.md
    - SDK: new/installation/dev/sdk.md
    - Аутентификация: new/installation/dev/auth.md
    - Подробный старт: new/installation/dev/init.md
    - API Reference: new/installation/dev/api-reference.md
    
  - Регистрация пайщика: 
    - new/registration/index.md
    - Вступить в пайщики: new/registration/join.md
    - Принять пайщика: new/registration/accept.md
    - Разработчикам: new/registration/dev.md

  - Аккаунты:
    - new/accounts/index.md

  - Электронная подпись:
    - new/signature/index.md
  
  - Фабрика документов:
    - new/factory/index.md

  - Блокчейн:
    - new/blockchain/index.md
    
  - Смарт-контракты:
    - new/contracts/index.md
    
  - Навигатор: new/navigator/index.md

  - Стол пайщика:
      - Кошелёк:
          - Обзор: new/participant/wallet.md
          - Паевой взнос: new/participant/wallet-topup.md
          - Возврат взноса: new/participant/wallet-refund.md
      - Удостоверение: new/participant/profile.md
      - Реквизиты: new/participant/requisites.md
      - Документы: new/participant/documents.md
      - Платежи: new/participant/payments.md
      - Собрания: new/participant/meetings.md
      - Контакты: new/participant/contacts.md

  - Стол совета:
      - Повестка совета: new/council/agenda.md
      - Реестр пайщиков: new/council/participants.md
      - Реестр документов: new/council/documents.md
      - Реестр платежей: new/council/payments.md
      - Реестр собраний: new/council/meetings.md
      - Реестр кошельков: new/council/wallets.md
    
  - Стол председателя:
    - Запросы одобрений: new/chairman/approval-requests.md
    - Магазин приложений: new/chairman/app-store.md
    - Стартовые страницы: new/chairman/start-pages.md
    - Члены совета: new/chairman/board-members.md
    - Кооперативные участки: new/chairman/cooperative-branches.md
    - Регистрационные взносы: new/chairman/registration-fees.md
    - Ключ кооператива: new/chairman/cooperative-key.md
    - Контакты кооператива: new/chairman/cooperative-contacts.md
  
  - Стол вычислительных ресурсов:
    - Аренда квот ресурсов: new/resources/quotas.md
    - Монитор ресурсов: new/resources/monitor.md
    - Настройки аренды ресурсов: new/resources/settings.md
    - Лог ресурсов: new/resources/log.md
    
  - Стол заказов:
    - Обзор: new/cooplace/index.md
    - Маркетплейс: new/cooplace/marketplace.md
    - Разработчикам: new/cooplace/dev.md
    
  - Общие собрания: new/meet/index.md
  - Бухгалтерия: new/buh/index.md
  
  
  # - Стол совета:
  #     - Повестка совета:
  #       - Объявление собрания: manual/document-workflow-and-decisions/board-meetings/meeting-announcement.md
  #       - Повестка собрания: manual/document-workflow-and-decisions/board-meetings/meeting-agenda.md
  #       - Голосование по повестке: manual/soviet/voting.md
  #       - Утверждение протокола: manual/soviet/approve.md
  #       - Исполнение решений: manual/soviet/exec.md
      
  #     - Реестр пайщиков:
  #       - Управление пайщиками: manual/cooperative-management/participants-management/participants-registry.md
  #       - Папки пайщиков: manual/participants/folders.md
  #       - Обработка заявлений: manual/cooperative-management/participants-management/process-applications.md
      
  #     - Реестр документов:
  #       - Структура документов: manual/documents/structure.md
  #       - Папки документов: manual/documents/folders.md
  #       - Работа с документами: manual/documents/look.md
      
  #     - Реестр платежей:
  #       - Обработка платежей: manual/financial-management/payments-and-contributions/payment-processing.md
  #       - Контроль взносов: manual/workspace-management/soviet/payments/payment-control.md
  #       - Платежные провайдеры: new/members/payments/index.md
        
  #     - Реестр собраний:
  #       - Организация собраний: manual/workspace-management/soviet/meetings/organization.md
  #       - Протоколы собраний: manual/workspace-management/soviet/meetings/protocols.md
    
  # - Председателям: 
    # - О системе:
    #   - Что такое MONO: manual/about-mono/what-is-mono.md
    #   - Рабочие столы: manual/about-mono/workspaces.md
    #   - Подключение к платформе: manual/about-mono/platform-connection.md
    #   - Установка и запуск: manual/about-mono/installation.md
    #   - Стоимость использования: manual/about-mono/pricing.md
    
      
    #   - Настройки кооператива:
    #     - Управление настройками: manual/cooperative-management/cooperative-settings/settings-management.md
    #     - Настройка совета: manual/settings/soviet.md
    #     - Кооперативные участки: manual/workspace-management/chairman/settings/branches.md
    #     - Фонды накопления: manual/workspace-management/chairman/settings/accumulation-funds.md
    #     - Фонды списания: manual/workspace-management/chairman/settings/expense-funds.md
    #     - Паевые взносы: manual/workspace-management/chairman/settings/initial-contributions.md
    #     - Контакты кооператива: manual/workspace-management/chairman/settings/contacts.md
    #     - Настройка уведомлений: manual/cooperative-management/cooperative-settings/notification-setup.md
    
    
    # - Стол бухгалтера (планируется):
      # - Учёт операций: manual/workspace-management/accountant/operations/accounting.md
      # - Отчётность: manual/workspace-management/accountant/reports/financial-reports.md
      # - Налоговые документы: manual/workspace-management/accountant/tax/tax-documents.md
    
  # - Разработчикам: 
  #   - Основы платформы:
  #     - Введение: documentation/index.md
  #     - Как это работает: documentation/howitworks.md
  #     - Архитектура: documentation/architecture.md
  #     - Установка: documentation/install.md
  #     - Первый старт: documentation/init.md
    
  #   - Основные сущности:
  #     - Пользователи и аккаунты:
  #       - Аккаунты: documentation/accounts.md
  #       - Пайщики: documentation/participants.md
  #       - Соглашения: documentation/agreements.md
      
  #     - Финансы и платежи:
  #       - Кошелёк: documentation/wallet.md
  #       - Платежи и взносы: documentation/payments.md
  #       - Методы платежа: documentation/payment-methods.md
    
  #   - Управление и документооборот:
  #     - Решения и собрания:
  #       - Решения: documentation/decisions.md
  #       - Общие собрания: documentation/meetings.md
  #       - Документы: documentation/documents.md
      
  #     - Структура кооператива:
  #       - Кооперативные участки: documentation/branches.md
  #       - Фонды: documentation/funds.md
  #       - Целевые программы: documentation/programs.md
    
  #   - Расширение функциональности:
  #     - Приложения: documentation/extensions.md
  #     - Рабочий стол: documentation/desktop.md
  #     - Системная информация: documentation/system.md


  # - Пайщикам: 
    # - Начало работы:
    # - Регистрация: participants/getting-started/joining/registration.md
    #   - Первые шаги: participants/getting-started/joining/first-steps.md
    #   - Интерфейс кабинета: participants/getting-started/work-basics/interface.md
    #   - Навигация по системе: participants/getting-started/work-basics/navigation.md
    
    # - Кошелёк:
    #   - Пополнение кошелька: participants/financial-operations/wallet-and-payments/wallet-deposit.md
    #   - Просмотр баланса: participants/financial-operations/wallet-and-payments/view-balance.md
    #   - Паевые взносы: participants/financial-operations/wallet-and-payments/share-contributions.md
    #   - Возврат средств: participants/financial-operations/wallet-and-payments/refund.md
    
    # - Профиль и настройки:
    #   - Настройка профиля: participants/getting-started/work-basics/profile-setup.md
    #   - Безопасность: participants/getting-started/work-basics/security.md
    #   - Уведомления: participants/getting-started/work-basics/notifications.md
    
    # - Документы:
    #   - Мои документы: participants/documents-and-applications/document-work/my-documents.md
    #   - Подписание документов: participants/documents-and-applications/document-work/document-signing.md
    #   - Статусы заявлений: participants/documents-and-applications/document-work/application-statuses.md
    #   - Архив документов: participants/documents-and-applications/document-work/document-archive.md
    
    # - Платежи:
    #   - История платежей: participants/getting-started/work-basics/payments-history.md
    #   - Детализация операций: participants/getting-started/work-basics/transaction-details.md
    
    # - Собрания:
    #   - Участие в собраниях: participants/getting-started/work-basics/meeting-participation.md
    #   - Голосование: participants/getting-started/work-basics/voting.md
    
    # - Контакты: participants/getting-started/work-basics/contacts.md
  
    # - 🔗 SDK Docs: /sdk
    # - 🔗 GraphQL-API Docs: /graphql
    # - Документы: documentation/registration.md
    # - Платежи: documentation/registration.md
    # - Пайщики: documentation/registration.md
  # - Подключение: connect.md
  # - Контакты: contacts.md
  
 
