/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BalanceCorrections {
  account_display_id: string;
  balance_pre_previous: Generated<Numeric>;
  balance_previous: Generated<Numeric>;
  coopname: string;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  year: number;
}

export interface GeneratedReports {
  coopname: string;
  corrections_snapshot: Json | null;
  created_at: Generated<Timestamp>;
  file_name: string;
  generated_by: string;
  id: Generated<string>;
  is_valid: Generated<boolean>;
  organization_snapshot: Json;
  period: number | null;
  report_type: string;
  validation_errors: Json | null;
  xml: string;
  year: number;
}

export interface ReportDrafts {
  coopname: string;
  created_at: Generated<Timestamp>;
  edited_fields: Generated<Json>;
  edits_json: Json;
  id: Generated<string>;
  owner_username: string;
  period: number | null;
  report_type: string;
  updated_at: Generated<Timestamp>;
  year: number;
}

export interface ReportRequisites {
  address_override: string | null;
  chairman_position: string | null;
  coopname: string;
  okfs: string | null;
  okopf: string | null;
  okpo: string | null;
  oktmo: string | null;
  okved: string | null;
  pfr_reg_number: string | null;
  phone_override: string | null;
  sfr_reg_number: string | null;
  signer_inn: string | null;
  signer_rep_doc: string | null;
  signer_snils: string | null;
  signer_type: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface ReportSubmissionMarks {
  coopname: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  mark: string;
  period: number | null;
  report_type: string;
  updated_at: Generated<Timestamp>;
  year: number;
}

export interface DB {
  balance_corrections: BalanceCorrections;
  generated_reports: GeneratedReports;
  report_drafts: ReportDrafts;
  report_requisites: ReportRequisites;
  report_submission_marks: ReportSubmissionMarks;
}
