// AUTO-GENERATED by cooptypes/scripts/gen-from-cpp.ts — DO NOT EDIT.
// Source: contracts/cpp/lib/core/debt/collateral.hpp
// Run `pnpm --filter cooptypes gen:from-cpp` to regenerate.

import type { IName } from '../interfaces/ledger2'

/** Тип основания договора займа: договор об участии в хозяйственной деятельности или оферта программы. */
export type CollateralBasisType = 'UHD' | 'OFFER'

export interface CollateralMeta {
  /** Ключ обеспечения — передаётся в действие createloan. */
  key: IName
  /** Кошелёк пайщика, с которого берётся обеспечение. */
  source_wallet: IName
  /** Кошелёк обеспечения на время займа. */
  pledge_wallet: IName
  /** Операции ledger2: блокировка, возврат, обращение в пользу кооператива. */
  pledge_op: IName
  unpledge_op: IName
  seize_op: IName
  /** Контракт программы-владельца и его действие согласования; пусто — без согласования. */
  owner_contract: IName
  sync_action: IName
  /** Основание договора займа и номер шаблона документа-основания в реестре документов. */
  basis_type: CollateralBasisType
  basis_registry_id: number
  /** Наименование обеспечения для текста заявления и договора. */
  human_name: string
}

/**
 * Реестр обеспечения беспроцентных займов — точная копия `DEBT_COLLATERAL_REGISTRY` из C++.
 */
export const DEBT_COLLATERAL_REGISTRY: readonly CollateralMeta[] = [
  { key: "blago", source_wallet: "w.cap.blago", pledge_wallet: "w.cap.pledge", pledge_op: "o.cap.pledge", unpledge_op: "o.cap.unpldg", seize_op: "o.cap.seize", owner_contract: "capital", sync_action: "pledgesync", basis_type: "UHD", basis_registry_id: 1001, human_name: "имущественное право на возврат части паевого взноса по целевой потребительской программе «Благорост»" },
] as const
