/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CardcoopAttestations {
  attestation_id: string | null;
  card_id: string;
  card_number: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_error: string | null;
  member_since: string;
  revoked_at: Timestamp | null;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface CardcoopConnectState {
  delivered_hash: string | null;
  id: string;
  last_error: string | null;
  rp_client_id: string | null;
  rp_client_secret: string | null;
  rp_issuer: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CardcoopEntrySessions {
  card_id: string;
  card_number: string | null;
  created_at: Generated<Timestamp>;
  disclosure_id: string | null;
  id: Generated<string>;
  memberships: Generated<Json>;
  outcome: string;
  profile: Json | null;
  profile_taken_at: Timestamp | null;
  profile_type: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string | null;
}

export interface CardcoopOperatorAnnouncements {
  coopname: string;
  created_at: Generated<Timestamp>;
  delivered: Generated<boolean>;
  display_name: string;
  last_error: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CardcoopPendingExits {
  coopname: string;
  created_at: Generated<Timestamp>;
  exit_hash: string;
  username: string;
}

export interface CardcoopPendingLinks {
  card_id: string;
  card_number: string | null;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface CardcoopUsedGrants {
  card_id: string;
  created_at: Generated<Timestamp>;
  grant_jti: string;
  to_coopname: string;
  username: string;
}

export interface DB {
  cardcoop_attestations: CardcoopAttestations;
  cardcoop_connect_state: CardcoopConnectState;
  cardcoop_entry_sessions: CardcoopEntrySessions;
  cardcoop_operator_announcements: CardcoopOperatorAnnouncements;
  cardcoop_pending_exits: CardcoopPendingExits;
  cardcoop_pending_links: CardcoopPendingLinks;
  cardcoop_used_grants: CardcoopUsedGrants;
}
