/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ChatcoopCallTranscriptionsStatusEnum = "active" | "completed" | "failed";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ChatcoopCalendarEvents {
  created_at: Generated<Timestamp>;
  created_by_username: string;
  description: string | null;
  ends_at: Timestamp | null;
  ics_sequence: Generated<number>;
  id: Generated<string>;
  matrix_room_id: string;
  starts_at: Timestamp;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface ChatcoopCalendarIcsSubscriptions {
  coop_username: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  secret_sha256_hex: string;
}

export interface ChatcoopCallTranscriptions {
  created_at: Generated<Timestamp>;
  ended_at: Timestamp | null;
  id: Generated<string>;
  matrix_room_id: string;
  memo: Generated<string>;
  participants: Generated<Json>;
  room_id: string;
  room_name: string;
  started_at: Timestamp;
  status: Generated<ChatcoopCallTranscriptionsStatusEnum>;
  updated_at: Generated<Timestamp>;
}

export interface ChatcoopManagedMatrixRooms {
  created_at: Generated<Timestamp>;
  display_label: string;
  encrypted: boolean;
  id: Generated<string>;
  matrix_room_id: string;
  message_history_backfill_complete: Generated<boolean>;
  message_history_pagination_token: string | null;
  project_hash: string | null;
  room_kind: string;
  secretary_in_room: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface ChatcoopRoomMessageHistory {
  body_text: string;
  call_transcription_id: string | null;
  coop_username: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  livekit_room_name: string | null;
  matrix_event_id: string;
  matrix_room_id: string;
  message_kind: string;
  origin_server_ts: Int8;
  sender_display_name: string | null;
  sender_matrix_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ChatcoopState {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_initialized: Generated<boolean>;
  secretary_initialized: Generated<boolean>;
  secretary_matrix_user_id: string | null;
  secretary_password_encrypted: string | null;
  secretary_username: string | null;
  space_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ChatcoopTranscriptionSegments {
  created_at: Generated<Timestamp>;
  end_offset: number;
  id: Generated<string>;
  speaker_identity: string;
  speaker_name: string;
  start_offset: number;
  text: string;
  transcription_id: string;
}

export interface MatrixTokens {
  coop_username: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  is_used: Generated<boolean>;
  matrix_user_id: string;
  token: string;
}

export interface MatrixUsers {
  coop_username: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  matrix_user_id: string;
  matrix_username: string;
  updated_at: Generated<Timestamp>;
}

export interface UnionChats {
  coop_username: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  matrix_user_id: string;
  room_id: string;
  union_name: string;
  union_person_id: string;
}

export interface DB {
  chatcoop_calendar_events: ChatcoopCalendarEvents;
  chatcoop_calendar_ics_subscriptions: ChatcoopCalendarIcsSubscriptions;
  chatcoop_call_transcriptions: ChatcoopCallTranscriptions;
  chatcoop_managed_matrix_rooms: ChatcoopManagedMatrixRooms;
  chatcoop_room_message_history: ChatcoopRoomMessageHistory;
  chatcoop_state: ChatcoopState;
  chatcoop_transcription_segments: ChatcoopTranscriptionSegments;
  matrix_tokens: MatrixTokens;
  matrix_users: MatrixUsers;
  union_chats: UnionChats;
}
