// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type IName = string
export type IChecksum256 = string
export type IPublicKey = string
export type ISignature = string
export type ITimePointSec = string
export type IUint32 = number
export type IUint64 = number | string

export interface IAddtrusted {
  coopname: IName
  braname: IName
  trusted: IName
}

export interface IApprtrusted {
  coopname: IName
  hash: IChecksum256
  countersigned: IDocument2
  countersigned_authority: IDocument2
}

export interface IBranchstat {
  coopname: IName
  count: IUint64
}

export interface ICanceldec {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface IClosedec {
  coopname: IName
  hash: IChecksum256
  protocol: IDocument2
}

export interface IConfirmdec {
  coopname: IName
  hash: IChecksum256
  authorization: IDocument2
}

export interface ICoobranch {
  braname: IName
  trustee: IName
  trusted: IName[]
  // binary_extension-поля: могут отсутствовать у строк, созданных до добавления приватности
  is_private?: boolean
  whitelist?: IName[]
}

export interface ICoodecision {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  type: IName
  initiator: IName
  chairman: IName
  status: IName
  proposal: IDocument2
  protocol: IDocument2
  petition: IDocument2
  liability: IDocument2
  authority: IDocument2
  authorization: IDocument2
  open_at: ITimePointSec
  close_at: ITimePointSec
  signed_ballots: IUint64
  braname: IName
  address: string
  participants: IName[]
  created_at: ITimePointSec
}

export interface ICoodecquest {
  id: IUint64
  decision_id: IUint64
  number: IUint64
  coopname: IName
  title: string
  decision: string
  context: string
  counter_votes_for: IUint64
  counter_votes_against: IUint64
  counter_votes_abstained: IUint64
  voters_for: IName[]
  voters_against: IName[]
  voters_abstained: IName[]
}

export interface ICreatebranch {
  coopname: IName
  braname: IName
  trustee: IName
}

export interface ICreatedec {
  coopname: IName
  hash: IChecksum256
  type: IName
  initiator: IName
  proposal: IDocument2
  braname: IName
  agenda: IDecisionPoint[]
}

export interface IDecisionPoint {
  title: string
  decision: string
  context: string
}

export interface IDecisionVotePoint {
  question_id: IUint64
  vote: IName
}

export interface IDeclinedec {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface IDecltrusted {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface IDeletebranch {
  coopname: IName
  braname: IName
}

export interface IDeltrusted {
  coopname: IName
  braname: IName
  trusted: IName
}

export interface ISetprivate {
  coopname: IName
  braname: IName
  is_private: boolean
}

export interface IAddwhite {
  coopname: IName
  braname: IName
  account: IName
}

export interface IDelwhite {
  coopname: IName
  braname: IName
  account: IName
}

export interface IDocument2 {
  version: string
  hash: IChecksum256
  doc_hash: IChecksum256
  meta_hash: IChecksum256
  meta: string
  signatures: ISignatureInfo[]
}

export interface IEditbranch {
  coopname: IName
  braname: IName
  trustee: IName
}

export interface IExec {
  coopname: IName
  hash: IChecksum256
  petition: IDocument2
  liability: IDocument2
  authority: IDocument2
}

export interface IApprliab {
  coopname: IName
  username: IName
  approval_hash: IChecksum256
  approved_document: IDocument2
}

export interface IDeclliab {
  coopname: IName
  username: IName
  approval_hash: IChecksum256
  reason: string
}

export interface IApprauth {
  coopname: IName
  username: IName
  approval_hash: IChecksum256
  approved_document: IDocument2
}

export interface IDeclauth {
  coopname: IName
  username: IName
  approval_hash: IChecksum256
  reason: string
}

export interface IInit {
}

export interface IJoindec {
  coopname: IName
  hash: IChecksum256
  username: IName
}

export interface IMigrate {
}

export interface IReqtrusted {
  coopname: IName
  braname: IName
  username: IName
  hash: IChecksum256
  application: IDocument2
  authority: IDocument2
}

export interface ISignatureInfo {
  id: IUint32
  signed_hash: IChecksum256
  signer: IName
  public_key: IPublicKey
  signature: ISignature
  signed_at: ITimePointSec
  meta: string
}

export interface IStartdec {
  coopname: IName
  hash: IChecksum256
  chairman: IName
  address: string
  agenda: IDecisionPoint[]
}

export interface ITrustreq {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  braname: IName
  username: IName
  application: IDocument2
  authority: IDocument2
}

export interface IVotedec {
  coopname: IName
  hash: IChecksum256
  username: IName
  ballot: IDocument2
  votes: IDecisionVotePoint[]
}
