// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type IName = string
export type IUint8 = number
export type IChecksum256 = string
export type IPublicKey = string
export type ISignature = string
export type ITimePointSec = string
export type IUint32 = number
export type IUint64 = number | string

export interface IAddtrusted {
  coopname: IName
  braname: IName
  trusted: IName
}

export interface IApprtrusted {
  coopname: IName
  hash: IChecksum256
  countersigned: IDocument2
  countersigned_authority: IDocument2
}

export interface IBranchstat {
  coopname: IName
  count: IUint64
}

export interface ICanceldec {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface IClosedec {
  coopname: IName
  hash: IChecksum256
  protocol: IDocument2
}

export interface IConfirmdec {
  coopname: IName
  hash: IChecksum256
  authorization: IDocument2
}

export interface ICoobranch {
  braname: IName
  trustee: IName
  trusted: IName[]
  // binary_extension-поля: могут отсутствовать у строк, созданных до добавления приватности
  is_private?: boolean
  whitelist?: IName[]
}

export interface ICoodecision {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  type: IName
  initiator: IName
  chairman: IName
  status: IName
  proposal: IDocument2
  protocol: IDocument2
  petition: IDocument2
  liability: IDocument2
  authority: IDocument2
  authorization: IDocument2
  open_at: ITimePointSec
  close_at: ITimePointSec
  signed_ballots: IUint64
  braname: IName
  address: string
  participants: IName[]
  created_at: ITimePointSec
}

export interface ICoodecquest {
  id: IUint64
  decision_id: IUint64
  number: IUint64
  coopname: IName
  title: string
  decision: string
  context: string
  counter_votes_for: IUint64
  counter_votes_against: IUint64
  counter_votes_abstained: IUint64
  voters_for: IName[]
  voters_against: IName[]
  voters_abstained: IName[]
}

export interface ICreatebranch {
  coopname: IName
  braname: IName
  trustee: IName
}

export interface ICreatedec {
  coopname: IName
  hash: IChecksum256
  type: IName
  initiator: IName
  proposal: IDocument2
  braname: IName
  agenda: IDecisionPoint[]
}

export interface IDecisionPoint {
  title: string
  decision: string
  context: string
}

export interface IDecisionVotePoint {
  question_id: IUint64
  vote: IName
}

export interface IDeclinedec {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface IDecltrusted {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface IDeletebranch {
  coopname: IName
  braname: IName
}

export interface IDeltrusted {
  coopname: IName
  braname: IName
  trusted: IName
}

export interface ISetprivate {
  coopname: IName
  braname: IName
  is_private: boolean
}

export interface IAddwhite {
  coopname: IName
  braname: IName
  account: IName
}

export interface IDelwhite {
  coopname: IName
  braname: IName
  account: IName
}

export interface IDocument2 {
  version: string
  hash: IChecksum256
  doc_hash: IChecksum256
  meta_hash: IChecksum256
  meta: string
  signatures: ISignatureInfo[]
}

export interface IEditbranch {
  coopname: IName
  braname: IName
  trustee: IName
}

export interface IExec {
  coopname: IName
  hash: IChecksum256
  petition: IDocument2
  liability: IDocument2
  authority: IDocument2
}

export interface IApprliab {
  coopname: IName
  username: IName
  approval_hash: IChecksum256
  approved_document: IDocument2
}

export interface IDeclliab {
  coopname: IName
  username: IName
  approval_hash: IChecksum256
  reason: string
}

export interface IApprauth {
  coopname: IName
  username: IName
  approval_hash: IChecksum256
  approved_document: IDocument2
}

export interface IDeclauth {
  coopname: IName
  username: IName
  approval_hash: IChecksum256
  reason: string
}

export interface IInit {
}

export interface IJoindec {
  coopname: IName
  hash: IChecksum256
  username: IName
}

export interface IMigrate {
}

// ── Экономика кооперативного участка (requirement b6) ────────────────────

export type IAsset = string

export interface IReqtrusted {
  coopname: IName
  braname: IName
  username: IName
  hash: IChecksum256
  application: IDocument2
  authority: IDocument2
}

export interface ISignatureInfo {
  id: IUint32
  signed_hash: IChecksum256
  signer: IName
  public_key: IPublicKey
  signature: ISignature
  signed_at: ITimePointSec
  meta: string
}

export interface ISetweight {
  coopname: IName
  braname: IName
  contract: IName
  username: IName
  weight: IUint64
}

export interface IDelweight {
  coopname: IName
  braname: IName
  contract: IName
  username: IName
}

export interface IAccrue {
  coopname: IName
  braname: IName
  source_contract: IName
  amount: IAsset
  /** Имя нитки процесса контракта-источника: взнос зачисляется внутри его процесса. */
  process_type: IName
  process_hash: IChecksum256
  memo: string
}

export interface IRetfee {
  coopname: IName
  braname: IName
  source_contract: IName
  amount: IAsset
  /** Имя нитки процесса контракта-источника: взнос зачисляется внутри его процесса. */
  process_type: IName
  process_hash: IChecksum256
  memo: string
}

export interface IDistribute {
  coopname: IName
  braname: IName
  source_contract: IName
  round_hash: IChecksum256
  amount: IAsset
  memo: string
}

export interface IConvert {
  coopname: IName
  username: IName
  convert_hash: IChecksum256
  amount: IAsset
}

export interface ICreateaid {
  coopname: IName
  username: IName
  braname: IName
  aid_hash: IChecksum256
  amount: IAsset
  statement: IDocument2
  meta: string
}

export interface IOnaidauth {
  coopname: IName
  hash: IChecksum256
  authorization: IDocument2
}

export interface IOnaiddecl {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface IAidconfirm {
  coopname: IName
  outcome_hash: IChecksum256
}

export interface IAiddecline {
  coopname: IName
  outcome_hash: IChecksum256
  reason: string
}

export interface ICreatetax {
  coopname: IName
  tax_hash: IChecksum256
  /** Сумма к перечислению в бюджет; не больше остатка удержанного налога. */
  amount: IAsset
  meta: string
}

export interface ITaxconfirm {
  coopname: IName
  outcome_hash: IChecksum256
}

export interface ITaxdecline {
  coopname: IName
  outcome_hash: IChecksum256
  reason: string
}

export interface IBranchExpenseItem {
  item_hash: IChecksum256
  /** Способ оплаты позиции: 0 — аванс под отчёт, 1 — прямая оплата по реквизитам. */
  mechanics: number
  /** Получатель: 0 — сам создатель, 1 — другой пайщик, 2 — организация. */
  recipient_type: number
  recipient: IName
  description: string
  planned_amount: IAsset
  actual_amount: IAsset
  status: number
}

export interface ICreateexp {
  coopname: IName
  braname: IName
  creator: IName
  expense_hash: IChecksum256
  items: IBranchExpenseItem[]
  statement: IDocument2
}

export interface IOnexpdone {
  coopname: IName
  expense_hash: IChecksum256
  status: number
  total_actual: IAsset
  data: string
}

export interface IBranchWeight {
  id: IUint64
  braname: IName
  contract: IName
  username: IName
  weight: IUint64
}

export interface IBranchWeightTotal {
  id: IUint64
  braname: IName
  contract: IName
  total_weight: IUint64
}

export interface IBranchAid {
  id: IUint64
  hash: IChecksum256
  username: IName
  braname: IName
  amount: IAsset
  status: IName
  statement: IDocument2
  protocol: IDocument2
}

export interface IBranchTax {
  id: IUint64
  hash: IChecksum256
  /** Сумма к перечислению в бюджет. */
  amount: IAsset
  created_at: ITimePointSec
}

export interface IBranchSpend {
  id: IUint64
  hash: IChecksum256
  braname: IName
  amount: IAsset
  memo: string
}

export interface IStartdec {
  coopname: IName
  hash: IChecksum256
  chairman: IName
  address: string
  agenda: IDecisionPoint[]
}

export interface ITrustreq {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  braname: IName
  username: IName
  application: IDocument2
  authority: IDocument2
}

export interface IVotedec {
  coopname: IName
  hash: IChecksum256
  username: IName
  ballot: IDocument2
  votes: IDecisionVotePoint[]
}

export interface IBranchExpense {
  id: IUint64
  hash: IChecksum256
  braname: IName
  creator: IName
  amount: IAsset
}

export interface IItem {
  item_hash: IChecksum256
  mechanics: IUint8
  recipient_type: IUint8
  recipient: IName
  description: string
  planned_amount: IAsset
  actual_amount: IAsset
  status: IUint8
}
