// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2
// Источник правды: components/contracts/build/contracts/edubridge/edubridge.abi
// (E3 — контракт «Образовательного моста»: подписки на курсы по членскому
// кошельку w.edu.member (процесс p.edu.access) и приём РИД преподавателей
// в паевой фонд (процесс p.edu.rid) поверх Ledger2::apply).

export type IAsset = string
export type IName = string
export type IChecksum256 = string
export type IPublicKey = string
export type ISignature = string
export type ITimePointSec = string
export type IUint32 = number
export type IUint64 = number | string
export type IBool = boolean

// ── Базовые структуры (импортируются из других контрактов через ABI) ─────

export interface ISignatureInfo {
  id: IUint32
  signed_hash: IChecksum256
  signer: IName
  public_key: IPublicKey
  signature: ISignature
  signed_at: ITimePointSec
  meta: string
}

export interface IDocument2 {
  version: string
  hash: IChecksum256
  doc_hash: IChecksum256
  meta_hash: IChecksum256
  meta: string
  signatures: ISignatureInfo[]
}

// ── p.edu.access: actions ────────────────────────────────────────────────

export interface IConvert {
  coopname: IName
  username: IName
  amount: IAsset
  statement: IDocument2
}

export interface IOpensub {
  coopname: IName
  username: IName
  sub_hash: IChecksum256
  learner_id: IUint64
  course_id: IUint64
  period: IName
  paid_until: ITimePointSec
  statement_hash: IChecksum256
}

export interface IExtendsub {
  coopname: IName
  sub_hash: IChecksum256
  paid_until: ITimePointSec
  statement_hash: IChecksum256
}

export interface IExpiresub {
  coopname: IName
  sub_hash: IChecksum256
}

// ── p.edu.rid: actions ───────────────────────────────────────────────────

export interface ISubmitrid {
  coopname: IName
  username: IName
  rid_hash: IChecksum256
  assignment_id: IUint64
  amount: IAsset
  rid_type: IName
  statement: IDocument2
}

export interface IAcceptrid {
  coopname: IName
  rid_hash: IChecksum256
  decision: IDocument2
  act: IDocument2
}

export interface IDeclinerid {
  coopname: IName
  rid_hash: IChecksum256
  decision: IDocument2
}

// ── Таблицы ──────────────────────────────────────────────────────────────

/**
 * edusubs (scope = coopname) — только активные подписки; expiresub стирает запись.
 */
export interface IEduSubscription {
  id: IUint64
  sub_hash: IChecksum256
  username: IName
  learner_id: IUint64
  course_id: IUint64
  period: IName
  paid_until: ITimePointSec
  statement_hash: IChecksum256
  created_at: ITimePointSec
  updated_at: ITimePointSec
}

/**
 * edurids (scope = coopname) — заявления о взносе РИД в ожидании решения;
 * acceptrid / declinerid стирают запись.
 */
export interface IEduRid {
  id: IUint64
  rid_hash: IChecksum256
  username: IName
  assignment_id: IUint64
  amount: IAsset
  rid_type: IName
  statement_hash: IChecksum256
  created_at: ITimePointSec
}
