// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2
// Источник правды: components/contracts/build/contracts/edubridge/edubridge.abi
// (E3 — контракт «Образовательного моста»: подписки на курсы по членскому
// кошельку w.edu.member (процесс p.edu.access) и приём РИД преподавателей
// в паевой фонд (процесс p.edu.rid) поверх Ledger2::apply).

export type IAsset = string
export type IName = string
export type IChecksum256 = string
export type IPublicKey = string
export type ISignature = string
export type ITimePointSec = string
export type IUint32 = number
export type IUint64 = number | string
export type IBool = boolean

// ── Базовые структуры (импортируются из других контрактов через ABI) ─────

export interface ISignatureInfo {
  id: IUint32
  signed_hash: IChecksum256
  signer: IName
  public_key: IPublicKey
  signature: ISignature
  signed_at: ITimePointSec
  meta: string
}

export interface IDocument2 {
  version: string
  hash: IChecksum256
  doc_hash: IChecksum256
  meta_hash: IChecksum256
  meta: string
  signatures: ISignatureInfo[]
}

// ── p.edu.access: actions ────────────────────────────────────────────────

export interface IConvert {
  coopname: IName
  username: IName
  amount: IAsset
  statement: IDocument2
}

/** Позиция расхода программы: что, кому и на какую сумму. */
export interface IEduExpenseItem {
  /** Механика оплаты: 0 — аванс под отчёт, 1 — прямая оплата, 2 — по факту. */
  mechanics: number
  /** Получатель: 0 — сам создатель, 1 — другой пайщик, 2 — организация. */
  recipient_type: number
  recipient: IName
  description: string
  planned_amount: IAsset
  actual_amount: IAsset
  status: number
}

export interface ICreateexp {
  coopname: IName
  creator: IName
  expense_hash: IChecksum256
  items: IEduExpenseItem[]
  statement: IDocument2
}

export interface IOnexpdone {
  coopname: IName
  expense_hash: IChecksum256
  status: number
  total_actual: IAsset
  data: string
}

export interface IChargefee {
  coopname: IName
  username: IName
  sub_hash: IChecksum256
  /** Период оплаты: month либо course. Сумму и срок считает контракт. */
  period: IName
  /** Сумма из подписанного заявления; расхождение с расчётом контракта — отказ. */
  expected: IAsset
  statement_hash: IChecksum256
}

export interface IUnlockfee {
  coopname: IName
  sub_hash: IChecksum256
}

export interface IRegstatement {
  coopname: IName
  username: IName
  statement: IDocument2
}

export interface IWarrclaim {
  coopname: IName
  username: IName
  sub_hash: IChecksum256
  statement: IDocument2
}

export interface IWarrgrant {
  coopname: IName
  username: IName
  claim_hash: IChecksum256
  sub_hash: IChecksum256
  decision: IDocument2
}

export interface ICancelsub {
  coopname: IName
  username: IName
  sub_hash: IChecksum256
  /** Отмена курса кооперативом по недобору: взнос целиком и сразу в паевой взнос. */
  underfilled: IBool
}

export interface IRetshare {
  coopname: IName
  username: IName
  amount: IAsset
  statement: IDocument2
}

export interface IWthshare {
  coopname: IName
  username: IName
  amount: IAsset
  statement: IDocument2
}

export interface IOpensub {
  coopname: IName
  username: IName
  sub_hash: IChecksum256
  learner_id: IUint64
  course_id: IUint64
  statement_hash: IChecksum256
}

/** Условия курса: по ним контракт считает все суммы процесса. */
export interface ISetcourse {
  coopname: IName
  course_id: IUint64
  /** Плановая ставка часа, заложенная во взнос участника, — предел ставки преподавателя. */
  planned_rate: IAsset
  /** Взнос преподавателя за занятие считается за каждого участника; false — фиксированный за занятие. */
  per_learner: IBool
  target_fee_month: IAsset
  lessons_per_month: IUint32
  lessons_total: IUint32
  lesson_minutes: IUint32
  course_payment: IBool
  /** Скидка за взнос разом, сотые доли процента. */
  discount_bp: IUint32
  guarantee_days: IUint32
  /** Начало занятий; нулевое время — курс не активирован. */
  starts_at: ITimePointSec
}

export interface IExpiresub {
  coopname: IName
  sub_hash: IChecksum256
}

// ── p.edu.rid: actions ───────────────────────────────────────────────────

export interface IHoldrid {
  coopname: IName
  username: IName
  rid_hash: IChecksum256
  rid_type: IName
  act: IDocument2
}

/** Преподаватель отчитался о занятии — открывается расчёт с участниками. */
export interface IOpenlesson {
  coopname: IName
  username: IName
  rid_hash: IChecksum256
  assignment_id: IUint64
  held_at: ITimePointSec
  minutes: IUint32
}

export interface IDroplesson {
  coopname: IName
  rid_hash: IChecksum256
}

/** Расчёт за занятие по одной подписке. */
export interface IChargelesson {
  coopname: IName
  rid_hash: IChecksum256
  sub_hash: IChecksum256
}

export interface ISubmitrid {
  coopname: IName
  username: IName
  rid_hash: IChecksum256
  assignment_id: IUint64
  amount: IAsset
  rid_type: IName
  statement: IDocument2
}

export interface IAcceptrid {
  coopname: IName
  rid_hash: IChecksum256
  decision: IDocument2
  act: IDocument2
}

export interface IDeclinerid {
  coopname: IName
  rid_hash: IChecksum256
  decision: IDocument2
}

export interface IRecallrid {
  coopname: IName
  rid_hash: IChecksum256
  reason: string
}

export interface IOnRidAuth {
  coopname: IName
  hash: IChecksum256
  authorization: IDocument2
}

export interface IOnRidDecl {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface ISignRidAct {
  coopname: IName
  username: IName
  rid_hash: IChecksum256
  decision: IDocument2
  act: IDocument2
}

export interface IApprvRidAct {
  coopname: IName
  username: IName
  rid_hash: IChecksum256
  approved_document: IDocument2
}

export interface IDclRidAct {
  coopname: IName
  username: IName
  rid_hash: IChecksum256
  reason: string
}

// ── p.edu.teach: actions ─────────────────────────────────────────────────

export interface ISigncontract {
  coopname: IName
  username: IName
  contract_hash: IChecksum256
  contract: IDocument2
}

export interface IApprvcontr {
  coopname: IName
  username: IName
  contract_hash: IChecksum256
  approved_document: IDocument2
}

export interface IDclinecontr {
  coopname: IName
  username: IName
  contract_hash: IChecksum256
  reason: string
}

export interface ITermcontract {
  coopname: IName
  username: IName
  contract_hash: IChecksum256
  reason: string
}

/** Допуск преподавателя к курсу и его ставка за час на одного участника. */
export interface ISetassign {
  coopname: IName
  assignment_id: IUint64
  username: IName
  course_id: IUint64
  rate: IAsset
}

export interface IDelassign {
  coopname: IName
  assignment_id: IUint64
}

// ── Таблицы ──────────────────────────────────────────────────────────────

/**
 * edusubs (scope = coopname) — только активные подписки; expiresub стирает запись.
 */
export interface IEduSubscription {
  id: IUint64
  sub_hash: IChecksum256
  username: IName
  learner_id: IUint64
  course_id: IUint64
  period: IName
  paid_until: ITimePointSec
  statement_hash: IChecksum256
  created_at: ITimePointSec
  updated_at: ITimePointSec
  /** Собрано по подписке в фонд программы; нет у подписок, открытых до учёта собранного. */
  charged?: IAsset
  /** Из собранного выделено в резерв выплат преподавателям. */
  reserved?: IAsset
  /** Удержано до конца гарантийного срока курса. */
  locked?: IAsset
  /** Учёт занятий по подписке; version = 1 — ведётся. */
  plan?: IEduSubPlan
}

/** Учёт занятий по подписке: по нему контракт считает расчёт с преподавателем и возврат. */
export interface IEduSubPlan {
  version: number
  paid_from: ITimePointSec
  lessons_paid: IUint32
  lessons_done: IUint32
  last_lesson: IUint32
  /** Остаток оплаты занятий по плановой ставке — за непроведённые занятия. */
  reserve: IAsset
  /** Взнос преподавателей за проведённые занятия, ещё не выделенный в резерв. */
  due: IAsset
  /** Гарантийный срок участника закрыт: удерживается только сумма возможного возврата. */
  released: IBool
}

/** eduterms (scope = coopname, ключ — course_id) — условия курса, по которым считаются суммы. */
export interface IEduTerms {
  course_id: IUint64
  planned_rate: IAsset
  per_learner: IBool
  target_fee_month: IAsset
  lessons_per_month: IUint32
  lessons_total: IUint32
  lesson_minutes: IUint32
  course_payment: IBool
  discount_bp: IUint32
  guarantee_days: IUint32
  starts_at: ITimePointSec
  subs_active: IUint32
  lessons_opened: IUint32
  open_lesson_id: IUint64
  last_held_at: ITimePointSec
}

/** eduassigns (scope = coopname, ключ — assignment_id) — допуск преподавателя к курсу и его ставка. */
export interface IEduAssignment {
  assignment_id: IUint64
  username: IName
  course_id: IUint64
  rate: IAsset
}

/** edulessons (scope = coopname) — занятие, по которому идёт расчёт с участниками. */
export interface IEduLesson {
  id: IUint64
  rid_hash: IChecksum256
  course_id: IUint64
  assignment_id: IUint64
  username: IName
  number: IUint32
  held_at: ITimePointSec
  minutes: IUint32
  rate: IAsset
  /** Ставка преподавателя за проведённое время: за одного участника либо за всё занятие. */
  charge: IAsset
  /** Оплата занятия по плановой ставке за проведённое время — уходит из резерва каждой подписки. */
  unit: IAsset
  learners: IUint32
  amount: IAsset
  created_at: ITimePointSec
}

/**
 * edurids (scope = coopname) — заявления о взносе РИД в ожидании решения;
 * acceptrid / declinerid стирают запись.
 */
export interface IEduRid {
  id: IUint64
  rid_hash: IChecksum256
  username: IName
  assignment_id: IUint64
  amount: IAsset
  rid_type: IName
  statement_hash: IChecksum256
  created_at: ITimePointSec
  /** Курс, из резерва которого результат оплачивается при приёме. */
  course_id: IUint64
}

/**
 * educourses (scope = coopname, ключ — course_id) — учёт средств курса; строка
 * появляется при первом движении по курсу и переживает его подписки.
 * Целевой членский взнос по курсу равен collected − reserve − settled.
 */
export interface IEduCourse {
  /** Номер курса приложения — тот же, что в подписке. */
  course_id: IUint64
  /** Всего собрано взносов учеников по курсу за вычетом возвратов. */
  collected: IAsset
  /** Остаток резерва выплат преподавателям курса. */
  reserve: IAsset
  /** Выплачено преподавателям курса. */
  settled: IAsset
}

/**
 * educontracts (scope = coopname) — договоры УХД преподавателей: `pending` до
 * подписи председателя, `active` после; отказ (dclinecontr) стирает запись.
 */
export interface IEduContract {
  id: IUint64
  username: IName
  contract_hash: IChecksum256
  status: IName
  created_at: ITimePointSec
  approved_at: ITimePointSec
}
