// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2
// Источник правды: components/contracts/build/contracts/marketplace/marketplace.abi
// (Story 11.1 — членская модель «Стола заказов»: 21 canonical action трёх процессов
// p.mkt.supply / p.mkt.return / p.mkt.wroff поверх Ledger2::apply).
// Выплата поставщику разделена на три action'а вокруг контракта gateway
// (E11 техдолг 598-16, Locked Decision L12):
//   - payout      — backend инициирует исходящий платёж (inline → gateway::createoutpay);
//   - payconfirm  — callback gateway::outcomplete (auth=_gateway), здесь Дт 86 / Кт 51;
//   - paydecline  — callback gateway::outdecline (auth=_gateway), без ledger-движения.

export type IAsset = string
export type IName = string
export type IChecksum256 = string
export type IPublicKey = string
export type ISignature = string
export type ITimePointSec = string
export type IUint32 = number
export type IUint64 = number | string
export type IBool = boolean

// ── Базовые структуры (импортируются из других контрактов через ABI) ─────

export interface ISignatureInfo {
  id: IUint32
  signed_hash: IChecksum256
  signer: IName
  public_key: IPublicKey
  signature: ISignature
  signed_at: ITimePointSec
  meta: string
}

export interface IDocument2 {
  version: string
  hash: IChecksum256
  doc_hash: IChecksum256
  meta_hash: IChecksum256
  meta: string
  signatures: ISignatureInfo[]
}

// ── p.mkt.supply: actions ────────────────────────────────────────────────

export interface ICreateOrder {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
  offer_hash: IChecksum256
  offerer: IName
  delivery_braname: IName
  quantity: IUint64
  unit_price: IAsset
  warranty_period_secs: IUint32
  batch_hash: IChecksum256
}

export interface IStockOrder {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
  offer_hash: IChecksum256
  delivery_braname: IName
  quantity: IUint64
  unit_price: IAsset
  warranty_period_secs: IUint32
  batch_hash: IChecksum256
}

export interface IMarkdown {
  coopname: IName
  order_hash: IChecksum256
  amount: IAsset
}

export interface ICancelOrder {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
}

export interface IExpireOrder {
  coopname: IName
  order_hash: IChecksum256
}

export interface IAcceptOrder {
  coopname: IName
  offerer: IName
  order_hash: IChecksum256
}

export interface IDeclineOrder {
  coopname: IName
  offerer: IName
  order_hash: IChecksum256
}

export interface ISignSupp {
  coopname: IName
  offerer: IName
  order_hash: IChecksum256
  accept_braname: IName
  act: IDocument2
}

export interface ISignChair {
  coopname: IName
  signer: IName
  order_hash: IChecksum256
  actual_quantity: IUint64
  actual_unit_price: IAsset
  act: IDocument2
}

export interface IPayout {
  coopname: IName
  order_hash: IChecksum256
}

export interface IPayConfirm {
  coopname: IName
  outcome_hash: IChecksum256
}

export interface IPayDecline {
  coopname: IName
  outcome_hash: IChecksum256
  reason: string
}

export interface ISignIss1 {
  coopname: IName
  signer: IName
  order_hash: IChecksum256
  act: IDocument2
}

export interface ISignIss2 {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
  actual_quantity: IUint64
  actual_unit_price: IAsset
  delivery_signer: IName
  act: IDocument2
}

// ── p.mkt.return: actions ────────────────────────────────────────────────

export interface ISubmRetrn {
  coopname: IName
  orderer: IName
  request_hash: IChecksum256
  original_order_hash: IChecksum256
  actual_quantity: IUint64
  reason_text: string
  photos: IChecksum256[]
  statement: IDocument2
}

export interface IAprRetRem {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
}

export interface IRejRetRem {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
  reason: string
}

export interface IAccRetrn {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
  statement: IDocument2
}

export interface IRejRetrn {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
  reason: string
}

// ── p.mkt.wroff: actions ─────────────────────────────────────────────────

export interface IPropWroff {
  coopname: IName
  proposed_by: IName
  proposal_hash: IChecksum256
  items: IWroffItem[]
  statement: IDocument2
  meta: string
}

export interface IExecWroff {
  coopname: IName
  signer: IName
  proposal_hash: IChecksum256
  item_index: IUint64
}

/**
 * Callback от `soviet::exec` после авторизации Протокола Совета о
 * списании скоропорта (Story 8.4). Сигнатура `(coopname, hash, authorization)`
 * совпадает с AUTHORIZE_CALLBACK_SIGNATURE в soviet.hpp. Контракт `soviet`
 * вызывает action от своего имени (require_auth(_soviet)).
 */
export interface IOnMktWoAuth {
  coopname: IName
  hash: IChecksum256
  authorization: IDocument2
}

/**
 * Callback от `soviet::cancelexprd` (повестка просрочена) или decline-
 * эффекта в soviet. Сигнатура `(coopname, hash, reason)` совпадает с
 * DECLINE_CALLBACK_SIGNATURE в soviet.hpp.
 */
export interface IOnMktWoDecl {
  coopname: IName
  hash: IChecksum256
  reason: string
}

// ── Service action ───────────────────────────────────────────────────────

export interface IMigrate {
}

// ── Tables ───────────────────────────────────────────────────────────────

export interface IOrder {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  orderer: IName
  offerer: IName
  offer_hash: IChecksum256
  delivery_braname: IName
  accept_braname: IName
  current_warehouse_braname: IName
  quantity: IUint64
  actual_quantity: IUint64
  unit_price: IAsset
  total_cost: IAsset
  fact_cost: IAsset
  warranty_period_secs: IUint32
  warranty_until: ITimePointSec
  status: IName
  batch_hash: IChecksum256
  acceptance_act_signsupp: IDocument2
  acceptance_act_signchair: IDocument2
  issue_act_signiss1: IDocument2
  issue_act_signiss2: IDocument2
  payout_status: IName
  payout_decline_reason: string
  return_request_id: IUint64
  /** Списанная уценка по заказу из остатка (binary_extension; у старых строк отсутствует). */
  markdown_cost?: IAsset
}

export interface IReturnRequest {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  orderer: IName
  original_order_id: IUint64
  original_order_hash: IChecksum256
  original_consume_op_id: IChecksum256
  actual_quantity: IUint64
  fact_cost: IAsset
  reason_text: string
  photos: IChecksum256[]
  status: IName
  statement: IDocument2
  decision_remote: IDocument2
  decision_visit: IDocument2
  reason_remote: string
  reason_visit: string
}

export interface IWroffItem {
  source_order_id: IUint64
  braname: IName
  amount: IAsset
  meta: string
  executed: IBool
}

export interface IWriteoffProposal {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  proposed_by: IName
  decided_by: IName
  items: IWroffItem[]
  total_amount: IAsset
  status: IName
  protocol: IDocument2
  reject_reason: string
}
